### ISSUE TITLE
Another airdrop.

### ISSUE THREAD

**Issue by jodiekurnia** [thebrumby/HotWalletClaimer#10]
Hi, are you interested in doing other airdrop like TapSwap/YesCoin etc?
Most script on github are using pyrogam which will cause new tele account being ban 🥲

**Comment by jodiekurnia** [comment]
Also as a suggestion, can you create new feature on wave? like auto upgrade boat when have enough balance? it would makes claim much longer but each claim get more ocean + less pay for gass fee

**Comment by doubleTroub1e** [comment]
hey, you can also find yescoin and tapswap here
https://github.com/shamhi/YesCoinBot

**Comment by jodiekurnia** [comment]
> hey, you can also find yescoin and tapswap here https://github.com/shamhi/YesCoinBot

yes I try those but got instant ban on my telegram account

**Comment by thebrumby** [comment]
> Hi, are you interested in doing other airdrop like TapSwap/YesCoin etc? Most script on github are using pyrogam which will cause new tele account being ban 🥲

Hi, I won't be able to complete that this week, but I'm happy to give it a go next week when more time allows :)

**Comment by thebrumby** [comment]
> Also as a suggestion, can you create new feature on wave? like auto upgrade boat when have enough balance? it would makes claim much longer but each claim get more ocean + less pay for gass fee

Thanks for the suggestion, but I'll pass on this one. While it would be pretty easy to do, but different people have different strategies. I like to upgrade the mining speed first, then extend the claim time. Other people do it the other way around. Plus then I'd get people say "Where's my coins gone?", "You're script took my coins"! So overall, best left alone :)

**Comment by doubleTroub1e** [comment]
>yes I try those but got instant ban on my telegram account

those work fine for me, but I don't use any proxy or multiacc, only my account

**Comment by jodiekurnia** [comment]
> > Also as a suggestion, can you create new feature on wave? like auto upgrade boat when have enough balance? it would makes claim much longer but each claim get more ocean + less pay for gass fee
> 
> Thanks for the suggestion, but I'll pass on this one. While it would be pretty easy to do, but different people have different strategies. I like to upgrade the mining speed first, then extend the claim time. Other people do it the other way around. Plus then I'd get people say "Where's my coins gone?", "You're script took my coins"! So overall, best left alone :)

It should be an option at least, enable upgrade mining speed + enable upgrade claim time.

**Comment by Wellynounet** [comment]
it's not very hard to click on a button every 5-10 days and more to level up and the more you level up the longer it takes i don't think it's extremely important to have this we should be very happy not to have to click every 2 hours on all our accounts
