### ISSUE TITLE
Is this pm2 normal behavior 

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#100]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/6bb7cd1e-0340-4622-9d0b-3694a7d3574a)

been tryna run bot without any errors is this normal behavior ?

**Comment by laggedv1** [comment]
More info 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/93de0297-4e3f-481d-a743-e3dd75778631)
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/4be21419-a1a1-4808-acd1-e903a875a707)

I have same chromium & chromedriver versions

**Comment by laggedv1** [comment]
More info 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/dbf61de3-2138-42a0-88ce-17ae8686ab7a)

![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/2386559b-a9ec-4d86-8b52-79a9707a97d5)
Chromedriver & chromium same version

**Comment by laggedv1** [comment]
First error after  ./launch.sh is :  mkdir cannot create directory /run/user/0' Permission denied, then again error from first picture, im tryna get the workaround will post it for newbies help if i find it

**Comment by thebrumby** [comment]
Hi,

1. No, that's not normal for PM2.
2. The default installer generally installs Google Chrome, not Chromium. If you are running an AMD64 machine (not ARM), you can run the installer again to try and change back to Chrome.
3. If you are running `./launch.sh` from inside `/home/tonton/HotWalletBot`, then the directories the script creates should be subdirectories of `/home/tonton/HotWalletBot`. Possibly Chromium-Browser is trying to create something under `/run/user/0`?

If you're having problems with dependencies, I'd switch to Docker where the container will have everything prebuilt from the latest image.

Thanks

**Comment by laggedv1** [comment]
> Hi,
> 
>     1. No, that's not normal for PM2.
> 
>     2. The default installer generally installs Google Chrome, not Chromium. If you are running an AMD64 machine (not ARM), you can run the installer again to try and change back to Chrome.
> 
>     3. If you are running `./launch.sh` from inside `/home/tonton/HotWalletBot`, then the directories the script creates should be subdirectories of `/home/tonton/HotWalletBot`. Possibly Chromium-Browser is trying to create something under `/run/user/0`?
> 
> 
> If you're having problems with dependencies, I'd switch to Docker where the container will have everything prebuilt from the latest image.
> 
> Thanks

Thanks for the fast response, i switch to updated chrome still get this error : 

mkdir: cannot create directory /run/user/0 : permission denied 

Any workaround?

**Comment by thebrumby** [comment]
Hi,

This script doesn’t create any directories in the directory you listed, so it’s probably one of the third-party modules/software not working well with the VM. 

Our supported methods are Ubuntu (VPS or native install), Ubuntu for Windows or Docker. 

I’d recommend using one of those methods, the script can then be installed with two sets of copied and pasted commands.

**Comment by laggedv1** [comment]
Fixed after i uninstalled chromium , thanks for the help
