### ISSUE TITLE
Gamee question

### ISSUE THREAD

**Issue by LFQO** [thebrumby/HotWalletClaimer#104]
Hi, is it possible to make log in to Gamee by using Open App button that is located on the left from message field?
For me this is essential because, for whatever reason, bot communicates with me in different languages and doesn't use English. 
I've tried to change telegram language and os language and region, but it still doesn't use English. There is also no language setting in the bot, so I guess it's impossible to change communication language

**Comment by thebrumby** [comment]
Hi Gamee, is currently not working anyway after they blocked access via Telegram web. If we are able to restore it, we'll look at the login button.

Thanks
