### ISSUE TITLE
Bring back ./remove-process.sh

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#105]
Hi recently update may be you remove the remove process command. I think it important to remove complete not working process

**Comment by thebrumby** [comment]
Hi,

As documented in the instructions, deleting processes is now handled by `./lanch.sh status`. 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/ef862e74-cf22-4921-9b0d-5c77d302671d)

**Comment by bscongluanbui** [comment]
> Hi,
> 
> As documented in the instructions, deleting processes is now handled by `./lanch.sh status`.
> 
> ![image](https://private-user-images.githubusercontent.com/29182343/345861345-ef862e74-cf22-4921-9b0d-5c77d302671d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDY5MjIsIm5iZiI6MTcyMDEwNjYyMiwicGF0aCI6Ii8yOTE4MjM0My8zNDU4NjEzNDUtZWY4NjJlNzQtY2YyMi00OTIxLTliMGQtNWM3N2QzMDI2NzFkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxNTIzNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZmU4YmUyMzVmNzdiNjA1NGNkZWEwNDVkNGExZDMzNDZkMDJjNWE1YTBlNmI0NmI4NTk2YTI4ZDI0NzYxMTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BB947E5WEHEPUW7G_YhLwMw1WBf8JDwzrRM4Qc_yNZQ)

if I config an erorr session. I cant delete it because it not show on status

**Comment by thebrumby** [comment]
Hi,

Please attach your image, all I see is a broken link.

Thanks

**Comment by bscongluanbui** [comment]
> Hi,
> 
> 
> 
> Please attach your image, all I see is a broken link.
> 
> 
> 
> Thanks

I mean if I got an error sesion and I want to delete it, I need old methods because status methods only work if I config succeed

**Comment by thebrumby** [comment]
Are you sure? Any game session that exists in folder structure but not in PM2 should be listed in the inactive processes table at the top.

**Comment by thebrumby** [comment]
Sure we will consider this. @jbr1989 is doing some great work in the background around the utilities and we hope to have some updates in the coming weeks.
