### ISSUE TITLE
proxy operation

### ISSUE THREAD

**Issue by ATAMAH161** [thebrumby/HotWalletClaimer#109]
Good afternoon. Can you tell me which proxies I can use to work in the script at the moment? As I understand it, proxies with login and password are not suitable. Then it turns out that you need to take public ones?

**Comment by thebrumby** [comment]
Hi,

You can use the built-in proxy which will use various techniques to try and make it look like the game is being accessed by a mobile phone. Some games (Blum & Vertus) won't work well without this enabled. 

There is the option to set another IP address to make the proxy connection, but if you wish to connect with a username and password, it apparently requires a Chrome extension, which is currently out-of-scope for this project.
