### ISSUE TITLE
oxygen isue

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#110]
Hi I get trouble of Oxygen recently. I tried many method but not working. I access it on web and got this
![image](https://github.com/thebrumby/HotWalletClaimer/assets/102287592/e7119491-d21d-4001-ab36-c5f81cdd83b1)
I can access on mobile. Anyone can help me

**Comment by thebrumby** [comment]
Hi,

Oxygen is currently working on TG Web for me, and also in the bot.

I'm using the built-in proxy and setting a custom user agent for oxygen miner.
