### ISSUE TITLE
Request: New Games Suggestions 

### ISSUE THREAD

**Issue by HoN3YP0T** [thebrumby/HotWalletClaimer#113]
Hey, Love Your Work I've been running this Claimer Since past 1 month on my Ubuntu server.
It works really well. I have a suggestion of few games could you please add them
1. Hamster Kombat Auto Farming 
2. MemeFi
3. Hamster chain

**Comment by thebrumby** [comment]
Hi,

Thank you for the suggestions. We'll take a look when we have time to integrate another game. It’s great to know you've found the script helpful so far.

Just a heads-up: not all games are suitable for use with this system. Many of the scripts we see on GitHub work by having the user extract their access token from the Telegram GUI to interact directly with the game API. Our script, however, launches a Google Chrome session and uses a third-party Python module called Selenium to scroll, move, and click in the browser session, emulating human-like behavior.

While we could use the same method as other scripts to add certain games, it would just duplicate existing solutions and dilute the purpose of this project.

That said, if the games work in a browser on Telegram Web, we will certainly consider adding them as time allows.

**Comment by thebrumby** [comment]
Maybe you could include the links to the bots to ensure we don't get a spam copy?

**Comment by HoN3YP0T** [comment]
Here are links of some of the most popular mining Airdrops
Tap swap :- https://t.me/tapswap_mirror_1_bot?profile
Hamster chain:-  https://t.me/hamsterchainbot/start?startapp=Deepuxd
MemeFi :- https://t.me/memefi_coin_bot?start=r_b8c32ca5c9
Banana : https://t.me/OfficialBananaBot/banana?startapp=referral=GARJTE6
Hamster Kombat :-  https://t.me/hamster_koMbat_bot/start?startapp=kentId6943272272
