### ISSUE TITLE
Request Fix: Blum

### ISSUE THREAD

**Issue by smolpepe59** [thebrumby/HotWalletClaimer#114]
Can you fix the **Blum** auto claim? Also how can I learn coding like this? I love your work man!

**Comment by Wellynounet** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/262822fb-04f8-4a14-b13c-d9a1a54d9ca1)

hello blum working well  
can you explain more what happend ?

**Comment by smolpepe59** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/139532388/9d4234d0-50f0-4bd2-a541-1471ad4e4dc7)


not claiming on mine, idk what is the problem

**Comment by smolpepe59** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/139532388/20b4821e-7147-48d0-8165-b7df18d2a023)

double checked on the app, its now available to be claimed but the script can't detect it

**Comment by Wellynounet** [comment]
what the message before 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/9c4cf050-1230-4ac9-8899-b9fc617f3f6f)

**Comment by smolpepe59** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/139532388/31aeee4e-643c-4020-8fe3-9d9cf0671f4f)

here

**Comment by thebrumby** [comment]
Hi,

Looking at your screenshots, it appears that all interactions with Telegram, such as finding the link to open the app, are working correctly; this would suggest that you are correctly logged into Telegram and connecting to the internet correctly (steps 100-104). 

Once the script moves on to interacting with Blum, **every** step fails (steps 105-109).

This would suggest that if the game was correctly set up and ready to claim, as you say, then the proxy process is not working correctly. Assuming you are running the latest version of the scripts in the repository, you could try restarting it and then restart your Blum session:

```
pm2 restart http-proxy
```

Or delete it and make it reinstall, watching out for any errors:
```
pm2 delete http-proxy
pm2 save
```
After using the commands above to delete it, you'd need to restart the Blum session to trigger the reinstall of the proxy.

Thanks.

**Comment by smolpepe59** [comment]
Thank you for your quick response, however I'm still getting the same response despite of doing what you said. Is there any way to debug or check if the http module is working properly?

**Comment by Wellynounet** [comment]
yes enable verbose 3 in variable.txt 
do you have manually enable blum ? you have to do the first step by the hand  if you have a new account

**Comment by smolpepe59** [comment]
Blum is enabled and I'm already playing it for some time. 

verbose already enabled too, this is my current settings 

{"forceClaim": true, "debugIsOn": false, "hideSensitiveInput": true, "screenshotQRCode": true, "maxSessions": 1, "verboseLevel": 3, "lowestClaimOffset": 0, "highestClaimOffset": 10, "forceNewSession": false, "useProxy": false, "proxyAddress": "http://127.0.0.1:8080", "requestUserAgent": false}

**Comment by Wellynounet** [comment]
enable proxy  
you need proxi to get blum working 
proxi its a feature build in  
you dont have to pay something just enable and blum working

**Comment by smolpepe59** [comment]
Got it, thank you for this!

**Comment by thebrumby** [comment]
To debug the http-proxy itself, you could change line 7 or 8 from:
```
log_to_file = False  # Set this to False to log to /dev/null
```
to:
```
log_to_file = True  # Set this to False to log to /dev/null
```
as @Wellynounet says, you can also change the verbose level to show all steps (3) and/or enable debugging in settings or variables.txt. With debugging enabled you can see some "screenshots" of the virtual browser session.

**Comment by smolpepe59** [comment]
should i edit the default proxy?

 Enter the Proxy IP address and port (current: http://127.0.0.1:8080):

**Comment by Wellynounet** [comment]
na dont touch anythings jsut enter enter enter :!)

**Comment by thebrumby** [comment]
Just as an FYI, as Blum requires the proxy on to function, it contains this line in blum.py:

```
self.forceLocalProxy = True
```

That means that with default code and default settings, it should have worked without any problem or debugging!

**Comment by smolpepe59** [comment]
It worked, so the error was the proxy settings is not enabled. Thank you so much

**Comment by Wellynounet** [comment]
Thanks you for your support
