### ISSUE TITLE
PixelTap working?

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#116]
For me pixel tap crashes into infinite reboots is it working rn? everything else works fine ly brumby

**Comment by laggedv1** [comment]
Lumcity also off for me 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/080da498-580e-4ba9-8a51-67b489bbfe41)
every else gucci, just me or?

**Comment by thebrumby** [comment]
Hi, 

I've uploaded a fix for if Lumcity is not able to return a wait time value. If the original error is being caused by the script not being able to return the wait time, it won't solve the problem, but will let the script handle it more gracefully. 

Pixel Tap is working fine for me. You could either use `./launch.sh status` to delete and stuck sessions, and watch for errors when setting them up again, or share any screenshots you have of the errors.

Thanks

**Comment by thebrumby** [comment]
One additional thought, sometimes the Telegram session that games are created with get revoked, if you get a lot of errors when recreating the session, it might be worth starting with a new TG session.

**Comment by laggedv1** [comment]
> One additional thought, sometimes the Telegram session that games are created with get revoked, if you get a lot of errors when recreating the session, it might be worth starting with a new TG session.

Thanks for your help will try, how can i update fast? i dont find any command

**Comment by Wellynounet** [comment]
./pull-games.sh

**Comment by laggedv1** [comment]
> `./pull-games.sh`

![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/aa9fcd65-8b3f-4911-ae14-17878e27e07c)

**Comment by laggedv1** [comment]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/ac43f849-697f-4bb2-803d-b78c7ca9068b)

**Comment by laggedv1** [comment]
bro 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/c745d502-ffa8-4ff8-802c-9eddbc9c53ef)

**Comment by laggedv1** [comment]
Ok nvm i seen its located in another folder thx 👍

**Comment by Wellynounet** [comment]
a yeah `git pull ` on ubuntu :) 
./pull-games.sh  on docker

**Comment by laggedv1** [comment]
ty will reopen if i find pixel tap errors

**Comment by laggedv1** [comment]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/b5303ee6-234a-4298-b9dc-96fb4a6e4f2a)
if its working obv a problem on my end, any hint anyways?

**Comment by laggedv1** [comment]
Also tried w a fresh telegram session to check out, still crashes

**Comment by laggedv1** [comment]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/7fb8acdd-f357-4f1c-8d16-2956281de02f)

**Comment by laggedv1** [comment]
Also lumcity 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/48ca982b-a36a-473a-b45b-f32b125e7a0c)

**Comment by laggedv1** [comment]
Hexacore too 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/79828d3b-aee4-476d-920a-2429b9ba39d6)

**Comment by laggedv1** [comment]
pixeltap still off, managed to get everything else working tho

**Comment by laggedv1** [comment]
using another pixeltap bot ty for help anyway

**Comment by thebrumby** [comment]
No problem. Sorry it didn't work for you, but working fine for us.

**Comment by laggedv1** [comment]
> No problem. Sorry it didn't work for you, but working fine for us.

All gucci thanks for the great work <3
