### ISSUE TITLE
Log out and can not log in again

### ISSUE THREAD

**Issue by Neo19867** [thebrumby/HotWalletClaimer#118]
I have such problem like here: https://github.com/thebrumby/HotWalletClaimer/issues/92
What can i do?

**Comment by thebrumby** [comment]
Hi @Neo19867 

It's failing on the 2-factor authentication, like in the other post?

**Comment by Neo19867** [comment]
Yes it is. But in fact it is logged in when i look at the logged devices. But script did not see it.

**Comment by thebrumby** [comment]
Hi, 

I couldn’t recreate this error? Maybe turn off your 2fa, save your TG session, and turn 2fa back on?

Once the session data is saved, it no longer requires the password.
