### ISSUE TITLE
Feature Request: Add another proxy protocol

### ISSUE THREAD

**Issue by rostamzad1900** [thebrumby/HotWalletClaimer#119]
hey phil
thanks for your great work.
me and my friends was fascinated by your work and we want to use this awesome project
but there is some technical issue to lunch docker or other way you suggested.
telegram in my country was banned by regime, they want to silent us and suppress people.
every single person in my country use a vpn or proxy for social apps.
several vpn and proxy i was used and common point to all of this is "Socks5" protocol.
if u add this protocol to proxy part, i would be so grateful.
thank you in advance

**Comment by thebrumby** [comment]
Hi,

I’m pleased to hear you find the project interesting. I will look at adding better proxy support next week. 

Thanks

**Comment by thebrumby** [comment]
After spending most of the day experimenting with different methods to implement proxy support in the project, I ultimately decided not to proceed with it.

While it is technically possible to enable proxy authentication in Selenium by modifying Chromedriver or creating a JavaScript listener as part of a custom Chrome extension, these approaches introduce complexities that extend beyond the intended scope of this project.

For these reasons, I've chosen to keep the project focused on its core objectives without adding proxy support at this time.

Thank you for understanding.

Best regards, Phil

**Comment by thebrumby** [comment]
In an update to the earlier message, we have a solution that will allow one external proxy to be nominated. Currently the only way to have multiple credentials would be to create separate Docker containers for each required connection.

https://www.patreon.com/posts/support-added-110409861?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link
