### ISSUE TITLE
Error when installing Python Script

### ISSUE THREAD

**Issue by Mkeith34** [thebrumby/HotWalletClaimer#120]
Hi Phi,

Can you please help me with this error:

[PM2] Spawning PM2 daemon with pm2_home=/home/pi2/.pm2
[PM2] PM2 Successfully daemonized
5.4.2
Python version: Python 3.11.2
Node.js version: v22.4.0
npm version: 10.8.1
Chromium/Chrome version: 125.0.6422.133
Chromedriver version:
Architecture: aarch64
Note: x86_64 users can run this script again to switch between Google Chrome/Chr                                                       omium browsers.
pi2@raspberrypi:~/HotWalletBot $ ./launch.sh hot
Activating virtual environment...
Running script: ./games/hot.py with arguments:
Traceback (most recent call last):
  File "/home/pi2/HotWalletBot/./games/hot.py", line 14, in <module>
    from selenium import webdriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdri                                                       ver/__init__.py", line 20, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdri                                                       ver/chrome/webdriver.py", line 18, in <module>
    from selenium.webdriver.chromium.webdriver import ChromiumDriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdri                                                       ver/chromium/webdriver.py", line 22, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdri                                                       ver/remote/webdriver.py", line 67, in <module>
    from .websocket_connection import WebSocketConnection
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdri                                                       ver/remote/websocket_connection.py", line 23, in <module>
    from websocket import WebSocketApp
ModuleNotFoundError: No module named 'websocket'
Deactivating virtual environment...

**Comment by thebrumby** [comment]
Hi,

Looking at your output, Chromedriver didn't get installed. You can always try to get the latest code

```
git pull
```

from within the HotWalletBot directory, and repeat the installer.

```
./install.sh
```

If you can't resolve the dependencies, I'd recommend installing [Docker](docs/DOCKER.md) and using the pre-built image with all the dependencies pre-built.

Thanks.

**Comment by Mkeith34** [comment]
Hi Thebrumby,

Thank you for replying and sorry for my late reaction.

i just try the code pit pull and i get the same error. 

pi2@raspberrypi:~/HotWalletBot $ git pull
Already up to date.
pi2@raspberrypi:~/HotWalletBot $ ./install.sh
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.nodesource.com/node_22.x nodistro InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
snapd is already the newest version (2.57.6-1+b5).
curl is already the newest version (7.88.1-10+deb12u6).
wget is already the newest version (1.21.3-1+b1).
python3 is already the newest version (3.11.2-1+b1).
python3-pip is already the newest version (23.0.1+dfsg-1+rpt1).
libzbar0 is already the newest version (0.23.92-7+deb12u1).
unzip is already the newest version (6.0-28).
python3-venv is already the newest version (3.11.2-1+b1).
gdebi-core is already the newest version (0.9.5.7+nmu6).
The following packages were automatically installed and are no longer required:
  libcamera0.2 libraspberrypi0 libwpe-1.0-1 libwpebackend-fdo-1.0-1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: wheel in ./venv/lib/python3.11/site-packages (0.43.0)
Requirement already satisfied: selenium in ./venv/lib/python3.11/site-packages (4.22.0)
Requirement already satisfied: Pillow in ./venv/lib/python3.11/site-packages (10.4.0)
Requirement already satisfied: pyzbar in ./venv/lib/python3.11/site-packages (0.1.9)
Requirement already satisfied: qrcode-terminal in ./venv/lib/python3.11/site-packages (0.8)
Requirement already satisfied: python-telegram-bot in ./venv/lib/python3.11/site-packages (21.4)
Requirement already satisfied: requests in ./venv/lib/python3.11/site-packages (2.32.3)
Requirement already satisfied: mitmproxy in ./venv/lib/python3.11/site-packages (10.3.1)
Requirement already satisfied: typing-extensions~=4.9 in ./venv/lib/python3.11/site-packages (from selenium) (4.12.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in ./venv/lib/python3.11/site-packages (from selenium) (2.2.2)
Requirement already satisfied: trio~=0.17 in ./venv/lib/python3.11/site-packages (from selenium) (0.26.0)
Requirement already satisfied: trio-websocket~=0.9 in ./venv/lib/python3.11/site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in ./venv/lib/python3.11/site-packages (from selenium) (2024.7.4)
Requirement already satisfied: qrcode in ./venv/lib/python3.11/site-packages (from qrcode-terminal) (7.4.2)
Requirement already satisfied: httpx~=0.27 in ./venv/lib/python3.11/site-packages (from python-telegram-bot) (0.27.0)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests) (3.7)
Requirement already satisfied: aioquic<=1.0.0,>=1.0.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.0.0)
Requirement already satisfied: asgiref<=3.8.1,>=3.2.10 in ./venv/lib/python3.11/site-packages (from mitmproxy) (3.8.1)
Requirement already satisfied: Brotli<=1.1.0,>=1.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.1.0)
Requirement already satisfied: cryptography<42.1,>=42.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (42.0.8)
Requirement already satisfied: flask<=3.0.3,>=3.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (3.0.3)
Requirement already satisfied: h11<=0.14.0,>=0.11 in ./venv/lib/python3.11/site-packages (from mitmproxy) (0.14.0)
Requirement already satisfied: h2<=4.1.0,>=4.1 in ./venv/lib/python3.11/site-packages (from mitmproxy) (4.1.0)
Requirement already satisfied: hyperframe<=6.0.1,>=6.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (6.0.1)
Requirement already satisfied: kaitaistruct<=0.10,>=0.10 in ./venv/lib/python3.11/site-packages (from mitmproxy) (0.10)
Requirement already satisfied: ldap3<=2.9.1,>=2.8 in ./venv/lib/python3.11/site-packages (from mitmproxy) (2.9.1)
Requirement already satisfied: mitmproxy-rs<0.6,>=0.5.1 in ./venv/lib/python3.11/site-packages (from mitmproxy) (0.5.2)
Requirement already satisfied: msgpack<=1.0.8,>=1.0.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.0.8)
Requirement already satisfied: passlib<=1.7.4,>=1.6.5 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.7.4)
Requirement already satisfied: protobuf<=5.27.0,>=3.14 in ./venv/lib/python3.11/site-packages (from mitmproxy) (5.27.0)
Requirement already satisfied: pyOpenSSL<=24.1.0,>=22.1 in ./venv/lib/python3.11/site-packages (from mitmproxy) (24.1.0)
Requirement already satisfied: pyparsing<=3.1.2,>=2.4.2 in ./venv/lib/python3.11/site-packages (from mitmproxy) (3.1.2)
Requirement already satisfied: pyperclip<=1.8.2,>=1.6.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.8.2)
Requirement already satisfied: ruamel.yaml<=0.18.6,>=0.16 in ./venv/lib/python3.11/site-packages (from mitmproxy) (0.18.6)
Requirement already satisfied: sortedcontainers<=2.4.0,>=2.3 in ./venv/lib/python3.11/site-packages (from mitmproxy) (2.4.0)
Requirement already satisfied: tornado<=6.4,>=6.2 in ./venv/lib/python3.11/site-packages (from mitmproxy) (6.4)
Requirement already satisfied: urwid-mitmproxy<2.2,>=2.1.1 in ./venv/lib/python3.11/site-packages (from mitmproxy) (2.1.2.1)
Requirement already satisfied: wsproto<=1.2.0,>=1.0 in ./venv/lib/python3.11/site-packages (from mitmproxy) (1.2.0)
Requirement already satisfied: publicsuffix2<=2.20191221,>=2.20190812 in ./venv/lib/python3.11/site-packages (from mitmproxy) (2.20191221)
Requirement already satisfied: zstandard<=0.22.0,>=0.15 in ./venv/lib/python3.11/site-packages (from mitmproxy) (0.22.0)
Requirement already satisfied: pylsqpack<0.4.0,>=0.3.3 in ./venv/lib/python3.11/site-packages (from aioquic<=1.0.0,>=1.0.0->mitmproxy) (0.3.18)
Requirement already satisfied: service-identity>=24.1.0 in ./venv/lib/python3.11/site-packages (from aioquic<=1.0.0,>=1.0.0->mitmproxy) (24.1.0)
Requirement already satisfied: cffi>=1.12 in ./venv/lib/python3.11/site-packages (from cryptography<42.1,>=42.0->mitmproxy) (1.16.0)
Requirement already satisfied: Werkzeug>=3.0.0 in ./venv/lib/python3.11/site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (3.0.3)
Requirement already satisfied: Jinja2>=3.1.2 in ./venv/lib/python3.11/site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (3.1.4)
Requirement already satisfied: itsdangerous>=2.1.2 in ./venv/lib/python3.11/site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (2.2.0)
Requirement already satisfied: click>=8.1.3 in ./venv/lib/python3.11/site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in ./venv/lib/python3.11/site-packages (from flask<=3.0.3,>=3.0->mitmproxy) (1.8.2)
Requirement already satisfied: hpack<5,>=4.0 in ./venv/lib/python3.11/site-packages (from h2<=4.1.0,>=4.1->mitmproxy) (4.0.0)
Requirement already satisfied: anyio in ./venv/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (4.4.0)
Requirement already satisfied: httpcore==1.* in ./venv/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.0.5)
Requirement already satisfied: sniffio in ./venv/lib/python3.11/site-packages (from httpx~=0.27->python-telegram-bot) (1.3.1)
Requirement already satisfied: pyasn1>=0.4.6 in ./venv/lib/python3.11/site-packages (from ldap3<=2.9.1,>=2.8->mitmproxy) (0.6.0)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in ./venv/lib/python3.11/site-packages (from ruamel.yaml<=0.18.6,>=0.16->mitmproxy) (0.2.8)
Requirement already satisfied: attrs>=23.2.0 in ./venv/lib/python3.11/site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: outcome in ./venv/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in ./venv/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pypng in ./venv/lib/python3.11/site-packages (from qrcode->qrcode-terminal) (0.20220715.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.11/site-packages (from cffi>=1.12->cryptography<42.1,>=42.0->mitmproxy) (2.22)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from Jinja2>=3.1.2->flask<=3.0.3,>=3.0->mitmproxy) (2.1.5)
Requirement already satisfied: pyasn1-modules in ./venv/lib/python3.11/site-packages (from service-identity>=24.1.0->aioquic<=1.0.0,>=1.0.0->mitmproxy) (0.4.0)
2024-07-14 21:05:28 - Installing pre-requisites
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.nodesource.com/node_22.x nodistro InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
apt-transport-https is already the newest version (2.6.1).
ca-certificates is already the newest version (20230311).
curl is already the newest version (7.88.1-10+deb12u6).
gnupg is already the newest version (2.2.40-1.1).
The following packages were automatically installed and are no longer required:
  libcamera0.2 libraspberrypi0 libwpe-1.0-1 libwpebackend-fdo-1.0-1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.nodesource.com/node_22.x nodistro InRelease
Reading package lists... Done
2024-07-14 21:05:39 - Repository configured successfully.
2024-07-14 21:05:39 - To install Node.js, run: apt-get install nodejs -y
2024-07-14 21:05:39 - You can use N|solid Runtime as a node.js alternative
2024-07-14 21:05:39 - To install N|solid Runtime, run: apt-get install nsolid -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (22.4.1-1nodesource1).
The following packages were automatically installed and are no longer required:
  libcamera0.2 libraspberrypi0 libwpe-1.0-1 libwpebackend-fdo-1.0-1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

changed 138 packages in 30s

13 packages are looking for funding
  run `npm fund` for details
Chromium is already installed. Version: 125.0.6422.133
Chromedriver is already installed. Version: 125.0.6422.133

Installed Versions:
PM2 version: [PM2] Spawning PM2 daemon with pm2_home=/home/pi2/.pm2
[PM2] PM2 Successfully daemonized
5.4.2
Python version: Python 3.11.2
Node.js version: v22.4.1
npm version: 10.8.1
Chromium/Chrome version: 125.0.6422.133
Chromedriver version: 125.0.6422.133
Architecture: aarch64
Note: x86_64 users can run this script again to switch between Google Chrome/Chromium browsers.
pi2@raspberrypi:~/HotWalletBot $ ./launch.sh hot
Activating virtual environment...
Running script: ./games/hot.py with arguments:
Traceback (most recent call last):
  File "/home/pi2/HotWalletBot/./games/hot.py", line 14, in <module>
    from selenium import webdriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdriver/__init__.py", line 20, in <module>
    from .chrome.webdriver import WebDriver as Chrome  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 18, in <module>
    from selenium.webdriver.chromium.webdriver import ChromiumDriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 22, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver as RemoteWebDriver
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 67, in <module>
    from .websocket_connection import WebSocketConnection
  File "/home/pi2/HotWalletBot/venv/lib/python3.11/site-packages/selenium/webdriver/remote/websocket_connection.py", line 23, in <module>
    from websocket import WebSocketApp
ModuleNotFoundError: No module named 'websocket'
Deactivating virtual environment...
pi2@raspberrypi:~/HotWalletBot $


I can't install Docker on raspi!

thank you again for your time
