### ISSUE TITLE
error with tg-bot

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#121]
Some error when I install TG-bot. WHen I launch tg-bot  It's said
Running script: ./games/tg-bot.py with arguments:
Activating virtual environment...
Running script: ./games/tg-bot.py with arguments:
Traceback (most recent call last):
  File "/usr/src/app/./games/tg-bot.py", line 21, in <module>
    from utils.pm2 import start_pm2_app, save_pm2
ModuleNotFoundError: No module named 'utils.pm2'
Deactivating virtual environment...

Event I already Install module untils

**Comment by thebrumby** [comment]
Hi,

I'll make a short update to the tg-bot script so it works correctly with previous versions of Docker. 

Thanks

**Comment by thebrumby** [comment]
Hi,

I've pushed a fix now, although the whole system might need a little tuning in the coming days and weeks.

**Comment by bscongluanbui** [comment]
> Hi,
> 
> I've pushed a fix now, although the whole system might need a little tuning in the coming days and weeks.

thank you It's working
