### ISSUE TITLE
tg bot error after git pull 

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#122]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/6de19d13-3929-4bda-ab7c-a79ade37b2a0)

**Comment by thebrumby** [comment]
Hi,

We have been pushing some updates overnight, please confirm if you are still getting an error, and if so what kind of setup you have: docker / stand-alone Ubuntu etc

**Comment by laggedv1** [comment]
Ubuntu VPS 6cores 16ram 22.04  still gettin same error it insta resets a couple times using peak 50% cpu

**Comment by laggedv1** [comment]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/257da796-6fc9-41ed-bfad-b71a02c82772)
i assume this is me trying to send info to the bot?

**Comment by thebrumby** [comment]
Yes, telegram has a message limit for each bot, although you can have more than one bot. You might need to disable it for a while until it "cools down"

**Comment by laggedv1** [comment]
> Yes, telegram has a message limit for each bot, although you can have more than one bot. You might need to disable it for a while until it "cools down"

So if i have 9 + devices w every bot i need to re create it daily?

**Comment by laggedv1** [comment]
Gonna test using minimal claim steps, 2 seems to flood a bit

**Comment by laggedv1** [comment]
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/e3c679f7-6d49-4f69-8569-9a271cee0261)
deleted it, cant set it up again

**Comment by thebrumby** [comment]
> > Yes, telegram has a message limit for each bot, although you can have more than one bot. You might need to disable it for a while until it "cools down"
> 
> So if i have 9 + devices w every bot i need to re create it daily?

You don't need to recreate it daily, but it locks you out for sending too many, you might need to take a break until it allows you to start posting again.

**Comment by thebrumby** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/174215942/347472631-e3c679f7-6d49-4f69-8569-9a271cee0261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTQ1MzUsIm5iZiI6MTcyMDY1NDIzNSwicGF0aCI6Ii8xNzQyMTU5NDIvMzQ3NDcyNjMxLWUzYzY3OWY3LTZkNDktNGY2OS04NTY5LTlhMjcxY2VlMDI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQyMzMwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk0N2E0ZjNhNjkxMTY0ZGQ5MGI0YmNmOWQxNmJkNDNmZDgyMGM0ODI3OTBlYTVhYWM0ZDJkYmU2MThlMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SI5uG61da9WD8m4OidqCswUiJon95NMVlejuiSsRfm4) deleted it, cant set it up again

It looks like your on the updated code, I'd update from the repository and try again :)

**Comment by laggedv1** [comment]
> > ![imagen](https://private-user-images.githubusercontent.com/174215942/347472631-e3c679f7-6d49-4f69-8569-9a271cee0261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NTQ1MzUsIm5iZiI6MTcyMDY1NDIzNSwicGF0aCI6Ii8xNzQyMTU5NDIvMzQ3NDcyNjMxLWUzYzY3OWY3LTZkNDktNGY2OS04NTY5LTlhMjcxY2VlMDI2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQyMzMwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Nzk0N2E0ZjNhNjkxMTY0ZGQ5MGI0YmNmOWQxNmJkNDNmZDgyMGM0ODI3OTBlYTVhYWM0ZDJkYmU2MThlMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SI5uG61da9WD8m4OidqCswUiJon95NMVlejuiSsRfm4) deleted it, cant set it up again
> 
> It looks like your on an outdated version of the code, I'd update from the repository and try again :)

Hi , i updated still error after ./launch.sh tg-bot.py 
![imagen](https://github.com/thebrumby/HotWalletClaimer/assets/174215942/51eb8df2-d7ab-4bf4-9a7b-c195c1fcfc09)
