### ISSUE TITLE
Oxygen or oxygen auto?

### ISSUE THREAD

**Issue by Neo19867** [thebrumby/HotWalletClaimer#123]
Hello you have Oxygen and Oxygen-auto. So, i need to run both or just auto? Same question about Fuel.

**Comment by thebrumby** [comment]
Hi, 

It's one or the other. If you run the auto version, it will spend your tokens on the "mining speed" upgrades as soon as you have enough to upgrade. 

If you prefer to make your own decisions as to when and what to upgrade, just run the standard version.

Thanks.
