### ISSUE TITLE
About LumCity-Auto

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#125]
For me works 50/50 claims pot but doesnt upgrade, if i see logs from telegram rn says:
 Status: An error occurred: float() argument must be a string or a real number, not 'nonetype' 
Lets wait an hour and try again

Anyone else or im cursed?

**Comment by thebrumby** [comment]
Hi. 

I use the non auto-upgrade version myself, but looking at the error, the script can’t obtain the expected value from the game, it could cause this error. I’ll take a look today to improve the error handling. 

Thanks

**Comment by thebrumby** [comment]
Hi,

I pushed an update to the repository, please let me know if it resolves your issue :)

**Comment by laggedv1** [comment]
> Hi,
> 
> I pushed an update to the repository, please let me know if it resolves your issue :)

goat it seems to work smooth now, pocketfi also seems fixed will update if i find any error
