### ISSUE TITLE
Problem on the installation and Proxy

### ISSUE THREAD

**Issue by smolpepe59** [thebrumby/HotWalletClaimer#126]
![image](https://github.com/user-attachments/assets/7c7cdb0c-095b-47c3-b843-3127c68793ee)
![image](https://github.com/user-attachments/assets/69712867-6d89-4592-bfd7-724824ac1121)

I availed a VPS server and its architecture is x86_64 and when running the blum I'm getting that error. I hope you can help me :>

**Comment by smolpepe59** [comment]
![image](https://github.com/user-attachments/assets/8ee80c61-71d2-4dfa-bd52-8afeec806287)
my server work well with proxy off, maybe compatibility with the OS, im running ubuntu 20 on my contabo vps

**Comment by thebrumby** [comment]
Hi, 

It looks like you are missing the python package '`Wheel`' . While the main scripts were tested on 20.04 to 24.04, I didn't retro test all the newly added features on the older versions. I've added the commands to install Wheel if missing to the script, or you can install it manually from inside the `HotWalletBot` directory.

```
source venv/bin/activate
pip install wheel
deactivate
```

Please let me know if this works.
