### ISSUE TITLE
Error with Hot claimer

### ISSUE THREAD

**Issue by eychouesti** [thebrumby/HotWalletClaimer#127]
/root/.pm2/logs/HOT-Wallet1-out.log last 15 lines:
1|HOT:Wall | No user agent found, using default.
1|HOT:Wall |
1|HOT:Wall | CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
1|HOT:Wall | Step 101 - Attempting to check for the start button (should not be present)... [//button[contains(., 'START')]]
1|HOT:Wall | Step 102 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app']...
1|HOT:Wall | Step 103 - Attempting to click the 'Launch' button (probably not present)... [//button[contains(@class, 'popup-button') and contains(., 'Launch')]]
1|HOT:Wall | Step 104 - Attempting to switch to the app's iFrame...
1|HOT:Wall | Step 105 - Attempting to click the 'storage' link... [//h4[text()='Storage']]
1|HOT:Wall | Step 107 - Attempting to get the pre-claim wait timer... [//div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')]]
1|HOT:Wall | Step 107 - Attempting to click the 'storage' link... [//h4[text()='Storage']]
1|HOT:Wall | Step 107 - Attempting to get the pre-claim wait timer... [//div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')]]
1|HOT:Wall | Step 107 - Attempting to click the 'storage' link... [//h4[text()='Storage']]
1|HOT:Wall |
1|HOT:Wall | CHROME DRIVER DETACHED: It is now safe to exit the script.
1|HOT:Wall | 14 July - 23:44 | Need to wait until 14 July - 23:59 before the next claim attempt. Approximately 15 minutes.

**Comment by thebrumby** [comment]
Hi, 

You need to enable verbose level 3 to see if there's any error messages or enable debugging and look at the screenshots. The above information doesn't show what the issue is. 

Thanks.
