### ISSUE TITLE
Gamee add cloudflare checkl

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#130]
Gamee added cloudflare check & bots aint doing tasks anymore atleast for me
Pocketfi not working for me
Blum also off

**Comment by laggedv1** [comment]
cant see any error on blum logs it just doesnt clam, same for pocketfi, gamee cause of cloudflare i think

**Comment by thebrumby** [comment]
> Gamee added cloudflare check & bots aint doing tasks anymore atleast for me Pocketfi not working for me Blum also off

Yes, Cloudflare will stop new account log-ins. For those lucky enough to have signed in before the Cloudflare check, the script will keep on claiming. We have seen a number of games add Cloudflare, and then later remove it (probably when they fall into the $200/month tier!).

Blum will be something to do with the proxy not working correctly, I suspect. It makes certain changes to the header structure to allow the connection to Blum. Unfortunately, it's working fine for me, so I can't recreate the issue.

Do you have yesterday's update to the PocketFi script? They changed some elements of the layout, and we updated the script yesterday to fix it.

Thanks.

**Comment by laggedv1** [comment]
> > Gamee added cloudflare check & bots aint doing tasks anymore atleast for me Pocketfi not working for me Blum also off
> 
> Yes, Cloudflare will stop new account log-ins. For those lucky enough to have signed in before the Cloudflare check, the script will keep on claiming. We have seen a number of games add Cloudflare, and then later remove it (probably when they fall into the $200/month tier!).
> 
> Blum will be something to do with the proxy not working correctly, I suspect. It makes certain changes to the header structure to allow the connection to Blum. Unfortunately, it's working fine for me, so I can't recreate the issue.
> 
> Do you have yesterday's update to the PocketFi script? They changed some elements of the layout, and we updated the script yesterday to fix it.
> 
> Thanks.

morning, imo cloudflare shouldnt be hard to bypass?
 you right about gamee couldnt add new accounts is just that old accs stop working too other bot im using doesnt get flagged.
 about pocketfi tried with update yesterday was forced to swap to another bot cos it doesnt claim, just let the coins burn,
 blum for me couldnt claim same as pocketfi you get 0 errors yet nothing is working

Thanks for pushing updates btw <3

**Comment by thebrumby** [comment]
If you work out how to overcome Cloudflare, please contribute the solution here too :)

**Comment by laggedv1** [comment]
> If you work out how to overcome Cloudflare, please contribute the solution here too :)

Why would i , already have other bot working

**Comment by thebrumby** [comment]
You said it wasn't hard to bypass, I though you might have an idea how to do it.

**Comment by laggedv1** [comment]
> You said it wasn't hard to bypass, I though you might have an idea how to do it.

Cos it isnt, you can include zenrows & multiple free python cloudflare bypass

**Comment by Wellynounet** [comment]
of course it's not complicated, that's why we're waiting to hear from you about upgrading the script so that it works with cloudflare. 
thanks for your help

**Comment by Wellynounet** [comment]
It's you who says it's easy, either you do it or you wait for it to be done or not, but don't come and tell me to do something I can't even do! 
so if you can't even do something simple, do something you can do like shutting up

**Comment by laggedv1** [comment]
> It's you who says it's easy, either you do it or you wait for it to be done or not, but don't come and tell me to do something you can't even do! so if you can't even do something simple, do something you can do like shutting up

1. Already have bots runin so why invest my time
2. You seem pissed off maybe touch some grass bozo 
3. If you cant bypass cloudflare in 2024 quit doing bots & get back to pokemon

**Comment by laggedv1** [comment]
> It's you who says it's easy, either you do it or you wait for it to be done or not, but don't come and tell me to do something you can't even do! so if you can't even do something simple, do something you can do like shutting up

Btw all this dick ride just bcs i said IMO cloudflare isnt hard to bypass (spoiler it isnt) i said IMO anyway you fucking nerd

**Comment by Wellynounet** [comment]
> "Already have bots running, so why invest my time? Why? "

Because it's for the community. If you don't want to share something with the community, don't waste our time.

> "You seem pissed off, maybe touch some grass, bozo."


Yeah, I am pissed off at someone who does nothing but ask for something and doesn't "waste time" .

> "If you can't bypass Cloudflare in 2024, quit doing bots and get back to Pokémon."

And you can't do either, so stop blaming people because you don't want to waste your time. I don't want to waste my time talking to kids who think they are gods. You are just muppets.
see ya
