### ISSUE TITLE
problems with poketfi and pixeltap & some questions

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#131]
Hi! First of all I would like to thank you for such a great product. very well and thoughtfully implemented, especially with the docker. You must be a very good engineer. At the moment there are problems with two bots. 
1. Pixeltap - the bot collects daily klaim and gives an error. it does not collect coins for some reason when the vault is full. 
2. Pocketfi - there changed the application interface and the bot stopped collecting, also gives an error.
I would also like to ask 2 questions: 
1. Is it possible to make a backup with all settings, accounts and sessions via Docker and if so, how can I deploy it on another device?
2. Is it possible to add a bot to the wallet https://t.me/spell_wallet ? They are besides hot now the only promising wallet that will give something to earn. Also there do not need now funds for gas, claimes are absolutely free well and the interface is as simple as possible.
Once again I want to thank you for this incredibly convenient, practical and resource-intensive bot.

**Comment by thebrumby** [comment]
Hi, I'm pleased you are finding the script(s) useful!

> 1. Pixeltap - the bot collects daily klaim and gives an error. it does not collect coins for some reason when the vault is full.

I will look into this for you later today, or in the next few days.

> 2. Pocketfi - there changed the application interface and the bot stopped collecting, also gives an error.

We updated the PocketFi code yesterday. By default, Docker automatically updates and restarts any game sessions that has updated code. You could manually run `./pull-games.sh` to ensure you are on the latest versions and then restart it in PM2. Sometimes game sessions/telegram accounts can also get corrupted, so you could also use `./launch.sh status` to delete the current session and start afresh.

> 3. Is it possible to make a backup with all settings, accounts, and sessions via Docker and if so, how can I deploy it on another device?

Yes, docker has a copy function. For example, these commands would let you pull the game session files out of the container into your native file system:

```
docker cp telegram-claim-bot:/usr/src/app/screenshots/ screenshots/
docker cp telegram-claim-bot:/usr/src/app/selenium/ selenium/
docker cp telegram-claim-bot:/usr/src/app/backups/ backups/
```

You could then put them into a different environment or keep them as a backup. 

> 4. Is it possible to add a bot to the wallet https://t.me/spell_wallet ?

At the minute it's a no. We have one game to add later today, and that will be my time available for this project elaspsed for another week. However, we may add it at a later date.

Thanks again for your interest in the project.

**Comment by farmdigit** [comment]
> Hi,
> 
> Can you confirm if Pixel Tap is working OK in your mobile phone GUI? Looks like the game has some lag or something, as for me, it's just stuck permanently waiting to load.

Yes, specifically right now they're having an update there, it'll be finished in about 4-10 hours.

**Comment by farmdigit** [comment]
"Yes, docker has a copy function. For example, these commands would let you pull the game session files out of the container into your native file system:" 
I didn't understand how to make a backup and then deploy it to another device? Or is it possible to deploy current settings and accounts on another device without backup?

**Comment by thebrumby** [comment]
> "Yes, docker has a copy function. For example, these commands would let you pull the game session files out of the container into your native file system:" I didn't understand how to make a backup and then deploy it to another device? Or is it possible to deploy current settings and accounts on another device without backup?

It's not possible without taking a backup

**Comment by farmdigit** [comment]
> > 1. Pixeltap - the bot collects daily klaim and gives an error. it does not collect coins for some reason when the vault is full.
> 
> Hi,
> 
> Can you confirm if Pixel Tap is working OK in your mobile phone GUI? Looks like the game has some lag or something, as for me, it's just stuck permanently waiting to load.

Hi! Looks like the pixel are working and have a slightly updated interface.

**Comment by farmdigit** [comment]
> > 1. Pixeltap - the bot collects daily klaim and gives an error. it does not collect coins for some reason when the vault is full.
> 
> Hi,
> 
> Can you confirm if Pixel Tap is working OK in your mobile phone GUI? Looks like the game has some lag or something, as for me, it's just stuck permanently waiting to load.

seems like the problem is not relevant at the moment - they had a listing today and finished the first phase of the game.

Can we hope to add [spell wallet](https://t.me/spell_wallet) in august?

Thanks for your hard work.

**Comment by thebrumby** [comment]
Hi,

We have a few side projects we wish to tackle first:

1. **Update or add to the YouTube videos.**
2. **Rework the auto-claim versions of the scripts**, which need some improvements to get them working again.
3. **Add support for external proxies**, including those with usernames and passwords.

However, I think Spell Wallet would be a good addition. I've already looked at some of the mappings for it, so we'll see what can be done to add it :)

**Comment by farmdigit** [comment]
> 2\. **Rework the auto-claim versions of the scripts**, which need some improvements to get them working again.

blum bot is not working at the moment, maybe it's because they changed the interface a bit


> 3\. **Add support for external proxies**, including those with usernames and passwords.

It's going to be a very cool innovation.



> However, I think Spell Wallet would be a good addition. I've already looked at some of the mappings for it, so we'll see what can be done to add it :)

I can send links to the source code of projects where they have already made a bot for this wallet. Perhaps it will simplify the work.
