### ISSUE TITLE
update timefarm

### ISSUE THREAD

**Issue by mentalityStyle** [thebrumby/HotWalletClaimer#133]
Thanks for this big project
I have a question.. 
Can timefarm bot solve the new quizzes (new update in timefarm bot)?

**Comment by thebrumby** [comment]
Hi,

Thanks for the suggestion. The bot performs best with repetitive and predictable sequences of mouse movements and clicks. It can read and respond to written information in the game, such as comparing the cost of making an upgrade to the player's available balance. However, for this specific task, it's probably not ideally suited.

Today's question was:

> When did LaborX, the blockchain-based freelancer platform, officially launch?

I had to find the answer via an internet search, which returned the date in the US format (11/15/2018). Then, I needed to convert it to the UK format (15/11/2018) to enter it into the Timefarm bot.

While it might be possible to get the bot to perform internet searches, interpret the results, and enter the date, the limited benefit doesn't justify the effort required to implement this functionality. So, for now, we'll leave answering the question to the user. 😊
