### ISSUE TITLE
Fuel blank iFrame window

### ISSUE THREAD

**Issue by Imaroubat** [thebrumby/HotWalletClaimer#135]
![105_look for oil balance_error](https://github.com/user-attachments/assets/68472e6d-6576-4cd0-943d-f18ebfc19398)

Step 105 - Found 0 elements with XPath: //span[@class='fuel-balance'] for
Step 105 - Attempting to look for oil balance... [//span[@class='fuel-balance']/preceding-sibling::span[1]]
Step 105 - Timeout while trying to look for oil balance.
Screenshot saved to ./screenshots/Fuel:T-Mobile/105_look for oil balance_error.png
Step 105 - Found 0 elements with XPath: //span[@class='fuel-balance']/preceding-sibling::span[1] for
Step 105 - Before BALANCE: Unknown fuel & Unknown oil.
Step 105 - check if the timer is elapsing...
Step 105 - Found 0 elements with XPath: //div[@class='in-storage-footer'] for

**Comment by Neo19867** [comment]
I have the same. Where i can find screenshots if i will make DEBUG ON?

**Comment by Wellynounet** [comment]
cloudflare

**Comment by Imaroubat** [comment]
> cloudflare
how to pass ? fix problem?

**Comment by Imaroubat** [comment]
> I have the same. Where i can find screenshots if i will make DEBUG ON?

docker cp telegram-claim-bot:/usr/src/app/screenshots .

**Comment by Wellynounet** [comment]
you cant wait they didint  pay cloudflare

**Comment by thebrumby** [comment]
As Welly says, once Cloudflare detects that the set up is probably being manipulated by a bot, it doesn’t offer the click here if you are human prompt. 

There are other GitHub solutions to get passed this, but none seem to be working on the current version of Cloudflare. 

Every games who turned Cloudflare on, seems to turn it back off, often permanently. Again, as Welly said, probably when the cost of Cloudflare gets too much for them. If you log in when Cloudflare is off, you can continue to use the script, even when it’s turned back on.
