### ISSUE TITLE
Telegram session

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#136]
Hi if I have a telegram session crash. How do I re login that session. I dont want to lose data that I save on that session

**Comment by thebrumby** [comment]
Hi,

It depends what you mean by the Telegram session crashed. 

if a Telegram session got corrupted, you can go to create a new game session, when it asks if you want to use an existing Telegram account  select ‘n’. Log into Telegram again, press “y” to save the account, and save it again. 

If you went into the devices tab on the mobile app and terminated the session, you’d have to double check if the games are still logged in or not - probably not. In this case, delete the not working ines and create again once you logged into Telegram. 

If you no longer have access to the Telegram accounts, you will only be able to access games that have seed phases. 

Thanks

**Comment by bscongluanbui** [comment]
Hi because my hot claimer said that:
Step 101 - Attempting to check for the start button (should not be present)... [//button[contains(., 'START')]]
 Initialising the HOT: Wallet Auto-claim Python Script - Good Luck!
Session ID provided: HOT:c6e51
Proxy disabled in settings.
Resuming the previous session...

CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
 Step 100 - Chrome driver reports the QR code is visible: It appears we are no longer logged in.
 Step 100 - Most likely you will get a warning that the central input box is not found.
Step 100 - System will try to restore session, or restart the script from CLI to force a fresh log in.
Step 101 - Attempting to check for the start button (should not be present)... [//button[contains(., 'START')]]
Step 102 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app']...
Step 102 - Failed to find the 'Open Wallet' button within the expected timeframe.
Step 102 - Attempting to find the chat window/message input box... [//div[contains(@class, 'input-message-container')]/div[contains(@class, 'input-message-input')][1]]
Step 102 - Failed to find the message input box.
Step 102 - Attempting to restore from backup and retry.
CHROME DRIVER DETACHED: It is now safe to exit the script.

Does it relate to corrupt the sesion?
I try remove and add session again but 1-2 days, I got this error again.

**Comment by thebrumby** [comment]
Hi,

It looks like the Telegram session used to authenticate this session has become invalidated. To resolve this, you will need to remove the game session:

```
./launch.sh status
delete HOT:c6e51
```

Once this is done, recreate the account using any working Telegram session you have and enter the seed phrase when prompted. With the HOT game, it is not required to use the same Telegram account that the seed phrase was registered with. You can use any valid Telegram session or process a new Telegram login.
