### ISSUE TITLE
Stop multiple ID on status command

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#137]
HI a useful feature to stop multiple ID will be good. Sometime I have crash multiple game and I want to stop them. If I use pm2 stop, it's once per time. Thank you

**Comment by thebrumby** [comment]
Hi,

For now, start, stop and restart is all handled by PM2. You can you pattern matching by name to stop / start / restart / reset processes. Here are some examples:

**Restart all HOT game sessions**
```
pm2 restart /HOT:/
```

**Stop all instances of Oxyen**
```
pm2 stop /Oxy/
```

**Comment by bscongluanbui** [comment]
> Hi,
> 
> For now; the starting, stopping, and restarting of game sessions are handled by PM2. You can use pattern matching by name to affect multiple game sessions. When the pattern you type between the two forward slashes (`/`) matches one or more game sessions, the command will be applied to all matches. Here are some examples:
> 
> **Restart all HOT game sessions**
> 
> ```
> pm2 restart /HOT:/
> ```
> 
> **Stop all instances of Oxygen Auto-upgrade**
> 
> ```
> pm2 stop /Oxygen-autoupgrade/
> ```

Hi thanks for advices. I noticed that the session usually corrupted recently. Did it was effected by recently update? Can you check that

**Comment by thebrumby** [comment]
Hi, can you clarify which game(s) and what update you are referring to please?

**Comment by bscongluanbui** [comment]
> Hi, can you clarify which game(s) and what update you are referring to please?

I’m issue with hot, seed. The latest update script. When I run a bout a few day, I got that. It seem the game cannot open session data

**Comment by thebrumby** [comment]
Hi,

My processes have been running fine for the last 5 days, since I restarted them. I don't think it's an issue with the script.
