### ISSUE TITLE
telegram session RU

### ISSUE THREAD

**Issue by esckobar** [thebrumby/HotWalletClaimer#139]
Greetings dear creators.

My problem is that when I start a new session via ./launsh hot I add a telegram account via QR. Everything is fine here, but when it comes to `Step 09 - Attempting to find the HereWallet log-in button... [//button[p[contains(text(), 'Log in')]]]
Step 09 - Timeout while trying to find the HereWallet log-in button.
Screenshot saved to ./screenshots/HOT:Wallet2/09_find the HereWallet log-in button_error.png
Step 09 - An error occurred: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome-headless-shell=126.0.6478.182)
` 
I looked at the screenshots and it shows that authorization in herewaletbot takes place in English.
I already have a VPN connection and even created a telegram account using a US number.
What to do, help today. Since I decided to update the bot and reinstall everything, now none of them work at all.
![09_find the HereWallet log-in button_error](https://github.com/user-attachments/assets/e468f2cc-a42a-4dfe-84ff-3e631b29d607)
![09_find the HereWallet log-in button_error](https://github.com/user-attachments/assets/4b325233-fa88-4bc9-9f50-6e90b4d22886)

**Comment by AerolisGit** [comment]
Привет, ты подключал прокси с авторизацией? Если да, можешь подсказать как это сделал? У меня не запрашивает логина и пароля при вводе прокси
