### ISSUE TITLE
HOT error, BALANCE: Unknow

### ISSUE THREAD

**Issue by howtoprogram** [thebrumby/HotWalletClaimer#144]
Hello,

I observed few errors happened recently when add new HOT game.
` Step 101 - Timeout while trying to check for the start button (should not be present).
Step 102 - Attempting to open a link for the app: 
Step 102 - Successfully able to open a link for the app..
 Step 103 - Attempting to click the 'Launch' button (probably not present)...
...
Step 105 - Attempting to click the 'storage' link... 
Step 106 - Found 0 elements with XPath: //p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p for
Step 106 - Before BALANCE: Unknown
....
Step 108 - Timeout while trying to get the pre-claim wait timer.
Step 108 - Attempt 1: Wait time element not found. Clicking the 'Storage' link and retrying...
...
Step 108 - Timeout while trying to click the 'storage' link.
An error occurred on attempt 1: 'NoneType' object has no attribute 'text'
`
It seems like HOT game has had few updates recently on the new UI. Kindly look into it. Thanks

**Comment by howtoprogram** [comment]
A note is that it is often happening for new accounts

**Comment by thebrumby** [comment]
Hi,

HOT has been having intermittent issues with its login system. It's currently back up, but this is the error from earlier in the evening:

![image](https://github.com/user-attachments/assets/d1235436-99cb-456f-8132-e5ac416c2620)

Thanks
