### ISSUE TITLE
Seed errors

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#145]
Hi. Sinces yesterday seed app errors. I think relate about play and open app button inside the app (like oxygen before)

**Comment by thebrumby** [comment]
Hi,

For me, the link to open the app says "Open app", please can you confirm what it's showing for you?

Thanks

**Comment by bscongluanbui** [comment]
> Hi,
> 
> For me, the link to open the app says "Open app", please can you confirm what it's showing for you?
> 
> Thanks

I think it’s new. Input start and it show “play”
![Uploading IMG_0814.jpeg…]()

**Comment by thebrumby** [comment]
Hi,

Please can you attach the image so I can see?

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Please can you attach the image so I can see?

![image](https://github.com/user-attachments/assets/4f52afcd-30d4-4b9f-ab30-c66c20ca13aa)
it's show that

**Comment by thebrumby** [comment]
Thanks, I couldn't see the first image.

I added the dual switch now :)
