### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by bedjoey** [thebrumby/HotWalletClaimer#15]
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 01 - Backup restored successfully.
Step 01 - Attempting to verify if we are logged in (hopefully QR code is not present).
Step 01 - nothing found to action. The QR code test passed.

Step 02 - Attempting to check for the start button (should not be present)...
Step 02 - Timeout while trying to check for the start button (should not be present).
Step 03 - Attempting to open a link for the app...
Step 03 - Failed to find the 'Open Wallet' button within the expected timeframe.

Step 03 - Attempting to find the chat window/message input box...
Step 03 - Timeout while trying to find the chat window/message input box.
Step 03 - Failed to find the message input box.

Step 03 - Attempting to restore from backup and retry.

CHROME DRIVER DETACHED: It is now safe to exit the script.
Session released: ./selenium/Wave:Wallet2
Session started: ./selenium/Wave:Wallet2 in status.txt

CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.

**Comment by bedjoey** [comment]
I haven't connected my Telegram account to the bot

**Comment by thebrumby** [comment]
Hey Joey,

There was an error connecting the script to Telegram accounts for around 2 days after Telegram changed their layout. I have corrected the issue, so you should be able to pull the latest version from GitHub and log into Telegram.

Thanks
