### ISSUE TITLE
Hexacore and blum doesn't work

### ISSUE THREAD

**Issue by HoN3YP0T** [thebrumby/HotWalletClaimer#151]
hexacore and blum having problem in detecting clicks remaining and start farming  button

**Comment by thebrumby** [comment]
Hi,

It looks like both games have updated their user interfaces, I'll release a patch in the coming days.

**Comment by thebrumby** [comment]
Hi,

Blum should be working again now. We will look again at Hexacore in August.

Thanks

**Comment by thebrumby** [comment]
Hi,

As the GUI version of Hexcore in the Telegram browser still isn't working, I'll close this issues until the game developers resolve their issues.

Thanks
