### ISSUE TITLE
как обновить полностю thebrumby / HotWalletClaimer

### ISSUE THREAD

**Issue by oboroccv** [thebrumby/HotWalletClaimer#152]
как обновить полностю thebrumby / HotWalletClaimer

**Comment by thebrumby** [comment]
```
git pull
pm2 restart all
```

**Comment by oboroccv** [comment]
> ```shell
> git pull
> ```

![1](https://github.com/user-attachments/assets/f01b4b33-ac9b-4e23-a829-6363ea8cc985)

**Comment by Wellynounet** [comment]
for update on docker  use 
"./pull-games.sh "
![image](https://github.com/user-attachments/assets/ef4fe0c6-daad-49fa-90ee-af88eb78cce2)
