### ISSUE TITLE
Can you add a script for the SPELL WALLET bot?

### ISSUE THREAD

**Issue by KarinaBash** [thebrumby/HotWalletClaimer#153]

**Comment by thebrumby** [comment]
Hi,

There will be no further games added until at least August, but we already made a start on Spell. 

Thanks.

**Comment by thebrumby** [comment]
We've add the first iteration of Spell wallet today, it's working fine for claiming Mana. Thanks.

**Comment by KarinaBash** [comment]
Thank You sir, you the best
