### ISSUE TITLE
Ошибки 

### ISSUE THREAD

**Issue by oboroccv** [thebrumby/HotWalletClaimer#154]
![22](https://github.com/user-attachments/assets/3109bd2b-f885-4b74-8347-d629a6fb0cce)
![23](https://github.com/user-attachments/assets/cb73d56d-3eef-4b9e-a63b-90af78c3ac8f)

с дерево он не собирает
![24](https://github.com/user-attachments/assets/b53c60da-d20c-4006-97b9-17a1a5f381e5)

**Comment by thebrumby** [comment]
> ![22](https://private-user-images.githubusercontent.com/22344723/352401261-3109bd2b-f885-4b74-8347-d629a6fb0cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkwMDAsIm5iZiI6MTcyMTk3ODcwMCwicGF0aCI6Ii8yMjM0NDcyMy8zNTI0MDEyNjEtMzEwOWJkMmItZjg4NS00Yjc0LTgzNDctZDYyOWE2ZmIwY2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMTM5ZGU0ODFmNDM0NDM0OTg4MDdkY2Y5YjQ5YjNhNzIzMDIyNmMwNzI2MTY3NWMzZTYwNWY1YTkxYTQyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAj1eD5TDy84bDXpYyO_acwMfkqHpnBP1EMfDuueNNU) ![23](https://private-user-images.githubusercontent.com/22344723/352401318-cb73d56d-3eef-4b9e-a63b-90af78c3ac8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkwMDAsIm5iZiI6MTcyMTk3ODcwMCwicGF0aCI6Ii8yMjM0NDcyMy8zNTI0MDEzMTgtY2I3M2Q1NmQtM2VlZi00YjllLWE2M2ItOTBhZjc4YzNhYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjkzZWRhNTIzMjc2NGVhZjkxNDk5NDk3M2UwNWVkZmFjNjZmOTE4YzQzOTY2ZjIyNjBmMDlhZmE4ZGQ1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYECBwb127t9CCfSkRg3qjt0O3qfkft7jSRIaRSjQQY)
> 
This shows you are restarting the process with PM2

**Comment by thebrumby** [comment]
> с дерево он не собирает ![24](https://private-user-images.githubusercontent.com/22344723/352402065-b53c60da-d20c-4006-97b9-17a1a5f381e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkwODgsIm5iZiI6MTcyMTk3ODc4OCwicGF0aCI6Ii8yMjM0NDcyMy8zNTI0MDIwNjUtYjUzYzYwZGEtZDIwYy00MDA2LTk3YjktMTdhMWE1ZjM4MWU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4OTlkMWQ2M2I3NWMzNmZiNDNhNjBiYjM2MDQ0YzNjMDhiMDNiODJiZWJjMzE2MTdjY2JkZTgyZDhkMDdiYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hlAqkVIyssFJOsTt3PtAGMzdrMrNVw1hq-kHEfyZmJo)

Да, эта функция не работает. У меня очень мало свободного времени в июле. Я планирую внести исправления в августе.

**Comment by oboroccv** [comment]
> > ![22](https://private-user-images.githubusercontent.com/22344723/352401261-3109bd2b-f885-4b74-8347-d629a6fb0cce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkwMDAsIm5iZiI6MTcyMTk3ODcwMCwicGF0aCI6Ii8yMjM0NDcyMy8zNTI0MDEyNjEtMzEwOWJkMmItZjg4NS00Yjc0LTgzNDctZDYyOWE2ZmIwY2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMTM5ZGU0ODFmNDM0NDM0OTg4MDdkY2Y5YjQ5YjNhNzIzMDIyNmMwNzI2MTY3NWMzZTYwNWY1YTkxYTQyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAj1eD5TDy84bDXpYyO_acwMfkqHpnBP1EMfDuueNNU) ![23](https://private-user-images.githubusercontent.com/22344723/352401318-cb73d56d-3eef-4b9e-a63b-90af78c3ac8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzkwMDAsIm5iZiI6MTcyMTk3ODcwMCwicGF0aCI6Ii8yMjM0NDcyMy8zNTI0MDEzMTgtY2I3M2Q1NmQtM2VlZi00YjllLWE2M2ItOTBhZjc4YzNhYzhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA3MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0MjkzZWRhNTIzMjc2NGVhZjkxNDk5NDk3M2UwNWVkZmFjNjZmOTE4YzQzOTY2ZjIyNjBmMDlhZmE4ZGQ1OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HYECBwb127t9CCfSkRg3qjt0O3qfkft7jSRIaRSjQQY)
> 
> Это показывает, что вы перезапускаете процесс с PM2.

и как это исправить?

**Comment by thebrumby** [comment]
Для PM2 естественно перезапускаться, особенно в Docker. Вот некоторые из многих причин:

	1.	Вы перезапустили контейнер Docker или компьютер.
	2.	Он обнаружил обновление в коде и перезапустился с последней версией.
	3.	Вы использовали PM2 для остановки или перезапуска скрипта.

Если подумать иначе, прерывание с клавиатуры похоже на нажатие клавиши Escape или сочетания Ctrl + C для выхода из текущего скрипта, а затем, возможно, он может перезапуститься снова.
