### ISSUE TITLE
Change in Vertus

### ISSUE THREAD

**Issue by rostamzad1905** [thebrumby/HotWalletClaimer#155]
hey phil
i'm not good at using git and etc
but i know there is been a change in the vertus game when you want to start game
in vertus.py func "find_working_link"
you must change xpath to this:
`start_app_xpath = "//div[@class='reply-markup-row']//span[contains(text(),'Open app') or contains(text(), 'Play')]"
`

**Comment by thebrumby** [comment]
Thanks, 

We experienced some similar things before were the opening link shows slightly different with certain games, I pushed the update now.

**Comment by rostamzad1905** [comment]
Tnx
i,m getting error constantly
`STATUS: An error occurred while trying to claim: apply_random_offset() missing 3 required positional arguments: 'settings', 'step', and 'output'`

i think change in **apply_random_offset** can solve this problem

```
def apply_random_offset(unmodifiedTimer):
    global settings, step
    if settings['lowestClaimOffset'] <= settings['highestClaimOffset']:
        random_offset = random.randint(settings['lowestClaimOffset'], settings['highestClaimOffset'])
        modifiedTimer = unmodifiedTimer + random_offset
        output(f"Step {step} - Random offset applied to the wait timer of: {random_offset} minutes.", 2)
        return modifiedTimer
    return unmodifiedTimer
```

**Comment by rostamzad1905** [comment]
Tnx
i,m getting error constantly
STATUS: An error occurred while trying to claim: apply_random_offset() missing 3 required positional arguments: 'settings', 'step', and 'output'

i think change in apply_random_offset can solve this problem

def apply_random_offset(unmodifiedTimer):
    global settings, step
    if settings['lowestClaimOffset'] <= settings['highestClaimOffset']:
        random_offset = random.randint(settings['lowestClaimOffset'], settings['highestClaimOffset'])
        modifiedTimer = unmodifiedTimer + random_offset
        output(f"Step {step} - Random offset applied to the wait timer of: {random_offset} minutes.", 2)
        return modifiedTimer
    return unmodifiedTimer

**Comment by rostamzad1905** [comment]
Tnx
i,m getting error constantly
`STATUS: An error occurred while trying to claim: apply_random_offset() missing 3 required positional arguments: 'settings', 'step', and 'output'`

i think change in **apply_random_offset** can solve this problem

```
def apply_random_offset(unmodifiedTimer):
    global settings, step
    if settings['lowestClaimOffset'] <= settings['highestClaimOffset']:
        random_offset = random.randint(settings['lowestClaimOffset'], settings['highestClaimOffset'])
        modifiedTimer = unmodifiedTimer + random_offset
        output(f"Step {step} - Random offset applied to the wait timer of: {random_offset} minutes.", 2)
        return modifiedTimer
    return unmodifiedTimer
```

**Comment by thebrumby** [comment]
Hi, 

I've pushed some updates for Vertus to make it share more common code with the other apps. Please let me know if this fixes your issue :)

**Comment by bscongluanbui** [comment]
Hi maybe vertus not working today. Can you check it?

**Comment by thebrumby** [comment]
HI,

```
59|Vertus: | Step 110 - Attempting to move to the missions link... [//p[contains(text(), 'Missions')]]
59|Vertus: | Step 111 - Attempting to move to the daily missions link... [//p[contains(text(), 'Daily')]]
59|Vertus: | Step 112 - Attempting to move to the claim daily missions link... [//p[contains(text(), 'Claim')]]
59|Vertus: | Step 112 - Attempting to check if the bonus is for tomorrow... [//p[contains(text(), 'Come back tomorrow')]]
59|Vertus: | STATUS: Island bonus claimed. . Successful Claim & The daily bonus will be available tomorrow.: Next claim in 60 minutes.
```

It's working for me, kindly follow the [troubleshooting steps](https://github.com/thebrumby/HotWalletClaimer/issues/166) and share your issue/findings.
