### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ankitraz154** [thebrumby/HotWalletClaimer#157]
![Screenshot_2024_0729_111716](https://github.com/user-attachments/assets/b4d2cc7b-0a59-402d-be3b-8de0630b2184)

**Comment by thebrumby** [comment]
Hi,

The message is saying to ensure you have the correct browser and Chromedriver version installed. If you have difficulty trouble shooting, consider using docker which has all the dependencies pre-built. 

```
chromedriver --version
google-chrome --version
chromium-browser --version
```

Thanks
