### ISSUE TITLE
The script requires a lot of space

### ISSUE THREAD

**Issue by fly-a1one** [thebrumby/HotWalletClaimer#158]
I ran into the problem that over time the script starts to take up a lot of space, especially if several bots are running at once. I tried to figure out what exactly is taking up space and that's the selenium folder. I think it's related to the application cache or cookies, but I don't know for sure.
In almost a week, the size of this folder grows by 2 GB. And in the end it takes up the entire disk of my server (10 GB) and my server stops responding, namely it is impossible to log in via SSH. And every time I have to reinstall the system and download all the scripts again. This has already happened several times and I'm tired of reinstalling the system every time. 
Can you tell me how it is possible to delete this cache or the problem is with my server.

P.S. I have attached a screenshot below. Starting on July 24th, I installed all the scripts and ran them. And then you can see how the disk space is gradually filling up.

![image](https://github.com/user-attachments/assets/d84fe21c-9782-440d-9425-fc1e3ea3cd8d)
![image](https://github.com/user-attachments/assets/43340d74-96f7-427d-bc53-ab9a30a448a7)
![image](https://github.com/user-attachments/assets/944678c2-9f88-409b-9311-64bc4ae9653a)

**Comment by fly-a1one** [comment]
I understand that the simplest solution is to just use a server with a lot of disk space, but at the moment I don't have that option. And in general, I think it's abnormal that the script allocates so much cache. Perhaps there is a solution to reduce it or periodically delete it.

P.S. Somehow I logged into the server and after a couple of minutes of waiting I was able to calculate the size of the folders. I have attached screenshots below. Basically, you can compare the size of my folders and folders if you install the script for the first time

![image](https://github.com/user-attachments/assets/0852cefb-adff-49e9-a24b-cda5050fa542)

**Comment by fly-a1one** [comment]
After deleting some folders, the folder with the script weighs a little again

![image](https://github.com/user-attachments/assets/cfb6108c-901f-443d-9dbc-2780c6545b51)

**Comment by rostamzad1900** [comment]
hey phil
i'm experience same issue in my server. every time commit changes to docker image its got bigger and bigger.

![image_2024-07-29_15-40-53](https://github.com/user-attachments/assets/ac55635c-bf45-4060-b806-98fce44a4980)

**Comment by rostamzad1900** [comment]
hey phil
i'm experience same issue in my server. every time commit changes to docker image its got bigger and bigger.

execute last line make a image bigger than 14.7G, after push it to gitlab registry, it reduced to around 8G because of compression.

![image_2024-07-29_15-40-53](https://github.com/user-attachments/assets/cfd1e36c-361e-42df-9422-d0d8e3a19648)

**Comment by thebrumby** [comment]
> I understand that the simplest solution is to just use a server with a lot of disk space, but at the moment I don't have that option. And in general, I think it's abnormal that the script allocates so much cache. Perhaps there is a solution to reduce it or periodically delete it.
> 
> P.S. Somehow I logged into the server and after a couple of minutes of waiting I was able to calculate the size of the folders. I have attached screenshots below. Basically, you can compare the size of my folders and folders if you install the script for the first time
> 
> ![image](https://private-user-images.githubusercontent.com/70477273/353020926-0852cefb-adff-49e9-a24b-cda5050fa542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzYwMjcsIm5iZiI6MTcyMjI3NTcyNywicGF0aCI6Ii83MDQ3NzI3My8zNTMwMjA5MjYtMDg1MmNlZmItYWRmZi00OWU5LWEyNGItY2RhNTA1MGZhNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjJhYzVmOTdkYjgwZjlkYjIwMDFkNmZhOGY3MDJiM2IwZDNjMWI0MWY0MmUwNmFiYjQ4NDg2OTlkMmZhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pd6BrjqCkQaA9drxeOCeoIVc7I8Q487jlHixN9hUSiM)

Hi,

The space in the Selenium directory is a cache of your active browser sessions, you'd have to raise it with their project to store less, we have no control over it

**Comment by thebrumby** [comment]
> After deleting some folders, the folder with the script weighs a little again
> 
> ![image](https://private-user-images.githubusercontent.com/70477273/353022053-cfb6108c-901f-443d-9dbc-2780c6545b51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzYwMjcsIm5iZiI6MTcyMjI3NTcyNywicGF0aCI6Ii83MDQ3NzI3My8zNTMwMjIwNTMtY2ZiNjEwOGMtOTAxZi00NDNkLTlkYmMtMjc4MGM2NTQ1YjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNGI1YzAwYzcxYjIwNTJhOTAyNGM5MTZiNzVmOWI3MzE4MzAwMjIwNzhmYjZhYjRlYjcyYWQ5ZWIwZDU5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aEzsVbKgMAs-U2VJJ23Fnd9mA7EfD1OU3ux7irNhRMQ)

By deleting the selenium folder, you deleted all your browser sessions and the script will no longer work. 

```
./launch.sh status
```

Alternatively, you could have used this command to remove any inactive settings or chosen which games to remove.

**Comment by thebrumby** [comment]
> hey phil i'm experience same issue in my server. every time commit changes to docker image its got bigger and bigger.
> 
> execute last line make a image bigger than 14.7G, after push it to gitlab registry, it reduced to around 8G because of compression.

Hi,

The official Docker image is:

https://hub.docker.com/repository/docker/thebrumby/telegram-claim-bot/general

The compressed size according to the Docker website is 531.51 MB. When extracted to an AWS instance, it uses around 2.05 GB for the operating system, script, and dependencies.

Each game session should be expected to take between 100 MB and 350 MB for your saved Selenium browser session. The backup of the session which we take in case of a Chromedriver crash will also take up between 5 and 15 MB. Finally, you'll need to make an allowance for PM2 to store its logs, which could run to 15 MB per game session.

If you have limited hard drive space, you'll need to assess how many game sessions can be set up according to your hardware. If you really want to free up more space, you could delete the backups folder and keep on top of pruning PM2 logs. You can easily turn off PM2 logs by using the following command:

```
pm2 set pm2:log max_memory_restart 1M
```

This command will restart PM2 logs when they exceed 1 MB, effectively keeping the log size minimal.

On a side note, you mentioned you are pushing something to GitLab for compression. Are you saying you are pushing your container, including the created game sessions, to a private repository? In this case, the size would grow as the saved Selenium browser sessions grow, although I don't see how this would help long term as they will need decompressing again before you could use them.

Thanks

**Comment by fly-a1one** [comment]
> > I understand that the simplest solution is to just use a server with a lot of disk space, but at the moment I don't have that option. And in general, I think it's abnormal that the script allocates so much cache. Perhaps there is a solution to reduce it or periodically delete it.
> > P.S. Somehow I logged into the server and after a couple of minutes of waiting I was able to calculate the size of the folders. I have attached screenshots below. Basically, you can compare the size of my folders and folders if you install the script for the first time
> > ![image](https://private-user-images.githubusercontent.com/70477273/353020926-0852cefb-adff-49e9-a24b-cda5050fa542.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNzYwMjcsIm5iZiI6MTcyMjI3NTcyNywicGF0aCI6Ii83MDQ3NzI3My8zNTMwMjA5MjYtMDg1MmNlZmItYWRmZi00OWU5LWEyNGItY2RhNTA1MGZhNTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE3NTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMjJhYzVmOTdkYjgwZjlkYjIwMDFkNmZhOGY3MDJiM2IwZDNjMWI0MWY0MmUwNmFiYjQ4NDg2OTlkMmZhN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pd6BrjqCkQaA9drxeOCeoIVc7I8Q487jlHixN9hUSiM)
> 
> Hi,
> 
> The space in the Selenium directory is a cache of your active browser sessions, you'd have to raise it with their project to store less, we have no control over it

I understood you. I just don't understand why it keeps increasing. The same application, pictures and internal scripts are used there, the application does not change every time, etc. It is possible that the cache increases every time the browser is launched and caches the data

**Comment by thebrumby** [comment]
> I understood you. I just don't understand why it keeps increasing. The same application, pictures and internal scripts are used there, the application does not change every time, etc. It is possible that the cache increases every time the browser is launched and caches the data

Selenium caches the page elements from the game session and stores them for faster loading and reduced bandwidth consumption. For most users, this is more of a benefit than a hindrance. However, considering your situation, you could add an extra line to the browser configuration to stop it from storing images, CSS files, JavaScript files, etc.

The downside of this is that every time you make a claim, it will require downloading these resources again, creating a slower experience.

## Modify claimer.py

Add the following line to the browser configuration to disable the application cache:

```
chrome_options.add_argument("--disable-application-cache")  # Add this line to disable the application cache
```
Here's how the updated setup_driver function should look:
```
def setup_driver(self):
    chrome_options = Options()
    chrome_options.add_argument(f"user-data-dir={self.session_path}")
    chrome_options.add_argument("--headless")  # Ensure headless is enabled
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--disable-application-cache")  # Add this line to disable the application cache
```

After modifying the code, you could optionally delete your existing game sessions and recreate them to see how much space can be saved.

Thanks

**Comment by fly-a1one** [comment]
Thanks a lot, I'll try it

**Comment by farmdigit** [comment]
> you could delete the backups folder

How do I do that? Please explain.
Also can you make instructions how to delete backup, make backup, transfer and run backup on another server?

**Comment by rostamzad1900** [comment]
let's reset our conversation

what is the efficient way to backup all telegram logins and games ?
i ran 10 games on 10 telegram account.
if i want to migrate on another server, what is the efficient way to do that ?

**Comment by rostamzad1900** [comment]
> > hey phil i'm experience same issue in my server. every time commit changes to docker image its got bigger and bigger.
> > execute last line make a image bigger than 14.7G, after push it to gitlab registry, it reduced to around 8G because of compression.
> 
> Hi,
> 
> The official Docker image is:
> 
> https://hub.docker.com/repository/docker/thebrumby/telegram-claim-bot/general
> 
> The compressed size according to the Docker website is 531.51 MB. When extracted to an AWS instance, it uses around 2.05 GB for the operating system, script, and dependencies.
> 
> Each game session should be expected to take between 100 MB and 350 MB for your saved Selenium browser session. The backup of the session which we take in case of a Chromedriver crash will also take up between 5 and 15 MB. Finally, you'll need to make an allowance for PM2 to store its logs, which could run to 15 MB per game session.
> 
> If you have limited hard drive space, you'll need to assess how many game sessions can be set up according to your hardware. If you really want to free up more space, you could delete the backups folder and keep on top of pruning PM2 logs. You can manage PM2 logs effectively by using log rotation:
> 
> **Install pm2-logrotate:**
> 
> ```
> pm2 install pm2-logrotate
> ```
> 
> **Configure log rotation settings:**
> 
> ```
> pm2 set pm2-logrotate:max_size 1M
> pm2 set pm2-logrotate:retain 10
> pm2 set pm2-logrotate:compress true
> pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HH-mm-ss'
> pm2 set pm2-logrotate:workerInterval 30
> pm2 set pm2-logrotate:rotateInterval '0 0 * * *' # Rotate daily
> ```
> 
> On a side note, you mentioned you are pushing something to GitLab for compression. Are you saying you are pushing your container, including the created game sessions, to a private repository? In this case, the size would grow as the saved Selenium browser sessions grow, although I don't see how this would help long term as they will need decompressing again before you could use them.
> 
> Thanks


thank you for your attention phil.

let's reset our conversation

what is the efficient way to backup all telegram logins and games ?
i ran 10 games on 10 telegram account.
if i want to migrate on another server, what is the efficient way to do that ?

**Comment by fly-a1one** [comment]
> > > привет, Фил, у меня такая же проблема на моем сервере. каждый раз, когда я фиксирую изменения в образе docker, он становится все больше и больше. выполнение последней строки приводит к созданию изображения размером более 14,7 Гб, после загрузки его в реестр gitlab оно уменьшилось примерно до 8 ГБ из-за сжатия.
> > 
> > 
> > Привет,
> > Официальный образ Docker:
> > https://hub.docker.com/repository/docker/thebrumby/telegram-claim-bot/general
> > Размер сжатия, согласно веб-сайту Docker, составляет 531,51 МБ. При извлечении в экземпляр AWS для операционной системы, скрипта и зависимостей используется около 2,05 ГБ.
> > Ожидается, что каждый игровой сеанс будет занимать от 100 до 350 МБ для сохраненного сеанса браузера Selenium. Резервная копия сеанса, которую мы создаем на случай сбоя Chromedriver, также займет от 5 до 15 МБ. Наконец, вам нужно будет выделить PM2 для хранения его логов, объем которых может достигать 15 МБ за игровую сессию.
> > Если у вас ограничено место на жестком диске, вам нужно оценить, сколько игровых сессий можно настроить в зависимости от вашего оборудования. Если вы действительно хотите освободить больше места, вы могли бы удалить папку резервных копий и продолжить обрезку журналов PM2. Вы можете эффективно управлять журналами PM2, используя ротацию журналов:
> > **Установить pm2-logrotate:**
> > ```
> > pm2 install pm2-logrotate
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Настройка параметров ротации журналов:**
> > ```
> > pm2 set pm2-logrotate:max_size 1M
> > pm2 set pm2-logrotate:retain 10
> > pm2 set pm2-logrotate:compress true
> > pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HH-mm-ss'
> > pm2 set pm2-logrotate:workerInterval 30
> > pm2 set pm2-logrotate:rotateInterval '0 0 * * *' # Rotate daily
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Кстати, вы упомянули, что загружаете что-то в GitLab для сжатия. Вы хотите сказать, что загружаете свой контейнер, включая созданные игровые сессии, в частный репозиторий? В этом случае размер будет увеличиваться по мере роста сохраненных сеансов браузера Selenium, хотя я не вижу, как это поможет в долгосрочной перспективе, поскольку их нужно будет снова распаковать, прежде чем вы сможете их использовать.
> > Спасибо
> 
> спасибо за ваше внимание, Фил.
> 
> давайте перенесем наш разговор
> 
> каков эффективный способ резервного копирования всех логинов и игр telegram? я запустил 10 игр в 10 аккаунтах telegram. если я хочу выполнить миграцию на другой сервер, какой эффективный способ сделать это?

I think it's easier to recreate the necessary sessions and that's it, it will take a little time, about 30 minutes.
