### ISSUE TITLE
Feature Request: Add manual for proxy with a login and password and a backup

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#159]
Hi Phil! Thanks for everything you are doing.  
Can you please explain in detail how to add a proxy with login and password, as well as how to delete backup, make backup, transfer and run backup on another server? 
It's about docker on windows.
I have studied all the materials but nowhere found the necessary information.

**Comment by thebrumby** [comment]
Hi,

I'm pleased you are enjoying everything so far.

1. There is no proxy support with login and password yet, we might add that this month, please follow the [open issue](https://github.com/thebrumby/HotWalletClaimer/issues/119) for it.
2. If you want to delete one or more game accounts, you can do so by following the instructions for using the [status](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/STATUS.md) command.
3. If you want to create a backup server without entering the accounts again, you could take a backup of the game accounts, but bear in mind you'd manually need to set up the tasks in PM2 again, which might mean it's easier just to set them up the normal way.

## Backup the 3 game folders using docker CLI tools from outside the container:
### Use Windows Command Prompt, PowerShell, Ubuntu, or other Linux distributions CLI
```
docker cp telegram-claim-bot:/usr/src/app/screenshots .
docker cp telegram-claim-bot:/usr/src/app/backup .
docker cp telegram-claim-bot:/usr/src/app/selenium .
```
## Restore the 3 game folders using docker CLI tools from outside the container:
### Use Windows Command Prompt or PowerShell or Ubuntu or other Linux distributions CLI
```
docker cp ./screenshots telegram-claim-bot:/usr/src/app/screenshots
docker cp ./backup telegram-claim-bot:/usr/src/app/backup
docker cp ./selenium telegram-claim-bot:/usr/src/app/selenium
```

**Comment by farmdigit** [comment]
ty, Phil. 
Please tell me what each point means?
pm2 set pm2-logrotate:max_size 1M
pm2 set pm2-logrotate:retain 10
pm2 set pm2-logrotate:compress true
pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HHH-mm-mm-ss'
pm2 set pm2-logrotate:workerInterval 30
pm2 set pm2-logrotate:rotateInterval '0 0 0 * * * * *' # Rotate daily
how to delete pm2-logrotate without terminating sessions?


> Hi,
> 
> I'm pleased you are enjoying everything so far.
> 
> 1. There is no proxy support with login and password yet, we might add that this month, please follow the [open issue](https://github.com/thebrumby/HotWalletClaimer/issues/119) for it.
> 2. If you want to delete one or more game accounts, you can do so by following the instructions for using the [status](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/STATUS.md) command.
> 3. If you want to create a backup server without entering the accounts again, you could take a backup of the game accounts, but bear in mind you'd manually need to set up the tasks in PM2 again, which might mean it's easier just to set them up the normal way.
> 
> ## Backup the 3 game folders using docker CLI tools from outside the container:
> ### Use Windows Command Prompt, PowerShell, Ubuntu, or other Linux distributions CLI
> ```
> docker cp telegram-claim-bot:/usr/src/app/screenshots .
> docker cp telegram-claim-bot:/usr/src/app/backup .
> docker cp telegram-claim-bot:/usr/src/app/selenium .
> ```
> 
> ## Restore the 3 game folders using docker CLI tools from outside the container:
> ### Use Windows Command Prompt or PowerShell or Ubuntu or other Linux distributions CLI
> ```
> docker cp ./screenshots telegram-claim-bot:/usr/src/app/screenshots
> docker cp ./backup telegram-claim-bot:/usr/src/app/backup
> docker cp ./selenium telegram-claim-bot:/usr/src/app/selenium
> ```

ty, Phil. 
Please tell me what each point means?
pm2 set pm2-logrotate:max_size 1M
pm2 set pm2-logrotate:retain 10
pm2 set pm2-logrotate:compress true
pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HHH-mm-mm-ss'
pm2 set pm2-logrotate:workerInterval 30
pm2 set pm2-logrotate:rotateInterval '0 0 0 * * * * *' # Rotate daily
how to delete pm2-logrotate without terminating sessions?

**Comment by thebrumby** [comment]
Here's what each PM2 Logrotate configuration command means:

1. `pm2 set pm2-logrotate:max_size 1M`
   - Sets the maximum log file size to 1 megabyte. When a log file reaches this size, it will be rotated.

2. `pm2 set pm2-logrotate:retain 10`
   - Retains the last 10 rotated log files and deletes older ones to save disk space.

3. `pm2 set pm2-logrotate:compress true`
   - Enables compression for rotated log files, saving disk space.

4. `pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HH-mm-ss'`
   - Sets the timestamp format for log file names to year-month-day_hour-minute-second.

5. `pm2 set pm2-logrotate:workerInterval 30`
   - The log rotation worker checks every 30 seconds if any log file needs rotation based on size.

6. `pm2 set pm2-logrotate:rotateInterval '0 0 0 * * * * *'`
   - Schedules log rotation to occur daily at midnight.

To delete pm2-logrotate without terminating sessions, follow these steps:

1. Disable pm2-logrotate:
   ```bash
   pm2 set pm2-logrotate:enable false
   ```
2. Uninstall pm2-logrotate:
   ```bash
   pm2 uninstall pm2-logrotate
   ```
   This will remove the pm2-logrotate module without affecting your running PM2 processes.

Best regards, Phil

**Comment by farmdigit** [comment]
> * Retains the last 10 rotated log files and deletes older ones to save disk space.

What parameter should be set if for example there are 15 telegram accounts and each has 3 bots (Poketfi, Blum, Hot)? Explain please, this point is not clear.

**Comment by thebrumby** [comment]
> > * Retains the last 10 rotated log files and deletes older ones to save disk space.
> 
> What parameter should be set if for example there are 15 telegram accounts and each has 3 bots (Poketfi, Blum, Hot)? Explain please, this point is not clear.

In this situation, 15 TG accounts multiply by 3 games each, then you would have 45 game sessions. In terms of PM2 logs, each of the 45 sessions would have 1 uncompressed log file (45 mb) and 9 compressed log files (maybe another 200 mb). 

If you want to save more space and keep less data, reduce the number of saved settings.

**Comment by farmdigit** [comment]
> each of the 45 sessions would have 1 uncompressed log file (45 mb) and 9 compressed log files (maybe another 200 mb).

Does that mean that in this case I should set the settings like this?

pm2 set pm2-logrotate:max_size 1M
pm2 set pm2-logrotate:retain 450
pm2 set pm2-logrotate:compress true
pm2 set pm2-logrotate:dateFormat 'YYYY-MM-DD_HHH-mm-mm-ss'
pm2 set pm2-logrotate:workerInterval 30
pm2 set pm2-logrotate:rotateInterval '0 0 0 * * * * *' # Rotate daily

Or am I misunderstanding?

**Comment by thebrumby** [comment]
The log rotate retain parameter is per process. So, in your example, it would save the most recent 450 logs for each of your 45 processes. If your goal is to minimize disk storage usage, it is best to use smaller numbers. Theoretically, you could even just have a single log file retained per process, though this might not provide enough historical data for troubleshooting. Adjust the number based on your needs for log retention versus disk space availability.

**Comment by farmdigit** [comment]
> The log rotate retain parameter is per process. So, in your example, it would save the most recent 450 logs for each of your 45 processes. If your goal is to minimize disk storage usage, it is best to use smaller numbers. Theoretically, you could even just have a single log file retained per process, though this might not provide enough historical data for troubleshooting. Adjust the number based on your needs for log retention versus disk space availability.

how to set up the log rotate as efficiently as possible in this case?

**Comment by thebrumby** [comment]
Hi, 

You could set the number of retained logs to the bare minimum if your only concern is to fit the maximum number of sessions onto the single server, and you aren't interested it keeping any further history.

```
pm2 set pm2-logrotate:retain 1
```

**Comment by farmdigit** [comment]
> Hi,
> 
> You could set the number of retained logs to the bare minimum if your only concern is to fit the maximum number of sessions onto the single server, and you aren't interested it keeping any further history.

Thanks for the answer, Phil.
