### ISSUE TITLE
Can you rewrite script request on Sui network? (ocean claim)

### ISSUE THREAD

**Issue by nthanhtung92** [thebrumby/HotWalletClaimer#16]
[hot-auto-claim-main.zip](https://github.com/thebrumby/HotWalletClaimer/files/15389627/hot-auto-claim-main.zip)

It is the same the file, I have uploaded here with Near network

Please check it, I hope that you can write the script same like that on SUI network (OCEAN)

Thank you very much. Have a nice day!

**Comment by thebrumby** [comment]
Hi,

The 4 games we currently support are Ocean (SUI), Hot (Near), Vertus & Cold (both say BSC, but do not mine to the blockchain). All the scripts work by interacting with a virtual browser session to ensure they appear "human-like" to the game. 

Did you have a sugguestion to modify or change something with the exsisting code?

<html>
<body>

Command | Mining Game Link in Telegram | Ubuntu | Docker
-- | -- | -- | --
./launch.sh hot | Launch HOT on Near Protocol: herewalletbot | ✅ | ✅
./launch.sh cold | Launch Cold on BNB Wallet: Newcoldwallet_bot | ✅ | ❌
./launch.sh vertus | Launch Vertus on TON: vertus_app_bot | ❌ | ❌
./launch.sh tree | Launch Tree on BNB Wallet: treeminebot | ✅ | ✅
./launch.sh wave | Launch Wave Wallet on Sui: waveonsuibot | ✅ | ✅


</body>
</html>Command	Mining Game Link in Telegram	Ubuntu	Docker
./launch.sh hot	Launch HOT on Near Protocol: [herewalletbot](https://t.me/herewalletbot)	✅	✅
./launch.sh cold	Launch Cold on BNB Wallet: [Newcoldwallet_bot](https://t.me/Newcoldwallet_bot)	✅	❌
./launch.sh vertus	Launch Vertus on TON: [vertus_app_bot](https://t.me/vertus_app_bot)	❌	❌
./launch.sh tree	Launch Tree on BNB Wallet: [treeminebot](https://t.me/treeminebot/app?startapp=6783218884)	✅	✅
./launch.sh wave	Launch Wave Wallet on Sui: [waveonsuibot](https://t.me/waveonsuibot/walletapp?startapp=1809774)	✅	✅

**Comment by nthanhtung92** [comment]
Thanks for your reply.
I down your script, but I cant sign in telegram.

**Comment by thebrumby** [comment]
OK, you're not giving me much information on which to help! Please try following the steps like in this issue https://github.com/thebrumby/HotWalletClaimer/issues/12 to determine where the fault is.

Thanks.

**Comment by nthanhtung92** [comment]
Devtools/Inspect/F12 => Network => {!}add => Preview => copy access_token

I hope that you can replace log in -> use access_token

**Comment by thebrumby** [comment]
Hi, 

I just discovered today that Telegram changed their XPATHs for logging in - I've pushed new updates to the affected games and you should now be able to log in via QR code or by entering the phone number and one-time password.

I hope this resolves your issues. Thanks for raising the issue.
