### ISSUE TITLE
Time Farm Errors

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#160]
hi ad Today i got errors with the timefarm. 
 File "/usr/src/app/games/time-farm.py", line 191, in <module>
main()
File "/usr/src/app/games/time-farm.py", line 188, in main
claimer.run()
File "/usr/src/app/games/claimer.py", line 160, in run
wait_time = self.full_claim()
            ^^^^^^^^^^^^^^^^^
File "/usr/src/app/games/time-farm.py", line 95, in full_claim
remaining_time = self.apply_random_offset(remaining_time)
File "/usr/src/app/games/claimer.py", line 1392, in apply_random_offset
if self.settings['allowEarlyClaim']:
 KeyError: 'allowEarlyClaim'

**Comment by thebrumby** [comment]
Hi,

Please update your code.

**Comment by prognt** [comment]
```
1   | HOT:1831             | 1.066029             | 0.009                | 02 August - 04:40    | An error occurred while trying to claim: 'allowEarlyClaim'                       |
| 2   | Oxygen:1831          | 4071.608             | None                 | 02 August - 04:39    | An error occurred while trying to claim: 'allowEarlyClaim'
```

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Please update your code.

Hi I update the latest and got that errors

**Comment by bscongluanbui** [comment]
> ```
> 1   | HOT:1831             | 1.066029             | 0.009                | 02 August - 04:40    | An error occurred while trying to claim: 'allowEarlyClaim'                       |
> | 2   | Oxygen:1831          | 4071.608             | None                 | 02 August - 04:39    | An error occurred while trying to claim: 'allowEarlyClaim'
> ```

I got the same

**Comment by thebrumby** [comment]
Hi, 

The claimer.py file in the repository was out-of-date. I've pushed the new version if you could kindly update and restart.
