### ISSUE TITLE
Hey i can't get my wallet to start again

### ISSUE THREAD

**Issue by badmosh23** [thebrumby/HotWalletClaimer#163]
For some days they are unactive and now getting this issue
![image](https://github.com/user-attachments/assets/76be5184-8cdf-4d06-a346-c62c35f259f3)

**Comment by Wellynounet** [comment]
try pm2 resurrect

**Comment by bscongluanbui** [comment]
I got the same problem with him and pm2 resurrect not working. i must delete all amd install from beginning, It’s take a lot of time of me

**Comment by badmosh23** [comment]
thanks that fix my issue
