### ISSUE TITLE
Blum isn't working properly 

### ISSUE THREAD

**Issue by HoN3YP0T** [thebrumby/HotWalletClaimer#164]
![Screenshot_2024-08-04-00-12-58-19_61c78dc80ee02b53007c815fefe993e3](https://github.com/user-attachments/assets/45e37aad-b1e5-4d73-8030-ac016ad997fe)

**Comment by thebrumby** [comment]
Hi, 

It's working correctly for me, and there is no information in your screenshot to suggest what the error might be.

To save you reading too many posts of the steps needed to debug your Blum session, I have created a Troubleshooting Guide: https://github.com/thebrumby/HotWalletClaimer/issues/166

Kindly follow the steps and report any resolved findings. 

Note, Blum requested the built-in Proxy to be running correctly to make contact with the game. It's important to ensure you have the `http-proxy` process running in PM2 as well as the game session.

Thanks
