### ISSUE TITLE
Tree error

### ISSUE THREAD

**Issue by oboroccv** [thebrumby/HotWalletClaimer#165]
![image](https://github.com/user-attachments/assets/8146f7ce-f4b6-4ff3-aecc-538597c5ad5a)

co claim

**Comment by thebrumby** [comment]
Did you not see yesterday's reply?

The game developers are blocking access via Telegram Web. If/When they re-open it, the script will be updated.

https://github.com/thebrumby/HotWalletClaimer/issues/161

Thanks
