### ISSUE TITLE
SimpleTap not Working

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#168]
Hi admin, today I got SimpleTap not working anymore 
 Traceback (most recent call last):
55|SimpleTap:vina  |   File "/usr/src/app/games/simpletap.py", line 238, in <module>
55|SimpleTap:vina  |     main()
55|SimpleTap:vina  |   File "/usr/src/app/games/simpletap.py", line 235, in main
55|SimpleTap:vina  |     claimer.run()
55|SimpleTap:vina  |   File "/usr/src/app/games/claimer.py", line 159, in run
55|SimpleTap:vina  |     wait_time = self.full_claim()
55|SimpleTap:vina  |                 ^^^^^^^^^^^^^^^^^
55|SimpleTap:vina  |   File "/usr/src/app/games/simpletap.py", line 87, in full_claim
55|SimpleTap:vina  |     self.get_balance(False)
55|SimpleTap:vina  |   File "/usr/src/app/games/simpletap.py", line 166, in get_balance
55|SimpleTap:vina  |     if button: button.click()
55|SimpleTap:vina  |                ^^^^^^^^^^^^^^
55|SimpleTap:vina  |   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
55|SimpleTap:vina  |     self._execute(Command.CLICK_ELEMENT)
55|SimpleTap:vina  |   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
55|SimpleTap:vina  |     return self._parent.execute(command, params)
55|SimpleTap:vina  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
55|SimpleTap:vina  |   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
55|SimpleTap:vina  |     self.error_handler.check_response(response)
55|SimpleTap:vina  |   File "/usr/src/app/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
55|SimpleTap:vina  |     raise exception_class(message, screen, stacktrace)
55|SimpleTap:vina  | selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="appbar-tab">...</div> is not clickable at point (118, 564). Other element would receive the click: <div class="boost_inner_scroll">...</div>
55|SimpleTap:vina  |   (Session info: headless chrome=112.0.5615.49)
55|SimpleTap:vina  | Stacktrace:
55|SimpleTap:vina  | #0 0x00556ea12bf4 <unknown>
55|SimpleTap:vina  | #1 0x00556e77e040 <unknown>
55|SimpleTap:vina  | #2 0x00556e7bb018 <unknown>
55|SimpleTap:vina  | #3 0x00556e7b8f68 <unknown>
55|SimpleTap:vina  | #4 0x000000000000 <unknown>
55|SimpleTap:vina  | Initialising the SimpleTap: Wallet Auto-claim Python Script - Good Luck!
55|SimpleTap:vina  | Session ID provided: SimpleTap:vina
55|SimpleTap:vina  | Proxy disabled in settings.
55|SimpleTap:vina  | Resuming the previous session...
55|SimpleTap:vina  | No user agent found, using default.
55|SimpleTap:vina  | CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
55|SimpleTap:vina  | Step 101 - Attempting to check for the start button (should not be present)... [//button[contains(., 'START')]]
55|SimpleTap:vina  | Step 102 - Attempting to open a link for the app: //div[contains(@class, 'new-message-wrapper')]//div[contains(text(), 'Start')]...
55|SimpleTap:vina  | Step 103 - Attempting to click the 'Launch' button (probably not present)... [//button[contains(@class, 'popup-button') and contains(., 'Launch')]]

**Comment by thebrumby** [comment]
Thanks - they are currently blocking TG web. I'll set it to not working on the main page.

**Comment by thebrumby** [comment]
Hi, 

Simple Tap should now be repaired, you will need to ensure your proxy is up-to-date before restarting:

```
pm2 delete http-proxy
pm2 save
./launch.sh enable-proxy
```

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Simple Tap should now be repaired, you will need to ensure your proxy is up-to-date before restarting:
> 
> ```
> pm2 delete http-proxy
> pm2 save
> ./launch.sh enable-proxy
> ```

thank you
