### ISSUE TITLE
Cant login into telegram

### ISSUE THREAD

**Issue by wordfangsss** [thebrumby/HotWalletClaimer#17]
![Screenshot (61)](https://github.com/thebrumby/HotWalletClaimer/assets/115153469/d9dbe0ce-7ee0-4370-9649-bb2e242e17b2)
After entering country name then show errors

**Comment by thebrumby** [comment]
Hi it appears Selenium is unable to get to the target. Is this issue with Docker or standalone Linux, please?

**Comment by wordfangsss** [comment]
Using linux

**Comment by thebrumby** [comment]
Thanks for info, I'll look to see if there's more we can do on my side to fix it.

**Comment by thebrumby** [comment]
Hey wordfangsss!

It appears that Telegram changed some of the so-called XPATHs which the script uses to interact with the various links and stuff in the browser on your behalf.

I tested them across all platforms and none of them worked, as you correctly flagged in. I've pushed updates to the scripts into the repository, which now work correctly in my test environments. 

Please feel free to add extra comments whether this works for you or not, for now I'll close the issue, just to help me track what is live or not.
