### ISSUE TITLE
LumCity Issue

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#170]
Hi ad, a small issue with lumcity app. When the bot run, it's comment "start" on the app and got error but If we change /app and working perfectly. Hope you update it on the future

**Comment by Wellynounet** [comment]
hello

 if you think we need to push some update pls provide  with pull request .

**Comment by thebrumby** [comment]
Good spot, 

I had to get follow-up referral codes a few times, but I never realized it was after using the start command! Duly updated. 

Thanks
