### ISSUE TITLE
Can't find the Log in button (HOT WALLET)

### ISSUE THREAD

**Issue by goncharovnr** [thebrumby/HotWalletClaimer#18]
The script cannot find the login button and gives an error
![image](https://github.com/thebrumby/HotWalletClaimer/assets/97805496/ea63138d-fcd8-4bfd-8363-fd5d40999962)

**Comment by thebrumby** [comment]
Hi, 

I tried with both supported browsers (Chrome/Chromium) to recreate the error and can't do so. If you could help us to help you:

1. Are you using the latest version of the script (uploaded 22nd May)
2. Are you using Docker or Standalone Linux?
3. Please enable debugging and share the photos from screenshots/tg1 so we can see the last few screenshots so we can see what step it's failing on.

<img width="262" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/9dc9d423-7fa2-49a2-8241-3db5e98ef23c">

<img width="272" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/b7d77267-3575-49f7-b409-507255e09248">

Thanks

**Comment by goncharovnr** [comment]
Hi
1. I downloaded all the latest using this command: sudo apt install -y git
git clone https://github.com/thebrumby/HotWalletBot.git
cd HotWalletBot
sudo chmod +x install.sh launch.sh
./install.sh
2. I use uduntu 24.04 LTS on Windows
3.
![image](https://github.com/thebrumby/HotWalletClaimer/assets/97805496/790a49d9-f1fc-429d-b1c0-697a4bb69f98)
![image](https://github.com/thebrumby/HotWalletClaimer/assets/97805496/fcbea005-d861-4529-a09a-d7a717e13464)
fe
![image](https://github.com/thebrumby/HotWalletClaimer/assets/97805496/2b760639-7696-4777-92d5-9d7cc6aaf646)
The names of the steps are visible at the top of the screenshot

**Comment by thebrumby** [comment]
Hi,

Thanks for the detailed reply. We can see Telegram is correctly connected, but there is no content in the Near Wallet pop-up for the script to interact with. 

The only time I saw that before was when they onboarded a lot of new users and the site had a lot of lag. Then after a few days, it came back. However, in this case, I think they resolved that.

From a programming point of view, there's not much I can do, because I can't make it interact with something that doesn't appear and is working well for my location. I did make one tweak to the script today, but I'm not confident it will solve the problem. The only other thing I can suggest is to try to run from a VPN, or different location, to see if you still have the issue. 

Feel free to keep me updated on your progress though. One final thought: you try connecting to any of the other games (Tree/Vertus/Cold don't require real tokens of gas fee) to see if they are responding OK?

Thanks

**Comment by thebrumby** [comment]
Hi,

I never used a VPN in Ubuntu before but seems you just download and set up the config file. However, I'm thinking now, that the issue must be something else. All these games are hosted from different domains, so even if one was blocked, it's hard to imagine they all are.

Are you using VPS or running it locally in your own place? I was thinking if running locally, you could try to access "https://web.telegram.org/k/#@herewalletbot" from another browser using the same connection. Although obviously that won't work if using a VPS.

**Comment by goncharovnr** [comment]
I'm just running ubuntu on my PC

**Comment by goncharovnr** [comment]
how can I use another browser?

**Comment by Wellynounet** [comment]
> I'm just running ubuntu on my PC
 can you connect with your phone ? or use the app on your PC ?  with TG  web ? 
 https://web.telegram.org/k/

**Comment by goncharovnr** [comment]
> > I'm just running ubuntu on my PC >
> > can you connect with your phone ? or use the app on your PC ?  with TG  web ?
> > https://web.telegram.org/k/

Yes, telegram applications work on PC, but not on Ubuntu

**Comment by thebrumby** [comment]
> how can I use another browser?

Based on Ubuntu on a "normal" AMD style PC (not a Mac) you have a couple of options.

### Option 1: Change Browser with your existing setup

1. Change into the directory (if you're not already) with:
    ```sh
    cd HotWalletBot
    ```
2. Run the installer a second time:
    ```sh
    ./installer.sh
    ```
3. It will prompt you to tell you which browser is installed, you can type "y" and hit enter to swap to Chromium.

### Option 2: Switch to a prebuilt Docker image

We're also experimenting with a Docker Image that makes it easier to have all the dependencies working: 

1. Install Docker Desktop and open it: [Docker Desktop](https://www.docker.com/products/docker-desktop/)
2. Open the command prompt terminal, which can be done numerous ways - but win key + r, then type `cmd` and press enter
3. Run these commands:
    ```sh
    docker run -d --name telegram-claim-bot thebrumby/telegram-claim-bot:1.1
    docker exec -it telegram-claim-bot /bin/bash
    ```


<img width="727" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/839afa73-db16-405e-9e36-531c11ef2bc6">

**Comment by goncharovnr** [comment]
The second method with Docker helped! Thank you! <3
