### ISSUE TITLE
HOT Block Claiming (just to know)

### ISSUE THREAD

**Issue by rostamzad1900** [thebrumby/HotWalletClaimer#180]
hi to everyone
it's not an issue
it's just a reminder that hot game block claiming if you don't watch a certain video on youtube.
check your wallet in telegram.
8/14/2024

**Comment by thebrumby** [comment]
Ok, I'm away from the PC for a few days, but will look next week at how to view that.

**Comment by thebrumby** [comment]
I just checked on a random account and it's still claiming with no video (yet) - I guess it must be a random thing. Do you have any screenshots?

**Comment by rostamzad1900** [comment]
check status

![image_2024-08-14_14-17-12](https://github.com/user-attachments/assets/b97d1732-a03d-44d3-b1c2-f0752b1071e5)

**Comment by rostamzad1900** [comment]
> I just checked on a random account and it's still claiming with no video (yet) - I guess it must be a random thing. Do you have any screenshots?

i passed this step for all my account, it's not appear now

**Comment by rostamzad1900** [comment]
ohhhhh noooo

now it's an issue
after passing video force to watch problem, now claiming process not working. restart all pm2 doesn't any help

**Comment by rostamzad1900** [comment]
as you see can't claim
selected item claimed manually.

![image_2024-08-14_15-40-23](https://github.com/user-attachments/assets/4120a7e9-0aaa-46b2-a2ad-f027152b0bd3)

**Comment by thebrumby** [comment]
OK, as mentioned earlier, I’m on holiday so will take a look early next week.

**Comment by badmosh23** [comment]
> as you see can't claim selected item claimed manually.
> 
> ![image_2024-08-14_15-40-23](https://private-user-images.githubusercontent.com/89634871/357808832-4120a7e9-0aaa-46b2-a2ad-f027152b0bd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NTEyMzQsIm5iZiI6MTcyMzY1MDkzNCwicGF0aCI6Ii84OTYzNDg3MS8zNTc4MDg4MzItNDEyMGE3ZTktMGFhYS00NmIyLWEyYWQtZjAyNzE1MmIwYmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE1NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMTFjYjdmYjQyMDk2YTQyYWFjNzExMjRjYjQwMTJjZGJlZTNlMmFiNTg1NGUxYjMyMmU1MDZkZmJkMDM3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZRta2Sf4g2-kcYuGXJcZXdb7j30nGqXTPjeCz2xCmAA)

in my case some of the wallets are claming and some are not

**Comment by Wellynounet** [comment]
hey for me  I have 24 h claim 
i dont have issue Yet 
![image](https://github.com/user-attachments/assets/da8e7de5-c989-4435-9365-8065ce8e53a2)

**Comment by Suman2131** [comment]
![IMG_20240813_094340](https://github.com/user-attachments/assets/80dc3434-90fb-4147-b35b-07fd869c63ed)
This is coming in some account

**Comment by thebrumby** [comment]
Thanks. While this can sometimes happen if there is game lag, or the user drops below 0.2 Near balance (the game throws an error regarding gas fees), but most likely it’s linked to the video. 

Definately worth checking your Near Balance if it might be close to 0.2 though. The point the game rejects mining is much higher than the real gas fee threshold.

**Comment by thebrumby** [comment]
Just an FYI, I have 24 accounts all claiming well!

**Comment by thebrumby** [comment]
Hi all,

Any further updates on this issue? Is everyone the latest version of the code, with the processes restarted since updating and > 0.2 Near in each account for gas fee? None of my accounts are having any of the issues described above, is it still an issue for you?

**Comment by Wellynounet** [comment]
Still all good for me

**Comment by badmosh23** [comment]
im having that problem still those account who dont have near around 0.2 are still mining and some are not its related to video probably 
![image](https://github.com/user-attachments/assets/349126c7-2a49-4bdb-afe2-e1f194575cfc)

**Comment by thebrumby** [comment]
Hi,

I can't see any video which blocks the claims process, only this:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/ed35a7c5-a62a-4d7d-9273-b011e67cd519">

**Comment by thebrumby** [comment]
Hi, 

I can't see any video which blocks the claims process, only this:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/5b8336c9-399a-4da6-816b-0462541af546">

**Comment by bscongluanbui** [comment]
You must have gas. It’s will claim if you have near

**Comment by badmosh23** [comment]
Ohh sorry you are right all those accounts which have less than 0.1 dollar worth of near are facing this problem we just need to have more than 0.1 dollar worth of near in account 
Thanks for your help 🙂

**Comment by thebrumby** [comment]
As mentioned above, Hot requires you to hold a minimum maintaining balance of 0.2 Near coins - even though the gas fee is much less. If you drop below this they may reject your transactions from going to the blockchain. The dollar value is irrelevant to the game as the gas fee and minimum balance is in Near Protocol coins not dollars 😋

**Comment by rostamzad1900** [comment]
> Hi,
> 
> I can't see any video which blocks the claims process, only this:
> 
> <img alt="image" width="345" src="https://private-user-images.githubusercontent.com/29182343/358851078-5b8336c9-399a-4da6-816b-0462541af546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjM1NDEsIm5iZiI6MTcyMzkyMzI0MSwicGF0aCI6Ii8yOTE4MjM0My8zNTg4NTEwNzgtNWI4MzM2YzktMzk5YS00ZGE2LTgxNmItMDQ2MjU0MWFmNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE5MzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NWM2NTM4YjllNWM2YzM1YzU1Mzk3M2M2ZGMxOTNjOWZjNzIzZjQ1ODcxMjEwY2RhMTVhN2Q2ZjUxMjNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1efO0v8HClLNRdudcOUBKe7XyRxOF4yKUN30lKyI1fg">

hey phil

some days ago i check randomly one of my hot wallet and find out claiming process is not working, when i want to click on claim button an overlay like this screenshot was appeared, i'm try to bypass it. but doesn't make any difference.
it's not something i made up from my imagination.
i don't know why this is not appear on other wallets. maybe it was appear just in time i checked my wallet, i don't know. at that moment i think this is something important and maybe inform to other folks it's a good idea.

![Screenshot_20240815-140325](https://github.com/user-attachments/assets/34640204-f355-47c3-91e5-9559a0319bba)

**Comment by rostamzad1900** [comment]
> As mentioned above, Hot requires you to hold a minimum maintaining balance of 0.2 Near coins - even though the gas fee is much less. If you drop below this they may reject your transactions from going to the blockchain. The dollar value is irrelevant to the game as the gas fee and minimum balance is in Near Protocol coins not dollars 😋

0.2 minimum near is something new to the game ?
i'm not hold any coin in hot wallet and until few days ago claiming process was perfect, but suddenly it's not working anymore through code but claiming manually worked as before.

gas fee can paid in 
1- hot : 50% of claimed hot
2- near : 0.002$ in near for every claim

code still not working.
i'm check manually claiming once again and take this screenshots for clarification:

![file](https://github.com/user-attachments/assets/fe4b6b13-b0aa-4fd8-ac2a-fca940493b9d)

**Comment by rostamzad1900** [comment]
set `debugIsOn = True`
delete all hot with : ` ./launch.sh status.py` then `delete HOT`
add new Hot wallet to check what is going on, its not even click on Check News !!

![116__monitor_element](https://github.com/user-attachments/assets/74f7db4c-4863-4c0b-b903-2b38268b0a0a)

**Comment by bscongluanbui** [comment]
The code was fine on me. I have near for gas to claim

**Comment by thebrumby** [comment]
> code still not working. i'm check manually claiming once again and take this screenshots for clarification:

The code was never designed to handle situations were the user doesn't have sufficient gas fees to cover their own transaction, so it's not correct to say it's not working correctly, it just doesn't do what you wanted it to.

<img width="646" alt="image" src="https://github.com/user-attachments/assets/8a87e2d2-35e1-41d0-931e-2dc6389c729e">

We might make a spin-off script that will choose the option to use hot in the future.

**Comment by thebrumby** [comment]
> > Hi,
> > I can't see any video which blocks the claims process, only this:
> > <img alt="image" width="345" src="https://private-user-images.githubusercontent.com/29182343/358851078-5b8336c9-399a-4da6-816b-0462541af546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MjM1NDEsIm5iZiI6MTcyMzkyMzI0MSwicGF0aCI6Ii8yOTE4MjM0My8zNTg4NTEwNzgtNWI4MzM2YzktMzk5YS00ZGE2LTgxNmItMDQ2MjU0MWFmNTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDE5MzQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NWM2NTM4YjllNWM2YzM1YzU1Mzk3M2M2ZGMxOTNjOWZjNzIzZjQ1ODcxMjEwY2RhMTVhN2Q2ZjUxMjNhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1efO0v8HClLNRdudcOUBKe7XyRxOF4yKUN30lKyI1fg">
> 
> hey phil
> 
> some days ago i check randomly one of my hot wallet and find out claiming process is not working, when i want to click on claim button an overlay like this screenshot was appeared, i'm try to bypass it. but doesn't make any difference. it's not something i made up from my imagination. i don't know why this is not appear on other wallets. maybe it was appear just in time i checked my wallet, i don't know. at that moment i think this is something important and maybe inform to other folks it's a good idea.
> 
> ![Screenshot_20240815-140325](https://private-user-images.githubusercontent.com/89634871/358866806-34640204-f355-47c3-91e5-9559a0319bba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzE4MDcsIm5iZiI6MTcyMzk3MTUwNywicGF0aCI6Ii84OTYzNDg3MS8zNTg4NjY4MDYtMzQ2NDAyMDQtZjM1NS00N2MzLTkxZTUtOTU1OWEwMzE5YmJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4NTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDkzODIwMDM0NmMzNjVmZGI1OTljMTFmMzIwMzU3MmNiZWI1OWEzZTYwM2Y0YTJjNjdhMGVmNzMyODYzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iI6VSBWvp3mHgL3WkI3xzK1CDarUKqOgDLaFCB2zvyU)

These kind of overlays have been present for a long time, it led to the introduction of this code many months ago:

```
    def clear_overlays(self, target_element, step):
        try:
            element_location = target_element.location_once_scrolled_into_view
            overlays = self.driver.find_elements(By.XPATH, "//*[contains(@style,'position: absolute') or contains(@style,'position: fixed')]")
            overlays_cleared = 0
            for overlay in overlays:
                overlay_rect = overlay.rect
                if (overlay_rect['x'] <= element_location['x'] <= overlay_rect['x'] + overlay_rect['width'] and
                    overlay_rect['y'] <= element_location['y'] <= overlay_rect['y'] + overlay_rect['height']):
                    self.driver.execute_script("arguments[0].style.display = 'none';", overlay)
                    overlays_cleared += 1
            self.output(f"Step {step} - Removed {overlays_cleared} overlay(s) covering the target.", 3)
            return overlays_cleared
        except Exception as e:
            self.output(f"Step {step} - An error occurred while trying to clear overlays: {e}", 1)
            return 0
```

The key line is `self.driver.execute_script("arguments[0].style.display = 'none';", overlay)` which removes the element from the field of view. This if you check the following screenshots, you should see this has been removed for the next step.

**Comment by bscongluanbui** [comment]
> > ![Screenshot_20240815-140325](https://private-user-images.githubusercontent.com/89634871/358866806-34640204-f355-47c3-91e5-9559a0319bba.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NzE4MDcsIm5iZiI6MTcyMzk3MTUwNywicGF0aCI6Ii84OTYzNDg3MS8zNTg4NjY4MDYtMzQ2NDAyMDQtZjM1NS00N2MzLTkxZTUtOTU1OWEwMzE5YmJhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDA4NTgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDkzODIwMDM0NmMzNjVmZGI1OTljMTFmMzIwMzU3MmNiZWI1OWEzZTYwM2Y0YTJjNjdhMGVmNzMyODYzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iI6VSBWvp3mHgL3WkI3xzK1CDarUKqOgDLaFCB2zvyU)
> 
> These kind of overlays have been present for a long time, it led to the introduction of this code many months ago:
> 
> ```
>     def clear_overlays(self, target_element, step):
>         try:
>             element_location = target_element.location_once_scrolled_into_view
>             overlays = self.driver.find_elements(By.XPATH, "//*[contains(@style,'position: absolute') or contains(@style,'position: fixed')]")
>             overlays_cleared = 0
>             for overlay in overlays:
>                 overlay_rect = overlay.rect
>                 if (overlay_rect['x'] <= element_location['x'] <= overlay_rect['x'] + overlay_rect['width'] and
>                     overlay_rect['y'] <= element_location['y'] <= overlay_rect['y'] + overlay_rect['height']):
>                     self.driver.execute_script("arguments[0].style.display = 'none';", overlay)
>                     overlays_cleared += 1
>             self.output(f"Step {step} - Removed {overlays_cleared} overlay(s) covering the target.", 3)
>             return overlays_cleared
>         except Exception as e:
>             self.output(f"Step {step} - An error occurred while trying to clear overlays: {e}", 1)
>             return 0
> ```
> 
> The key line is `self.driver.execute_script("arguments[0].style.display = 'none';", overlay)` which removes the element from the field of view. If you check the following screenshots, you should see this has been removed for the next step.

I think The only thing block on free gas accounts is the 2 options (-50% hot and deposit gas), must click -50%hot for working

**Comment by thebrumby** [comment]
> I think The only thing block on free gas accounts is the 2 options (-50% hot and deposit gas), must click -50%hot for working

Probably so. I'll see if I can empty an account low enough for it to fail.

**Comment by basu180** [comment]
> You must have gas. It’s will claim if you have near
after having gas 0.25 ,it's not working
same like first

**Comment by rostamzad1900** [comment]
having gas fee is irrelevant, it's not mandatory
all my account running again without deposit any Near.

![image_2024-08-19_20-00-59](https://github.com/user-attachments/assets/cfa57465-6cd0-46b5-8350-1e2657b4dd65)

**Comment by thebrumby** [comment]
Right, it’s not mandatory, but in the screen you posted, it showed there was at least one link to click. 

I tried to recreate it with an account with no Near, but the screen didn’t appear. It looks like it was something the game devs introduced for users witb no gas fee and then withdrew. Those of us who had gas fee were able to claim throughout.

**Comment by rostamzad1900** [comment]
> Right, it’s not mandatory, but in the screen you posted, it showed there was at least one link to click.
> 
> I tried to recreate it with an account with no Near, but the screen didn’t appear. It looks like it was something the game devs introduced for users witb no gas fee and then withdrew. Those of us who had gas fee were able to claim throughout.

i check my account today, this overlay was vanished for good.

**Comment by thebrumby** [comment]
Great. If it comes back again I’ll add a check.
