### ISSUE TITLE
Cannot claim Blum, Unknown status

### ISSUE THREAD

**Issue by phamvanhanh6720** [thebrumby/HotWalletClaimer#181]
Thank you so muck for your working. 

I got a issue when running claim Blum. I hope you can fix this issue.
I always got the unknown status when running claim Blum game. The bot cannot find remain time, so it sleep and claim again in the next few minutes, making a loop while cann't successfully claim game.
![IMG_3220](https://github.com/user-attachments/assets/2744b742-d318-4eb8-bff3-9a90c64b54dc)

**Comment by thebrumby** [comment]
Hi, 

Unfortunately, your screenshot doesn't tell me anything, except it's not working.

Please follow the pinned troubleshooting post about for how to debug or reset your Blum sessions. Blum also needs to built-in proxy to manipulate the headers, kindly follow the instructions in past issues if you're unsure if it's working correctly  https://github.com/thebrumby/HotWalletClaimer/issues/114#issuecomment-2212406196.

**Comment by phamvanhanh6720** [comment]
Hi @thebrumby,
When I check the screenshots, the game isn't launched. So, it results in error I show you above.
![104-iframe-switched](https://github.com/user-attachments/assets/0431a57c-8c6e-451f-82c0-8add5defcd7a)
**Screenshot file name:** 104-iframe-switched

**Comment by thebrumby** [comment]
Hi,

Blum requires the use of built-in proxy to modify the headers. 

Please check in PM2 that “http-proxy” is running. You can always delete it and as described in some closed issues and it will restore itself when Blum launches again.
