### ISSUE TITLE
Hot wallet chrome driver

### ISSUE THREAD

**Issue by Folout8** [thebrumby/HotWalletClaimer#182]
Good afternoon, I have an issue with Hot wallet bot. When I start it i have such error (it is bald)- 
root@foloutvpiska:~/HotWalletBot# ./launch.sh hot
Activating virtual environment...
Running script: ./games/hot.py with arguments:
Initialising the HOT: Wallet Auto-claim Python Script - Good Luck!

Current settings:
forceClaim: False
debugIsOn: False
hideSensitiveInput: True
screenshotQRCode: True
maxSessions: 10
verboseLevel: 2
telegramVerboseLevel: 0
lowestClaimOffset: 0
highestClaimOffset: 15
forceNewSession: False
useProxy: False
proxyAddress: http://127.0.0.1:8080
requestUserAgent: False
telegramBotToken:
telegramBotChatId:

Should we update our settings? (Default:<enter> / Yes = y):
Your session will be prefixed with: HOT:
Enter your unique Session Name here, or hit <enter> for the next sequential wallet: folout
Proxy disabled in settings.
Cookies file not found, using default user agent.
**ChromeDriver not found in PATH. Please ensure it is installed.
Deactivating virtual environment...**

What can I do with it or where I can found that path?

**Comment by thebrumby** [comment]
Hi, 

if you are using the standalone version, run the installer command again and watch for errors.  If it is missing, it should add it for you. 

Alternatively, switch to  using Docker as all the dependencies are pre-built. 

Thanks.

**Comment by thebrumby** [comment]
Hi, 

It seems your Chromedriver installation still has an issue. The standard install code should work fine on Ubuntu 22 & 24. If you aren't familiar with how to set it up, I'd recommend using docker (see [this guide](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/DOCKER.md)).

Setup takes just a few minutes on a VPS to copy the 3 blocks of required commands, and all the dependencies are prebuilt.

<img width="778" alt="image" src="https://github.com/user-attachments/assets/d446cc27-9b18-4b1b-b12a-393f585ef71c">

**Comment by Folout8** [comment]
Thanks, I fixed it alone!
