### ISSUE TITLE
Problems with Log In

### ISSUE THREAD

**Issue by Lavender7faded** [thebrumby/HotWalletClaimer#184]
Hi,
First, I want to thank you for such a wonderful product, it helps me a lot. But today I have a problem.
I'm trying to add a new HOT account, but the script gives an error. Please help me if you can.
![изображение_2024-08-20_152235361](https://github.com/user-attachments/assets/65373c77-2588-4a14-a4ce-2996eaa7f55b)

**Comment by thebrumby** [comment]
Hi,

I believe I have corrected the log-in Xpath. Kindly update your scripts according to your environment and try again.

#### On Docker:
Ensure you are inside the container and run this command:
```
./pull-scripts.sh
```

#### On a stand-alone installation:
Navigate to the **`HotWalletBot`** directory and execute:
```
git pull
```

Please let me know if it works for you. Thanks, Phil.

**Comment by Lavender7faded** [comment]
Hi,
Thank you very much for your help. I tried your method with 
`./pull-scripts.sh`
but it gave an error
![2024 08 20_18-15_cmd_674x418](https://github.com/user-attachments/assets/867f05bc-4e00-4408-89d7-14c8a883cbcd)
then I just restarted the container in the docker and was able to log in to a new account.

**Comment by thebrumby** [comment]
OK great, it also pulls the latest version of the scripts on restart too :)

**Comment by Imaroubat** [comment]
you can delete Fuel game from repo. game dont exist anymore (scam)

**Comment by thebrumby** [comment]
> you can delete Fuel game from repo. game dont exist anymore (scam)

Thanks, I created a 'retired' folder within games and moved it there.
