### ISSUE TITLE
TimeFarm AutoStake issue after update

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#185]
HI a big update recently and timefarm autostake not working right. 
 "STATUS: We still have 5 minutes left to wait - sleeping.
CHROME DRIVER DETACHED: It is now safe to exit the script.
Need to wait until 21 August - 05:55 before the next claim attempt. Approximately 5 minutes."
I't run  and wait 5 minutes to claim.

**Comment by bscongluanbui** [comment]
The Normal timefarm also got issue too.

**Comment by thebrumby** [comment]
Hi,

Yes looks like some bugs have crept in, a new version will be pushed shortly. 

Thanks.

**Comment by thebrumby** [comment]
The new files have been uploaded, if you experience any further problems, please reopen the issue.
