### ISSUE TITLE
Fix no such file or directory when action description contains "/" character

### ISSUE THREAD

**Issue by phamvanhanh6720** [thebrumby/HotWalletClaimer#186]
Hi @thebrumby 
Step 03 - An error occurred: [Errno 2] No such file or directory: './screenshots/Blum:/03_find the chat window/message input box_page_source.html'.

In case of action description contains the "/" character, you should replace '/' by other character when writing to file

**Comment by thebrumby** [comment]
Good spot, I didn't consider this action description could be used later in a filename. I removed the offending character and added a re-sub check. 

I'll update the repository after testing. Thanks.
