### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Frowen07** [thebrumby/HotWalletClaimer#188]
Hi! When you turn on the proxy, the following error appears
![Скриншот 21-08-2024 213805](https://github.com/user-attachments/assets/bd7ae122-9fea-4bbc-9a33-8643e9384cab)

**Comment by thebrumby** [comment]
Hi @Frowen07,

Are you just trying to use the default proxy, or have you tried to configure a third-party tunnel?

**Comment by Frowen07** [comment]
I wanted to install a simple ipv6 proxy, I tried ipv4, but there is always such a problem. Everything works without a proxy

**Comment by thebrumby** [comment]
Maybe a firewall or something blocking the ports?

**Comment by Frowen07** [comment]
nothing is blocked

**Comment by thebrumby** [comment]
Sorry to say, it's blocked, or misconfigured, or so slow the script times out. 

I just created a new Docker instance on AWS and tested it with a paid plan from smartproxy.com and it works fine. If it's timing out, the issue is with your setup.

Did you get the response code 200 after configuration?

<img width="442" alt="image" src="https://github.com/user-attachments/assets/8f3ea888-4bfc-48a4-818d-2c13a1ce8b46">

**Comment by Frowen07** [comment]
![Скриншот 21-08-2024 230342](https://github.com/user-attachments/assets/9a03ed9f-8cef-4fed-9f30-4a81f6568e07)

**Comment by thebrumby** [comment]
It says http-proxy not found, was it not previously running?

**Comment by Frowen07** [comment]
it was previously launched, but an error came out. I reconnected the proxy, but still the same error

**Comment by thebrumby** [comment]
There's not really any more action I can do. If it's working fine for me in Contabo (standalone Ubuntu) and fine for me in AWS (Docker) then everything appears to be working correctly.

Is it a reputable and fast proxy tunnel?

**Comment by Frowen07** [comment]
I used 2 proxies from different services. One is ipv6 and the other is ipv4

**Comment by thebrumby** [comment]
Unfortunately, as I can not recreate it, there is nothing further I can do right now. It's getting late here in Europe, but maybe tomorrow our chief tester @Wellynounet can test it for us and see if he gets any errors.

**Comment by thebrumby** [comment]
Also, I pushed a small update to the repository which you can update with:
```
./pull-scripts.sh
```
The test of the proxy was previously checked for a connection by visiting https://google.co.uk, I changed that to testing with https://web.telegram.org in case that is being blocked by the proxy.

**Comment by thebrumby** [comment]
It's not working for you, it works fine for other people.

**Comment by Frowen07** [comment]
But why doesn't it work with a proxy(

**Comment by thebrumby** [comment]
The question is, why doesn't it work with your proxy. But I have no idea what proxy you're using, what hardware you installed the script on, what firewalls you have in place, or if you configured the script correctly.

The instructions for set-up are [here](https://www.patreon.com/posts/support-added-110409861).

If you have the proxy enabled in your "game" settings with the MITMProxy endpoint of http://127.0.0.1:8080/ and the proxy connection defined and confirmed in the `setup-proxy` script it should work. 

If you REALLY need to use the script with a proxy, then you could edit line 6 in your enable-proxy.py file, and restart the proxy to see if there are clues in your log file why it's not making a connection:

```
log_to_file = False  # Set this to False to log to /dev/null

# Change to

log_to_file = True  # Set this to True to save logs in ./proxy/mitmproxy.log
```
