### ISSUE TITLE
Error whenever im trying to start the bot

### ISSUE THREAD

**Issue by hawryyy30** [thebrumby/HotWalletClaimer#19]
<img width="628" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/106805563/ceff14a1-4c8b-4ff7-8177-660851140133">

I don't really understand why this happens, it happens all the time when i want to use HOT, in mobile and VPS. Im running ubuntu 22.04 x86_64

**Comment by hawryyy30** [comment]
AFAIK, It only happens with HOT

**Comment by thebrumby** [comment]
Hey Harry,

TG changed their end of the login process, which affected the script, although it when unnoticed for 2 days because we save our TG sessions to avoid logging in each time we want to setup a new account! The updated script from two days ago should have fixed :)
