### ISSUE TITLE
Question Change proxy adress

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#196]
Hi I setup proxy address before, Now I want to change the proxy address? How to change it?

**Comment by thebrumby** [comment]
Hi @bscongluanbui,

Did you change the proxy address in the game settings, or using 

```
./launch.sh setup-proxy
```

**Comment by bscongluanbui** [comment]
> Hi @bscongluanbui,
> 
> Did you change the proxy address in the game settings, or using
> 
> ```
> ./launch.sh setup-proxy
> ```

Hi I change proxy in the game setting. ./launch.sh --> and change it by hit Y, but the game bypass it when I press Y

**Comment by thebrumby** [comment]
The message in `./launch.sh setup-proxy` if you already have a proxy configure is:

An upstream proxy is already configured. Enter 'y' to remove it, or press Enter to enter new credentials:

Hitting "y" should have removed your old proxy. You should have hit enter to set new credentials. However, after deleting the old proxy, you should be able to run:

```
./launch.sh setup-proxy
```

And set a new endpoint.

**Comment by bscongluanbui** [comment]
> The message in `./launch.sh setup-proxy` if you already have a proxy configure is:
> 
> An upstream proxy is already configured. Enter 'y' to remove it, or press Enter to enter new credentials:
> 
> Hitting "y" should have removed your old proxy. You should have hit enter to set new credentials. However, after deleting the old proxy, you should be able to run:
> 
> ```
> ./launch.sh setup-proxy
> ```
> 
> And set a new endpoint.

Hi My proxy have no name and password it like http://ulr:port. And when I leave empty user pass, It got error
"Invalid input. Please provide all the necessary details."

**Comment by bscongluanbui** [comment]
> The message in `./launch.sh setup-proxy` if you already have a proxy configure is:
> 
> An upstream proxy is already configured. Enter 'y' to remove it, or press Enter to enter new credentials:
> 
> Hitting "y" should have removed your old proxy. You should have hit enter to set new credentials. However, after deleting the old proxy, you should be able to run:
> 
> ```
> ./launch.sh setup-proxy
> ```
> 
> And set a new endpoint.

Hi I'm using old method proxy in game setting. Not the new proxy method

**Comment by thebrumby** [comment]
> > The message in `./launch.sh setup-proxy` if you already have a proxy configure is:
> > An upstream proxy is already configured. Enter 'y' to remove it, or press Enter to enter new credentials:
> > Hitting "y" should have removed your old proxy. You should have hit enter to set new credentials. However, after deleting the old proxy, you should be able to run:
> > ```
> > ./launch.sh setup-proxy
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And set a new endpoint.
> 
> Hi My proxy have no name and password it like http://ulr:port. And when I leave empty user pass, It got error "Invalid input. Please provide all the necessary details."

If you proxy doesn't require a username and password, and you just type any text for those entries to move on?

**Comment by bscongluanbui** [comment]
> > > The message in `./launch.sh setup-proxy` if you already have a proxy configure is:
> > > An upstream proxy is already configured. Enter 'y' to remove it, or press Enter to enter new credentials:
> > > Hitting "y" should have removed your old proxy. You should have hit enter to set new credentials. However, after deleting the old proxy, you should be able to run:
> > > ```
> > > ./launch.sh setup-proxy
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And set a new endpoint.
> > 
> > 
> > Hi My proxy have no name and password it like http://ulr:port. And when I leave empty user pass, It got error "Invalid input. Please provide all the necessary details."
> 
> If you proxy doesn't require a username and password, can you just type any random text for those entries to move on?

Thank you
