### ISSUE TITLE
tg-bot

### ISSUE THREAD

**Issue by badmosh23** [thebrumby/HotWalletClaimer#197]
sry for my lack of knowledge but i cant get my tg bot to get started its shows me this error every time
![image](https://github.com/user-attachments/assets/6995d9d0-2c27-4cf3-92c3-83b7eea42a62)

**Comment by thebrumby** [comment]
Hi,

You've put your Bot name in the space that says telegramBotToken.

If you go back to the BotFather the token is shown below this line:

Use this token to access the HTTP API:
`**<token>**`
Keep your token secure and store it safely, it can be used by anyone to control your bot.

Once you update this, you'll probably find it works better:)

**Comment by thebrumby** [comment]
> and another question does the blum bot plays game or not its been while but still all ticket are same as before

What tickets?

**Comment by badmosh23** [comment]
> > and another question does the blum bot plays game or not its been while but still all ticket are same as before
> 
> What tickets?

by which we are able to play the game

**Comment by Wellynounet** [comment]
![image](https://github.com/user-attachments/assets/59119913-edcd-46cd-bf73-2678660da768)
 this ?

**Comment by badmosh23** [comment]
> ![image](https://private-user-images.githubusercontent.com/88185485/361248866-59119913-edcd-46cd-bf73-2678660da768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDcyMzgsIm5iZiI6MTcyNDYwNjkzOCwicGF0aCI6Ii84ODE4NTQ4NS8zNjEyNDg4NjYtNTkxMTk5MTMtZWRjZC00NmNkLWJmNzMtMjY3ODY2MGRhNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzI5NmVhN2NiMTc3NTY0ZWEyNTQyNzk0YTkxYmRhNWNhMzU3YzMzMjRlYzI4NzE5ZTNhYjZhNWI0MWZlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsn21ica2YwuOYu7pYmkFRM0e4PCD8tDwLjm57ruybk) this ?

yes

**Comment by badmosh23** [comment]
> Hi,
> 
> You've put your Bot name in the space that says telegramBotToken.
> 
> If you go back to the BotFather the token is shown below this line:
> 
> Use this token to access the HTTP API: **`<token>`** Keep your token secure and store it safely, it can be used by anyone to control your bot.
> 
> Once you update this, you'll probably find it works better:)

![image](https://github.com/user-attachments/assets/334580b5-d357-4a06-84b9-dbd9b8b82d31)
i tried still getting same error

**Comment by Wellynounet** [comment]
> > ![image](https://private-user-images.githubusercontent.com/88185485/361248866-59119913-edcd-46cd-bf73-2678660da768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDcyMzgsIm5iZiI6MTcyNDYwNjkzOCwicGF0aCI6Ii84ODE4NTQ4NS8zNjEyNDg4NjYtNTkxMTk5MTMtZWRjZC00NmNkLWJmNzMtMjY3ODY2MGRhNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzI5NmVhN2NiMTc3NTY0ZWEyNTQyNzk0YTkxYmRhNWNhMzU3YzMzMjRlYzI4NzE5ZTNhYjZhNWI0MWZlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsn21ica2YwuOYu7pYmkFRM0e4PCD8tDwLjm57ruybk) this ?
> 
> yes

personnaly i have like 700 on all of my account maybe blum didnt send anymore the tickets

**Comment by badmosh23** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/88185485/361248866-59119913-edcd-46cd-bf73-2678660da768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDcyMzgsIm5iZiI6MTcyNDYwNjkzOCwicGF0aCI6Ii84ODE4NTQ4NS8zNjEyNDg4NjYtNTkxMTk5MTMtZWRjZC00NmNkLWJmNzMtMjY3ODY2MGRhNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzI5NmVhN2NiMTc3NTY0ZWEyNTQyNzk0YTkxYmRhNWNhMzU3YzMzMjRlYzI4NzE5ZTNhYjZhNWI0MWZlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsn21ica2YwuOYu7pYmkFRM0e4PCD8tDwLjm57ruybk) this ?
> > 
> > yes
> 
> personnaly i have like 700 on all of my account maybe blum didnt send anymore the tickets 

I mean that doesn't the bot automatically use them and collect the points

**Comment by Wellynounet** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/88185485/361248866-59119913-edcd-46cd-bf73-2678660da768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2MDcyMzgsIm5iZiI6MTcyNDYwNjkzOCwicGF0aCI6Ii84ODE4NTQ4NS8zNjEyNDg4NjYtNTkxMTk5MTMtZWRjZC00NmNkLWJmNzMtMjY3ODY2MGRhNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDE3Mjg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YzI5NmVhN2NiMTc3NTY0ZWEyNTQyNzk0YTkxYmRhNWNhMzU3YzMzMjRlYzI4NzE5ZTNhYjZhNWI0MWZlYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bsn21ica2YwuOYu7pYmkFRM0e4PCD8tDwLjm57ruybk) this ?
> > > 
> > > 
> > > yes
> > 
> > 
> > personnaly i have like 700 on all of my account maybe blum didnt send anymore the tickets
> 
> I mean that doesn't the bot automatically use them and collect the points

no

**Comment by thebrumby** [comment]
> > Hi,
> > You've put your Bot name in the space that says telegramBotToken.
> > If you go back to the BotFather the token is shown below this line:
> > Use this token to access the HTTP API: **`<token>`** Keep your token secure and store it safely, it can be used by anyone to control your bot.
> > Once you update this, you'll probably find it works better:)
> 
> [image removed by admin]
> 
> i tried still getting same error

I removed the image as it contains your API key. 

As you can see at the bottom for that image, the message is that Telegram have rejected your API key. Obviously the script can not connect if the key is rejected. Did you follow the rest of the instructions about opening a chat in the Telegram GUI with the bot and sending a message before entering the API Key?

https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/TG-BOT.md

**Comment by badmosh23** [comment]
i got that fixed but when i click status its show error getting information
![image](https://github.com/user-attachments/assets/4d1500a0-9b8b-4642-aae0-dd5547249cfa)

**Comment by thebrumby** [comment]
Hi,

Yes I have this problem with the script too, the games are pushing updates to my bot, but the status etc has stopped working, I need to investigate.

**Comment by thebrumby** [comment]
Hi @badmosh23,

It seems that after the status.py file was updated to collate the profit/hr column for each game (or at least, those games which display that information, it broke the status function of the bot.

Kindly update your code to the latest version:

### On Docker:
Ensure you are inside the container and run this command:
```
./pull-scripts.sh
```

### On a stand-alone installation:
Navigate to the **`HotWalletBot`** directory and execute:
```
git pull
```

And restart the tg-bot:
```
pm2 restart Telegram-Bot
```

And hopefully, when using the **`/start`** command when interacting with the bot, the correct data should now be display.

Thanks for flagging this error.

**Comment by badmosh23** [comment]
thanks a lot this fixed my issue 
When the hot will list i will surely buy you a coffee

**Comment by thebrumby** [comment]
Thanks, @badmosh23! Let's hope we all make a few $$$ for our effort claiming ☕

I might expand the bot functionality to allow for starting and stopping of sessions, in the coming weeks.
