### ISSUE TITLE
Script request for new game

### ISSUE THREAD

**Issue by mesamirh** [thebrumby/HotWalletClaimer#199]
Hello,
please create an automated script for the @LegendsAirDropBot if possible. It offers a $2,000 prize for first place every day.

**Comment by thebrumby** [comment]
Thanks for the recommendation, we'll take a look at the weekend when we look to integrate the next game.

**Comment by thebrumby** [comment]
> Sir please add some bot
> 
> Memefi Tomarket Catizen 🥲please

Hi,

Our target is to add 2 or 3 new games a month, we'll consider these next time we add one.

**Comment by thebrumby** [comment]
> How to host on vps please give a tutorial

[<img width="611" alt="image" src="https://github.com/user-attachments/assets/d3b72f27-cc49-43fa-9dcd-22b368e9664e">](https://www.youtube.com/watch?v=aXwg8U4Qlvc&t=4s)

**Comment by thebrumby** [comment]
> Sir please add some bot
> 
> Memefi Tomarket Catizen 🥲please

@try-to-learn-now 

Do you have the bot IDs for the games you suggested? Scammers often create bots with similar names to genuine projects.

**Comment by thebrumby** [comment]
> Hello, please create an automated script for the @LegendsAirDropBot if possible. It offers a $2,000 prize for first place every day.

Hi,

We have checked out the game, and it's not compatible with this system. Thanks.
