### ISSUE TITLE
Fail All Games

### ISSUE THREAD

**Issue by Jelingam** [thebrumby/HotWalletClaimer#201]
All my games are failing with this error

![image](https://github.com/user-attachments/assets/5d001fac-6c5b-4f9a-a306-f6b52b475851)

**Comment by Jelingam** [comment]
restore previous commit and stop daily-update works for me.

**Comment by Jelingam** [comment]
after restore to previous commit, HOT games still can not claim, this error keeps repeating

![image](https://github.com/user-attachments/assets/abe14b42-f100-4dce-95a1-449899710690)

**Comment by Jelingam** [comment]
another error from another game

![image](https://github.com/user-attachments/assets/1a32844b-ac37-4a2d-848e-26839c1a2c6c)

**Comment by thebrumby** [comment]
Hi,

All games failed because the Telegram session you used to set them up is not longer authenticated. If you look at step 100 they all say the same thing, when visiting web.telegram.org the QR code is showing - this means you got logged out.

**Comment by Jelingam** [comment]
how to fix this problem ?
i think may be this is how :
./launch.sh status -> delete telegram:name
./launch.sh any_game_use_this_telegram_account -> login with qr

this works ?

**Comment by thebrumby** [comment]
Hi @Jelingam,

Yes, that's about it

```
./launch.sh status
```

Then something like this, substituting the Telegram account name for the one that's in error and **ALL** unrecoverable game sessions.
```
delete Telegram:[bad account]
delete Vertus:[crashed account]
```
Then set up the crashed games again from the beginning. For the first game, you will need to authenticate with Telegram again, by scanning the QR code or using country, phone number & one-time password. Provided you select the option to save the Telegram session after authenticating, then for the other game sessions that were lost, you can reuse the Telegram session again.

Once they are all set up, add them to PM2 again (the automated option at the end of creating the game session) and then check the logs to ensure the new session is working OK.

Cheers

**Comment by Jelingam** [comment]
oh my god, it's too long.
this is a good idea: add a new feature to
`./launch.sh status
`
that can be used for delete all games form an account.

**Comment by Jelingam** [comment]
considering that all games are saved with a similar name
for example:
Vertus:Wallet1
Seed:Wallet1
...

the goal is delete all Wallet1 games

**Comment by thebrumby** [comment]
```
delete Wallet1
```

It will pattern match whatever you type, or a comma separated list, or a range, or one-by-one, as stated in the [instructions](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/STATUS.md).

**Comment by Jelingam** [comment]
`delete Wallet1`
its not a pattern
i've got error that say's its not a pattern

**Comment by Jelingam** [comment]
my wallet name is a **number**, and deleting process consider it as **ID**

my wallet is **Telegram:2536**
`delete 2536`
got this error:
`Invalid Process ID`

**Comment by thebrumby** [comment]
```
delete :2536
```
Maybe?

Or just pick the number in the left-hand column

**Comment by Jelingam** [comment]
`delete :2536`

work for me
Tnx
