### ISSUE TITLE
Bug: [HOT issue]

### ISSUE THREAD

**Issue by esckobar** [thebrumby/HotWalletClaimer#207]
Describe the Bug (required):
It's run infinity

Have you followed the https://github.com/thebrumby/HotWalletClaimer/issues/166 (required):
Yes

Steps to Reproduce (required):
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 102 - Backup restored successfully.
Step 102 - Attempting to find the chat window message input box...
Step 102 - Timeout while attempting to find the chat window message input box.
Step 102 - Failed to find the message input box.

Step 102 - Retried after restoring backup, but still failed to send the '/start' command.

Step 103 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app']...
Step 103 - Failed to find the 'Open Wallet' button within the expected timeframe.

Step 104 - Attempting to click the 'Launch' button (probably not present)...
Step 104 - Timeout while attempting to click the 'Launch' button (probably not present).
Step 105 - Attempting to switch to the app's iFrame within 'popup-body'...
Step 105 - Failed to find or switch to the iframe within 'popup-body' within the timeout period.

Step 106 - Found 0 elements with XPath: (//div[div/img[contains(@src, '/ft/near.png')]])//p[last()] for obtain your 'Near' Balance
Step {self.step} - The 'near' variable is empty or not defined.
Step 107 - Attempting to click the 'storage' link...
Step 107 - Timeout while attempting to click the 'storage' link.
Step 108 - Found 0 elements with XPath: //p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p for get balance
Step 109 - Found 0 elements with XPath: //div[div[p[text()='Storage']]]//p[last()] for get profit per hour
Step 109 - An error occurred: expected string or bytes-like object
Step 110 - Found 0 elements with XPath: //div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')] for get the wait time
Error encountered: expected string or bytes-like object
Session released: ./selenium/HOT:wallet.tg

CHROME DRIVER DETACHED: It is now safe to exit the script.
Session released: ./selenium/HOT:wallet.tg
31 August - 10:07 | Need to wait until 31 August - 12:07 before the next claim attempt. Approximately 120 minutes.
[10:07] Waiting for 15 more minutes...

**Comment by thebrumby** [comment]
If

**Comment by bscongluanbui** [comment]
![image](https://github.com/user-attachments/assets/dd70b43f-b0c0-4a93-bf93-9acfd79c55b8)
HI When I add HOT IT's got this error

**Comment by thebrumby** [comment]
Telegram web changed the format for games, you'll need to update your code.

**Comment by bscongluanbui** [comment]
![image](https://github.com/user-attachments/assets/f1397586-efa0-43f6-8060-fa0b6afd33ce)
Hi Hot still got errors

**Comment by thebrumby** [comment]
This error means it did not find the value expected, if the error presists, you need to check your screenshots for this session to find out what the problem is.

**Comment by bscongluanbui** [comment]
Hi when add the HOT, Its stuck on login screen
![image](https://github.com/user-attachments/assets/c17e7559-3970-4c80-beb8-715d7edb2210)
HOT:vina4: Step 102 - Successfully able to open a link for the app..
HOT:vina4: Step 103 - Attempting to click the 'Launch' button (probably not present)...
HOT:vina4: Step 103 - Successfully clicked click the 'Launch' button (probably not present).
HOT:vina4: Step 104 - Attempting to switch to the app's iFrame within 'web-app-body'...
HOT:vina4: Step 104 - Was successfully able to switch to the app's iFrame within 'web-app-body'.
HOT:vina4: Step 105 - Found 0 elements with XPath: (//div[div/img[contains(@src, '/ft/near.png')]])//p[last()] for obtain your 'Near' Balance
HOT:vina4: Step {self.step} - The 'near' variable is empty or not defined.
HOT:vina4: Step 106 - Attempting to click the 'storage' link...
HOT:vina4: Step 106 - Timeout while attempting to click the 'storage' link.
HOT:vina4: Step 107 - Found 0 elements with XPath: //p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p for get balance
HOT:vina4: Step 108 - Found 0 elements with XPath: //div[div[p[text()='Storage']]]//p[last()] for get profit per hour
HOT:vina4: Step 108 - An error occurred: expected string or bytes-like object, got 'bool'
HOT:vina4: Step 109 - Found 0 elements with XPath: //div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')] for get the wait time
HOT:vina4: Error encountered: expected string or bytes-like object, got 'bool'
HOT:vina4: Session released: ./selenium/HOT:vina4
CHROME DRIVER DETACHED: It is now safe to exit the script.

**Comment by thebrumby** [comment]
Thanks, I'll added a work around for requests and will add it to the Docker at some point.

**Comment by farmdigit** [comment]
> Thanks, I'll added a work around for requests and will add it to the Docker at some point.

I have a similar problem. I can't create a single session because I can't go further than the login window in the screenshots.
