### ISSUE TITLE
Bug: Telegram Web Changed the layout

### ISSUE THREAD

**Issue by thebrumby** [thebrumby/HotWalletClaimer#208]
**Describe the Bug (required):**

[www.web.telegram.org](www.web.telegram.org) changed the interface - it now has a tabbed-style view:

<img width="414" alt="image" src="https://github.com/user-attachments/assets/5fe4bedf-91b7-4741-a849-9ae0d0215737">

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**

This originally broke all game. Please follow the instructions to update your local code from the repository, the instructions to do this are in the troubleshooting guide above. If you games sessions do not restart automatically, restart them using PM2.

**Comment by phamvanhanh6720** [comment]
It would be great if you can fix the hot game. Currently we can’t switch to new iframe when click ‘Check News’ button

**Comment by thebrumby** [comment]
Here are my in-game screenshots:

<img width="531" alt="image" src="https://github.com/user-attachments/assets/e0892c59-9902-41be-a185-2ee08c9540b8">

<img width="476" alt="image" src="https://github.com/user-attachments/assets/508855f3-6d32-4579-92b1-ab9eb09e6a8e">

I can't see any problem?

**Comment by thebrumby** [comment]
> It would be great if you can fix the hot game. Currently we can’t switch to new iframe when click ‘Check News’ button

Even something like this would have been helpful:

<img width="580" alt="image" src="https://github.com/user-attachments/assets/384b72ec-0b07-4dc1-bed7-8ad00f3f9535">
