### ISSUE TITLE
Help Me: update if file were changed

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#209]
Hi Phil!
Can you please tell me how to update if I changed the code of one of the files and when I try to update it gives an error as on the screenshot? This error remains even if you manually change the content of the file to what it was.
![image](https://github.com/user-attachments/assets/26a5a2a9-ffa4-48ba-ac99-98e50a71c511)

**Comment by thebrumby** [comment]
Hi @farmdigit 

If you just want to replace your modified version with what's in the repository, probably easiest to delete the amend file and then update:

```
rm games/spell.py
```

**Comment by farmdigit** [comment]
> Hi @farmdigit
> 
> If you just want to replace your modified version with what's in the repository, probably easiest to delete the amend file and then update:
> 
> ```
> rm games/spell.py
> ```

ty vm. I've updated everything, but it looks like the spell wallet is having problems again. Is it something serious? Or am I doing something wrong?

![image](https://github.com/user-attachments/assets/ed1cd3ba-ea20-4041-b35c-2d2a92c67eb1)

**Comment by thebrumby** [comment]
All my bots are working.

**Comment by thebrumby** [comment]
> > Hi @farmdigit
> > If you just want to replace your modified version with what's in the repository, probably easiest to delete the amend file and then update:
> > ```
> > rm games/spell.py
> > ```
> 
> ty vm. I've updated everything, but it looks like the spell wallet is having problems again. Is it something serious? Or am I doing something wrong?
> 
> ![image](https://private-user-images.githubusercontent.com/175704266/363428521-ed1cd3ba-ea20-4041-b35c-2d2a92c67eb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMzI4NjQsIm5iZiI6MTcyNTEzMjU2NCwicGF0aCI6Ii8xNzU3MDQyNjYvMzYzNDI4NTIxLWVkMWNkM2JhLWVhMjAtNDA0MS1iMzVjLTJkMmE5MmM2N2ViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxOTI5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjIwZThjNTJjNDZlNDZjZjU1ZDc3MTdkMzNiOTkyZjQ2NzgxN2ZhYTNhMjE0OGIxOGQ3M2IzNTFlYWJlMTgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_vwipLzefsgQ61Wh1TFSgQdcglBDJD_w_8L0WrF-kA)
> 
> Seems to be due to the telegram update, almost all bots are crashed now. Very huge request - can you fix hot wallet first? This is the coolest project of all available at the moment.

The error says it was looking for a value which wasn't there. As the scripts are working for me, you'll have to check your debugging screenshots and see what's happening at step 108

**Comment by farmdigit** [comment]
> All my bots are working.

Problem with creating new bots where you need to enter seed phrases - the password input window is constantly hanging - the bot can't log in using the seed phrase.. I can send screenshots for hot wallet.

**Comment by farmdigit** [comment]
> The error says it was looking for a value which wasn't there.

Yes, because the bot can't get past the authorization window - it keeps hanging.
