### ISSUE TITLE
Claim HOT Running but claim error

### ISSUE THREAD

**Issue by nthanhtung92** [thebrumby/HotWalletClaimer#21]
Hi,
I run Hot claim but I have issue as below: 
![image](https://github.com/thebrumby/HotWalletClaimer/assets/168674000/ecf3157e-4404-4de6-9ba9-6936ded8b1fd)

**Comment by thebrumby** [comment]
Hi,

 Did you get any errors when trying to connect your telegram app? Every step is failing like your Telegram account is not connected. 

Are you using the docker version? Or stand-alone Ubuntu?

Thanks

**Comment by Wellynounet** [comment]
maybe you have disconnected your last session of TG  and that why the error happend

**Comment by thebrumby** [comment]
Hi, 

I fired up a new instance of Docker and tested the login functionality again, both QR and One-Time Password and I couldn't get an error. 

Are you still having issues with this? and are you able to log into https://web.telegram.org OK?
