### ISSUE TITLE
Bug: [authorization problems in all bots with the seed phrase]

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#210]
**Describe the Bug (required):**
Hi Phil! 
After updating telegram it is impossible to create any bot where you need to authorize with the seed phrase. The authorization window just sticks. This applies to all bots - hotwallet, spellwallet, etc.
As an example, here are screenshots of the process of trying to create a hot session

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Please confirm that you've reviewed the troubleshooting guide linked above and completed all steps to ensure the issue is not with your session. - Yes, I confirm

**Steps to Reproduce (required):**
Creating a new hot wallet session with a new telegram account

**Expected Behavior (required):**
successful authorization in the wallet :)

**Screenshots or Logs:**

![109_MonElem-get-the-wait-time](https://github.com/user-attachments/assets/ddc4c94a-8de6-49cf-a9f9-5391bb7a7deb)

![image](https://github.com/user-attachments/assets/7164ce97-b0f6-479d-8841-5406e5d80841)

**Comment by thebrumby** [comment]
An excellent example of what's needed to help me, help you in the debugging. 

It's all linked to Telegram's changes in their interface. Can you pull the latest updates and try again?

**Comment by kohutiv** [comment]
Hi Phil!
Everything worked! 
Thank you!!!

**Comment by farmdigit** [comment]
> An excellent example of what's needed to help me, help you in the debugging.
> 
> It's all linked to Telegram's changes in their interface. Can you pull the latest updates and try again?

Phil you are great! 
For the first time in 3 weeks created a session hot and spell wallets without problems! And even with the cache disabled! Although I created with debug enabled - I don't know if it will be ok with disabled. This is super! That's great! That's incredible! Thank you so much!!! Just a flurry of emotions after three weeks of all sorts of problems :)

**Comment by thebrumby** [comment]
I'm pleased to hear all is working for you - although I could never recreate the errors you described on my setup but obviously something's working better for you! The caching should be disabled in the program until after the set up, so there's no reason why it shouldn't still work.
