### ISSUE TITLE
Bug: HOT game cannot claim successfully

### ISSUE THREAD

**Issue by howtoprogram** [thebrumby/HotWalletClaimer#211]
**Describe the Bug (required):**
HOT game cannot claim successfully. It seem there is a problem with clicking the Claim button.

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Please confirm that you've reviewed the troubleshooting guide linked above and completed all steps to ensure the issue is not with your session.
Yes. I have pull the latest games and restart pm2 many times

**Steps to Reproduce (required):**
Monitor the logs

**Expected Behavior (required):**
the claimer should claim successfully. 

**Screenshots or Logs:**
HOT:1 | Step 100 - Attempting to verify if we are logged in (hopefully QR code is not present).
HOT:1 | Step 100 - nothing found to action. The QR code test passed.
HOT:1 |
HOT:1 | Step 101 - Attempting to check for the start button (should not be present)...
HOT:1 | Step 101 - Timeout while attempting to check for the start button (should not be present).
HOT:1 | Step 102 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app']...
HOT:1 | Step 102 - Successfully able to open a link for the app..
HOT:1 |
HOT:1 | Step 103 - Attempting to click the 'Launch' button (probably not present)...
HOT:1 | Step 103 - Successfully clicked click the 'Launch' button (probably not present).
HOT:1 | Step 104 - Attempting to switch to the app's iFrame within 'web-app-body'...
HOT:1 | Step 104 - Was successfully able to switch to the app's iFrame within 'web-app-body'.
HOT:1 |
HOT:1 | Step 105 - Found 0 elements with XPath: (//div[div/img[contains(@src, '/ft/near.png')]])//p[last()] for obtain your 'Near' Balance
HOT:1 | Step 105 - Successfully extracted Near balance: 0.3014
HOT:1 | Step 106 - Attempting to click the 'storage' link...
HOT:1 | Step 106 - Element was out of bounds but has been scrolled into view.
HOT:1 | Step 106 - Successfully clicked click the 'storage' link.
HOT:1 | Step 107 - Found 1 elements with XPath: //p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p for get balance
HOT:1 | Step 107 - Before BALANCE: 14.695068
HOT:1 | Step 108 - Found 1 elements with XPath: //div[div[p[text()='Storage']]]//p[last()] for get profit per hour
HOT:1 | Step 108 - Before PROFIT/HOUR: 0.025
HOT:1 | Step 109 - Found 1 elements with XPath: //div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')] for get the wait time
HOT:1 | Step 109 - The pre-claim wait time is : Filled and random offset is 7 minutes.
HOT:1 | Step 110 - Attempting to check for NEWS....
HOT:1 | Step 110 - Removed 3 overlay(s) covering the target.
HOT:1 | Step 110 - Removed 2 overlay(s) covering the target.
HOT:1 | Step 110 - Cleared 2 overlay(s) before attempting click...
HOT:1 | Step 110 - Successfully clicked check for NEWS..
HOT:1 | Step 111 - Attempting to switch to the app's iFrame within 'web-app-body'...
HOT:1 | Step 111 - Was successfully able to switch to the app's iFrame within 'web-app-body'.
HOT:1 |
HOT:1 | Step 112 - Attempting to click the claim button (1st button)...
HOT:1 | Step 112 - Timeout while attempting to click the claim button (1st button).
HOT:1 | Step 113 - Attempting to click the claim button (2nd button - may not be present)...
HOT:1 | Step 113 - Timeout while attempting to click the claim button (2nd button - may not be present).
HOT:1 | Step 114 - Let's wait for the pending Claim spinner to stop spinning...
HOT:1 | Step 114 - Pending action spinner has stopped.
HOT:1 |
HOT:1 | Step 115 - Found 1 elements with XPath: //div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')] for get the wait time
HOT:1 | Step 115 - Random offset applied to the wait timer of: 13 minutes.
HOT:1 | Step 116 - Found 1 elements with XPath: //p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p for get balance
HOT:1 | Step 116 - After BALANCE: 14.695068
HOT:1 | Step 117 - Found 1 elements with XPath: //div[div[p[text()='Storage']]]//p[last()] for get profit per hour
HOT:1 | Step 117 - After PROFIT/HOUR: 0.025
HOT:1 | STATUS: The wait timer is still showing: Filled - claim failed.
HOT:1 | Step 118 - This means either the claim failed, or there is >4 minutes lag in the game.
HOT:1 | Step 118 - We'll check back in 1 hour to see if the claim processed and if not, try again.

**Comment by bscongluanbui** [comment]
Me too. My hot cannot claim

**Comment by thebrumby** [comment]
Hi, 

Telegram has changed the format of their pop-up for games. Everything should be back to normal soon, keep on top of pull updates and retry.

**Comment by bscongluanbui** [comment]
> Hi, 
> 
> 
> 
> Telegram has changed the format of their pop-up for games. Everything should be back to normal soon, keep on top of pull updates and retry.

Thanks for all thing

**Comment by howtoprogram** [comment]
Thanks
