### ISSUE TITLE
Help Me: not solved . How to update?

### ISSUE THREAD

**Issue by Imaroubat** [thebrumby/HotWalletClaimer#213]
I have Docker Desktop running with bots for games. The developer added new games. I updated the repository through git pull in the repository folder located in the home directory. The new games were added to the folder. I stopped Docker and then started it again, but the new games are not available in Docker. I also tried shutting down Docker completely, but it didn’t help.

**Comment by Imaroubat** [comment]
![Screenshot_20240901_150314_TeamViewer](https://github.com/user-attachments/assets/c155a1cc-497f-4cbe-8eea-21be4b350f35)

**Comment by thebrumby** [comment]
In a case where the `pull-games.sh` script is missing or delete, like in your screenshot above, you'd do something like this:

```
curl -o pull-games.sh https://raw.githubusercontent.com/thebrumby/HotWalletClaimer/main/docker/pull-games.sh
chmod +x pull-games.sh
./pull-games.sh
```
