### ISSUE TITLE
NOT A BUG!

### ISSUE THREAD

**Issue by yanpaing007** [thebrumby/HotWalletClaimer#215]
The wait time is always 60 min even if the claim button is available. 
After one hour countdown it would go to another hour countdown and so on countlessly.
I try to delete old one and added new but still not working.
Tried restarting process.
This is the full logs from blum
<img width="973" alt="Screenshot 2024-09-05 at 2 28 44 AM" src="https://github.com/user-attachments/assets/b6084282-1f2d-4d11-843d-5847df5bef21">

**Comment by thebrumby** [comment]
Hi,

As described in the troubleshooting guide, you need to enable the debugging screenshots and find out what's blocking you. If there is only Telegram content and not the Blum game. Make sure the built-in proxy is running as this is required by default on Blum.

**Comment by yanpaing007** [comment]
Hi,I found your old comment on issues and the problem was solved.I need to delete http built in proxy and need to re-run blum.The issue I found on debugging photo was it was able to load blum bot frame but afterward no content loaded and everything is black that why error.Thanks alot!
<img width="1056" alt="image" src="https://github.com/user-attachments/assets/96fc9a6d-0de9-456d-bd3e-5d0a7d3d0dc4">

**Comment by yanpaing007** [comment]
Problem solved!

**Comment by thebrumby** [comment]
Pleased to hear you got sorted, I also added some more information to the troubleshooting guide :)
