### ISSUE TITLE
Using proxy feature 

### ISSUE THREAD

**Issue by Krokodile228** [thebrumby/HotWalletClaimer#222]
Hey Phil! There is one problem with using ur script  with proxies... When I setup it I can't login to tg account/ no generating qr-code for logging and etc
![tr](https://github.com/user-attachments/assets/2fe5a805-18c6-4135-9583-0322a4cca88c)
How to solve it? Need make many sessions with different proxy

**Comment by thebrumby** [comment]
Hi,

Looks like you don't have a connection, everything's timing out.

**Comment by Krokodile228** [comment]
![1f](https://github.com/user-attachments/assets/3aa9df7d-641b-4442-ad05-34b0058dc3fb)
![2s](https://github.com/user-attachments/assets/ff534759-bb15-455d-ba74-38759d3b1130)
![3tt](https://github.com/user-attachments/assets/543d36d2-6d18-473e-ad78-b88f7e0fd843)
 Hmm idk showing online in pm2 and this proxy is working rn(checked in browser) 
 type of this proxy HTTP mb in that problem?

**Comment by thebrumby** [comment]
I’ll look at add some more error checking to the proxy set up. In the coming days. In the short term, you could enable debugging screenshots and see what’s happening when you try to set up an account.

**Comment by Krokodile228** [comment]
Where can I find these screenshots?

**Comment by bscongluanbui** [comment]
I have the same problem with him. But phil said because of quality of proxy. When I tried change https to http in the file setupproxy.py It’ working, like another topic talking about that

**Comment by Krokodile228** [comment]
> I have the same problem with him. But phil said because of quality of proxy. When I tried change https to http in the file setupproxy.py It’ working, like another topic talking about that

ow what exactly did u change?

**Comment by bscongluanbui** [comment]
> > I have the same problem with him. But phil said because of quality of proxy. When I tried change https to http in the file setupproxy.py It’ working, like another topic talking about that
> 
> ![image](https://private-user-images.githubusercontent.com/181295105/366961788-5b85aea9-47cb-46ca-8313-bd6bc289b40f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTY4OTgsIm5iZiI6MTcyNjE1NjU5OCwicGF0aCI6Ii8xODEyOTUxMDUvMzY2OTYxNzg4LTViODVhZWE5LTQ3Y2ItNDZjYS04MzEzLWJkNmJjMjg5YjQwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTBmMGVjYjNmMzY3ZDlkOTJiN2ZkM2IxZWFlYzQxYTYxNDcwNTljOWNkNTNkYTFmMjMwYzUyNTUxYzk2ZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eufRAWi2Y5b_oWYeQwy6DkYpeb6F66PW01zJyxhsxG0)

Yes change this https in this line

**Comment by Krokodile228** [comment]
> > > I have the same problem with him. But phil said because of quality of proxy. When I tried change https to http in the file setupproxy.py It’ working, like another topic talking about that
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/181295105/366961788-5b85aea9-47cb-46ca-8313-bd6bc289b40f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTY4OTgsIm5iZiI6MTcyNjE1NjU5OCwicGF0aCI6Ii8xODEyOTUxMDUvMzY2OTYxNzg4LTViODVhZWE5LTQ3Y2ItNDZjYS04MzEzLWJkNmJjMjg5YjQwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTBmMGVjYjNmMzY3ZDlkOTJiN2ZkM2IxZWFlYzQxYTYxNDcwNTljOWNkNTNkYTFmMjMwYzUyNTUxYzk2ZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eufRAWi2Y5b_oWYeQwy6DkYpeb6F66PW01zJyxhsxG0)
> 
> Yes change this https in this line

![image](https://github.com/user-attachments/assets/4b958b7c-c874-469c-9b93-f19c2bf8dbb4)
![image](https://github.com/user-attachments/assets/0512b8e4-7444-47e8-8208-ee9d39f15871)

anyway cant even join on telegram acc

**Comment by thebrumby** [comment]
> > > I have the same problem with him. But phil said because of quality of proxy. When I tried change https to http in the file setupproxy.py It’ working, like another topic talking about that
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/181295105/366961788-5b85aea9-47cb-46ca-8313-bd6bc289b40f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTY4OTgsIm5iZiI6MTcyNjE1NjU5OCwicGF0aCI6Ii8xODEyOTUxMDUvMzY2OTYxNzg4LTViODVhZWE5LTQ3Y2ItNDZjYS04MzEzLWJkNmJjMjg5YjQwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTU2MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTBmMGVjYjNmMzY3ZDlkOTJiN2ZkM2IxZWFlYzQxYTYxNDcwNTljOWNkNTNkYTFmMjMwYzUyNTUxYzk2ZWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eufRAWi2Y5b_oWYeQwy6DkYpeb6F66PW01zJyxhsxG0)
> 
> Yes change this https in this line

This is correct, if a proxy doesn't support a secure connection for authentication, and you are OK sending your authentication credentials on an unencrypted connection, you could remove the "s", but your username and password will be viewable by every relay between the script and your VPN host.

**Comment by thebrumby** [comment]
<img width="471" alt="image" src="https://github.com/user-attachments/assets/e65e92a1-5b7f-4535-8045-16afec8089dd">

It looks like you have an error here.

**Comment by thebrumby** [comment]
Here are some instructions to try to manually install the mitmproxy-ca-cert.pem on Ubuntu:

# Manually Installing mitmproxy Certificate on Ubuntu

Follow these steps to manually install the `mitmproxy` certificate on Ubuntu.

### Step 1: Install `mitmproxy`
First, update your package list and install `mitmproxy` using pip:

```
sudo apt update
source venv/bin/activate
pip3 install mitmproxy  # Install mitmproxy if not already installed
```

### Step 2: Generate Certificates by Running mitmproxy
Running `mitmproxy` for the first time will generate the necessary SSL certificates:

```
mitmproxy --install
```

This command will generate the required `mitmproxy-ca-cert.pem` file in your `~/.mitmproxy/` directory.

### Step 3: Locate the Certificate
Verify that the certificate has been generated:

```
ls ~/.mitmproxy/
```

You should see `mitmproxy-ca-cert.pem` in the list of files.

### Step 4: Copy Certificate to System Trust Store
To make the certificate trusted system-wide, copy it to the appropriate directory and update the system’s certificates.

1. Copy the certificate to `/usr/local/share/ca-certificates/`:

```
sudo cp ~/.mitmproxy/mitmproxy-ca-cert.pem /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
```

2. Update the system's CA certificates:

```
sudo update-ca-certificates
```

This command updates the system’s trusted certificates, making the `mitmproxy` CA certificate trusted. If successful, you should see a message like:

Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.


### Step 5: Verify Installation
Check the list of trusted certificates to ensure the `mitmproxy` certificate is now trusted:

```
ls /etc/ssl/certs | grep mitmproxy
```

### Step 6: Restart Services (If Necessary)
Some services may require a restart to pick up the new certificate. For example, restart your browser or any service that uses SSL certificates.

### Troubleshooting:
- **File permissions issue**: If the certificate isn’t being recognized, ensure that the permissions on the file are correct:

```
sudo chmod 644 /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
```

- **Reinstall the certificate**: If something goes wrong, delete the certificate and regenerate it by rerunning `mitmproxy`:

```
rm ~/.mitmproxy/mitmproxy-ca-cert.pem
mitmproxy --install
```

This will regenerate the `mitmproxy-ca-cert.pem` file.

## Finally...
Quit the virtual environment:
```
deactivate
```

**Comment by thebrumby** [comment]
Once you've been able to confirm the certificate is installed, if you need to reinstall the proxy, the instructions are [here](https://github.com/thebrumby/HotWalletClaimer/issues/166).

**Comment by bscongluanbui** [comment]
> Once you've been able to confirm the certificate is installed, if you need to reinstall the proxy, the instructions are [here](https://github.com/thebrumby/HotWalletClaimer/issues/166).

Hi I must install on docker or ubuntu system?

**Comment by thebrumby** [comment]
> > Once you've been able to confirm the certificate is installed, if you need to reinstall the proxy, the instructions are [here](https://github.com/thebrumby/HotWalletClaimer/issues/166).
> 
> Hi I must install on docker or ubuntu system?

If you think the certificate  is not installed on your system too, you'd run these commands inside the Docker container:

### Step 1: Install `mitmproxy`
First, update your package list and install `mitmproxy` using pip:

```
sudo apt update
source venv/bin/activate
pip3 install mitmproxy  # Install mitmproxy if not already installed
```

### Step 2: Generate Certificates by Running mitmproxy
Running `mitmproxy` for the first time will generate the necessary SSL certificates:

```
mitmproxy --install
```

This command will generate the required `mitmproxy-ca-cert.pem` file in your `~/.mitmproxy/` directory.

### Step 3: Locate the Certificate
Verify that the certificate has been generated:

```
ls ~/.mitmproxy/
```

You should see `mitmproxy-ca-cert.pem` in the list of files.

### Step 4: Copy Certificate to System Trust Store
To make the certificate trusted system-wide, copy it to the appropriate directory and update the system’s certificates.

1. Copy the certificate to `/usr/local/share/ca-certificates/`:

```
sudo cp ~/.mitmproxy/mitmproxy-ca-cert.pem /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
```

2. Update the system's CA certificates:

```
sudo update-ca-certificates
```

This command updates the system’s trusted certificates, making the `mitmproxy` CA certificate trusted. If successful, you should see a message like:

Updating certificates in /etc/ssl/certs... 1 added, 0 removed; done.


### Step 5: Verify Installation
Check the list of trusted certificates to ensure the `mitmproxy` certificate is now trusted:

```
ls /etc/ssl/certs | grep mitmproxy
```

### Step 6: Restart Services (If Necessary)
Some services may require a restart to pick up the new certificate. For example, restart your browser or any service that uses SSL certificates.

### Troubleshooting:
- **File permissions issue**: If the certificate isn’t being recognized, ensure that the permissions on the file are correct:

```
sudo chmod 644 /usr/local/share/ca-certificates/mitmproxy-ca-cert.crt
```

- **Reinstall the certificate**: If something goes wrong, delete the certificate and regenerate it by rerunning `mitmproxy`:

```
rm ~/.mitmproxy/mitmproxy-ca-cert.pem
mitmproxy --install
```

This will regenerate the `mitmproxy-ca-cert.pem` file.

## Finally...
Quit the virtual environment:
```
deactivate
```
