### ISSUE TITLE
Bug: [Bug creating Hot wallet session]

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#223]
**Describe the Bug (required):**
Hi Phil! Thank you for everything you do.
There is a new problem with creating sessions in the hot wallet. When trying to create a session, an error occurs as on the screenshot. The screenshots show that the screen is stuck in one place and can't start the application. Perhaps the error is related to some next changes in Telegram, or the wallet itself has changed something. Please see what's wrong.

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Yes, I confirm.

**Steps to Reproduce (required):**
Creating a new session hot wallet

**Expected Behavior (required):**
Successful session creation

**Screenshots or Logs:**
logs:
![image](https://github.com/user-attachments/assets/2b3706c7-38f6-4361-850b-bd638b12eedc)

screenshots:
![13_timeout-while-trying-to-open-the-game](https://github.com/user-attachments/assets/5d632da4-cb46-4902-87f6-9ba7ee616284)

**Comment by thebrumby** [comment]
As you will have seen in the troubleshooting guide you need to try the following steps one at a time. 

- Enable debugging screenshots to see if there is somewhere the process is stuck
- If you can't explain it, delete the GUI chat with the herewalletbot for the Telegram account thats stuck
- Delete the saved TG account and try again from the beginning.

**Comment by farmdigit** [comment]
> Hi,
> 
> which step is that a screenshot of? I created a nee account this morning and it worked fine for me?

all of this steps
![image](https://github.com/user-attachments/assets/097c1beb-7efc-4cd1-ae78-1e8808cd57e0)

**Comment by farmdigit** [comment]
> I created a nee account this morning

Just in case you don't know - there are 2 promotions going on there right now - a #gra-gra token from mempad on bnb and a #free token. You can do simple tasks all accounts to get maybe a good airdrop soon.

**Comment by thebrumby** [comment]
OK, I think I understand the issue now:

<img width="369" alt="image" src="https://github.com/user-attachments/assets/8cc74bf8-7d85-418b-8cf2-0844054957bd">

The script looks for this "Open Wallet" link in the chat with the bot and clicks it. For anyone who has an existing chat, that was working fine. But it seems now the HOT devs have changed their welcome message which no longer includes the original link. 

```
./pull-games.sh
```

If you update your repository and try again, it should now match both the new method and old.

Let me know how you get on.

**Comment by farmdigit** [comment]
> OK, I think I understand the issue now:
> 
> <img alt="image" width="369" src="https://private-user-images.githubusercontent.com/29182343/366988226-8cc74bf8-7d85-418b-8cf2-0844054957bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjMyNzksIm5iZiI6MTcyNjE2Mjk3OSwicGF0aCI6Ii8yOTE4MjM0My8zNjY5ODgyMjYtOGNjNzRiZjgtN2Q4NS00MThiLThjZjItMDg0NDA1NDk1N2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDE3NDI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyODI2MjhjMDliODJhYWMxZjZiNWExNzQ5MmRiZWNhMjE5OWI1YzZmZmNlYjY2OWZkYzJkYjhkMDA1YzU3MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kMo2-cFqYyA8JD1OUIG1pLqiAuNGaw5Y80DpdqvuyoM">
> The script looks for this "Open Wallet" link in the chat with the bot and clicks it. For anyone who has an existing chat, that was working fine. But it seems now the HOT devs have changed their welcome message which no longer includes the original link.
> 
> ```
> ./pull-games.sh
> ```
> 
> If you update your repository and try again, it should now match both the new method and old.
> 
> Let me know how you get on.

Yeah, sure, TY. I'll try the updated version and report back a little later. By the way, why does the hot start before the waiting time? Very often I see messages like on the screenshot:
![image](https://github.com/user-attachments/assets/b38e0373-9e69-45d1-894d-c76565712a01)

**Comment by thebrumby** [comment]
> Yeah, sure, TY. I'll try the updated version and report back a little later. By the way, why does the hot start before the waiting time? Very often I see messages like on the screenshot: !

Hi,

the script converts time, eg 21h 29m into minutes (1289 minutes) and then will apply a random offset based on the two random offset limits in your settings. If you don’t want early claims, ensure they are both equal to or greater than 0. If you don’t want any random offset, just make them both zero. 

If you don’t want any offset, set them both to zero, although I’d see that as suspicious if I was a game dev.

**Comment by farmdigit** [comment]
> > Yeah, sure, TY. I'll try the updated version and report back a little later. By the way, why does the hot start before the waiting time? Very often I see messages like on the screenshot: !
> 
> Hi,
> 
> the script converts time, eg 21h 29m into minutes (1289 minutes) and then will apply a random offset based on the two random offset limits in your settings. If you don’t want early claims, ensure they are both equal to or greater than 0. If you don’t want any random offset, just make them both zero.
> 
> If you don’t want any offset, set them both to zero, although I’d see that as suspicious if I was a game dev.

Hi Phil!
If I run this command: "pm2 stop /Hot/" will it stop all sessions temporarily?
I can start them later with the command: "pm2 restart /Hot/"?
because I still can't check the update - after the update I have sessions hot running all the time, even though they occupy threads. I haven't figured out exactly what the cause of this behavior is.

**Comment by thebrumby** [comment]
> If I run this command: "pm2 stop /Hot/" will it stop all sessions hot temporarily?

It probably has to be capital letters for HOT: But, yes it will.
```
pm2 stop /HOT:/
```
> Can I start them later with the command: "pm2 restart /Hot/"? 

Also yes :)
```
pm2 restart /HOT:/
```

**Comment by farmdigit** [comment]
> Such sessions are only sleeping, for want of a better word, not deleted

That's exactly what I need. Thanks! I stopped all sessions and finally run the update check - now registers a new session with no problems - thanks Phil for your promptness - as always you quickly realized what the cause was and solved the problem - that's amazing. This problem is completely solved. U're best!
Now I just need to figure out why the hot sessions are starting earlier than they should on the timer.

**Comment by farmdigit** [comment]
> If you don’t want early claims, ensure they are both equal to or greater than 0
I have just such settings, but for some reason claimes happen before the timer.
![image](https://github.com/user-attachments/assets/edda4d5a-9c8b-457c-a522-ae6f3a4b931f)

**Comment by thebrumby** [comment]
Hey @farmdigit,

I'm going to do some work in the coming days, but if you want to enable verbose level 3 in settings, I added some additional diagnostic text to try and see better what's happening:
```
67|HOT:Phil  | Step 109 - Found 1 elements with XPath: //div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')] for get the wait time
67|HOT:Phil  | Step 109 - Picking a random offset between -15 and 15 minutes.
67|HOT:Phil  | Step 109 - Random offset applied the random offset of: 7 minutes to original time of 343.0 minutes.
67|HOT:Phil  | Step 109 - Returned modified timer: 350.0 minutes (5 hours 50 minutes).
67|HOT:Phil  | STATUS: Original wait time 5h 43m to fill - 343 minutes, We'll sleep for 350 minutes after random offset.
```

It still needs some tidying up, and standardising between games, but in the second line we can see my lower and higher offsets. Next line, it picked a value of +7 minutes (within -15 to +15) which it added to the original timer of 343 minutes. The function returned a value of 350 minutes (343 + 7) and the counter function acknowledged it will sleep for 350 minutes.

Hopefully, that will help!
