### ISSUE TITLE
Bug: No Python scripts found in the current directory or ./games directory.

### ISSUE THREAD

**Issue by Rohan7559** [thebrumby/HotWalletClaimer#224]
![IMG_20240913_163100](https://github.com/user-attachments/assets/b65c14b2-4338-4c53-af80-cd3e3e9da5a1)

Plz help me to solve out this err. Plz also explain how i can remove/delete and reinstall new one

Some more details:
Using VPS, Docker.....

**Comment by thebrumby** [comment]
Hi,

What are your steps before this point? On both ARM64 and AMD64 installations on VPS I can’t create this.

**Comment by thebrumby** [comment]
All the commands to delete and setup a new Docker container are in the [documentation](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/DOCKER.md).

**Comment by Rohan7559** [comment]
> Hi,
> 
> What are your steps before this point? On both ARM64 and AMD64 installations on VPS I can’t create this.

Steps/Cmds you maintained:

1. docker run -d --name telegram-claim-bot --restart unless-stopped thebrumby/telegram-claim-bot

2. docker exec -it telegram-claim-bot /bin/bash

3. ./launch.sh

**Comment by thebrumby** [comment]
So, what happens if, from outside the container you run these steps?

### Step 1 - delete the existing container:

```
docker stop telegram-claim-bot
docker rm telegram-claim-bot
```

### Step 2 - create a new container and switch into it:

```
docker run -d --name telegram-claim-bot --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it telegram-claim-bot /bin/bash
```

### Step 3 - verify the process is working:

```
ls games/
pm2 list
pm2 logs 0
```

**Comment by thebrumby** [comment]
> ![IMG_20240913_163100](https://private-user-images.githubusercontent.com/130834428/367267045-b65c14b2-4338-4c53-af80-cd3e3e9da5a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMzg5MzQsIm5iZiI6MTcyNjIzODYzNCwicGF0aCI6Ii8xMzA4MzQ0MjgvMzY3MjY3MDQ1LWI2NWMxNGIyLTQzMzgtNGM1My1hZjgwLWNkM2UzZTlkYTVhMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QxNDQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDAzNGMzODFiYTg1ZmZlNzVhZWRlMzJlMjE0ZDdhMzVlN2IxMTBkMzVhNTRhOGQ4ZjI3NzlkZmE0MmM1ZGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RN1FK_QI6X_5u9C8y93k_Cy5I9CvFYoN6HS-DgOdVxY)
> 
> Plz help me to solve out this err. Plz also explain how i can remove/delete and reinstall new one
> 
> Some more details: Using VPS, Docker.....

Oh wait, on taking a closer look, it looks like you have some kind of network error/DNS issue - "Fatal: unable to access 9github0: Could not resolve host"

**Comment by Rohan7559** [comment]
> So, what happens if you run these steps from outside the container?
> 
> ### Step 1 - delete the existing container:
> ```
> docker stop telegram-claim-bot
> docker rm telegram-claim-bot
> ```
> 
> ### Step 2 - create a new container and switch into it:
> ```
> docker run -d --name telegram-claim-bot --restart unless-stopped thebrumby/telegram-claim-bot:latest
> docker exec -it telegram-claim-bot /bin/bash
> ```
> 
> ### Step 3 - verify the process is working:
> ```
> ls games/
> pm2 list
> pm2 logs 0
> ```


![Screenshot_2024-09-13-20-22-34-601_com server auditor ssh client-edit](https://github.com/user-attachments/assets/090a7630-cddd-49c8-bcfe-4e4ec8940180)

![Screenshot_2024-09-13-20-23-46-003_com server auditor ssh client-edit](https://github.com/user-attachments/assets/c1b90022-ea46-408e-b0c0-942d05375ad0)

**Comment by thebrumby** [comment]
Ok - same problem then. You have network problems and can’t connect to Github.

**Comment by thebrumby** [comment]
From outside the container, maybe you can try:

### Check your current DNS config
```
docker exec -it telegram-claim-bot cat /etc/resolv.conf
```
### Consider updating the DNS to be Google
```
sudo nano /etc/docker/daemon.json
```

Add this line:
```
{ "dns": ["8.8.8.8", "8.8.4.4"] }
```
Save the file in nano:

- Press `Ctrl + O` to write the changes.
- Press `Enter` to confirm the filename.
- Press `Ctrl + X` to exit.

Restart Docker:
```
sudo systemctl restart docker
```

You can then try going back into the container and trying again, or start with a new container and see if the DNS issues persist.

**Comment by Rohan7559** [comment]
> From outside the container, maybe you can try:
> 
> ### Check your current DNS config
> ```
> docker exec -it telegram-claim-bot cat /etc/resolv.conf
> ```
> 
> ### Consider updating the DNS to be Google
> Install `nano` if it's missing:
> 
> ```
> sudo apt update && sudo apt install nano
> ```
> 
> Use `nano` to create/edit the Docker Daemon file:
> 
> ```
> sudo nano /etc/docker/daemon.json
> ```
> 
> Add this line:
> 
> ```
> { "dns": ["8.8.8.8", "8.8.4.4"] }
> ```
> 
> Save the file in nano:
> 
> * Press `Ctrl + O` to write the changes.
> * Press `Enter` to confirm the filename.
> * Press `Ctrl + X` to exit.
> 
> Restart Docker:
> 
> ```
> sudo systemctl restart docker
> ```
> 
> You can then try going back into the container and trying again, or start with a new container and see if the DNS issues persist.

Sir, still get the same err's

**Comment by thebrumby** [comment]
OK, 

Until you resolve the connectivity issues, the script won't work. Not being able to access GitHub on the internet is definitely a show-stopper. 

I've reopened [this issue](https://github.com/thebrumby/HotWalletClaimer/issues/31) and reached out to the original poster to see if they can remember how they solved it. You'll also see some advice/instructions there about checking firewall ports and how to install ping to test if you can connect to GitHub using ping.

**Comment by thebrumby** [comment]
Our user from the other post said they have to create a container using CLoudFlare's public DNS resolver. I think it's pretty much the same solution as we tried by using Google's DNS resolver, but maybe it's worth  a try:

```
docker stop telegram-claim-bot
docker rm telegram-claim-bot
docker run -d -t --name telegram-claim-bot --dns="1.1.1.1" --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it telegram-claim-bot /bin/bash
```

**Comment by Rohan7559** [comment]
> Our user from the other post said they had to create a container using CloudFlare's public DNS resolver. I think it's pretty much the same solution as we tried by using Google's DNS resolver, but maybe it's worth a try:
> 
> ```
> docker stop telegram-claim-bot
> docker rm telegram-claim-bot
> docker run -d -t --name telegram-claim-bot --dns="1.1.1.1" --restart unless-stopped thebrumby/telegram-claim-bot:latest
> docker exec -it telegram-claim-bot /bin/bash
> ```

In past, I was installed one script "https://github.com/DindaPutriFN/Autoscript" so maybe err from this repo/script. But now, I don't know how to remove/delete it (This script related to dns,web socket, cloudflare, ssh....)

**Comment by thebrumby** [comment]
If you don’t have anything else that you want to keep on the VPS, maybe you can reinstall in via the hosting companies website? Ubuntu 22 or 24 would be very compatible.

**Comment by Rohan7559** [comment]
> If you don’t have anything else that you want to keep on the VPS, maybe you can reinstall in via the hosting companies website? Ubuntu 22 or 24 would be very compatible.

I don't have VPS panel/account access, There is no way to remove/delete it from my system ?

**Comment by thebrumby** [comment]
> In past, I was installed one script "https://github.com/DindaPutriFN/Autoscript" so maybe err from this repo/script. But now, I don't know how to remove/delete it (This script related to dns,web socket, cloudflare, ssh....)

I looked into the script you mentioned from [this repository](https://github.com/DindaPutriFN/Autoscript), specifically the `setup.sh` file available [here](https://github.com/DindaPutriFN/Autoscript/releases/download/1.10/setup.sh). I noticed that much of the script is encrypted, which unfortunately makes it difficult to determine exactly what changes it has made to your system.

Because the script's content isn't fully transparent, it's challenging to provide specific steps to remove or reverse any modifications it may have implemented, especially regarding DNS settings, web sockets, Cloudflare configurations, or SSH.

If you're experiencing issues that might be related to this script and are unsure how to proceed, my recommendation is still to reimage your VPS to restore it to its original state. This would effectively remove any changes made by the script. You mention that don't have access to a self-service portal to perform a reimage, therefore you'd have to raise a support ticket with your hosting provider's support team to request their assistance.

If you have a normally functioning VPS with correctly configured internet access, firewall, and DNS, then my script will work just fine. Unfortunately, if this previously installed script has made changes to the default networking setting, and it can't contact GitHub, then if won't work at all.

**Comment by Rohan7559** [comment]
> > In past, I was installed one script "https://github.com/DindaPutriFN/Autoscript" so maybe err from this repo/script. But now, I don't know how to remove/delete it (This script related to dns,web socket, cloudflare, ssh....)
> 
> I looked into the script you mentioned from [this repository](https://github.com/DindaPutriFN/Autoscript), specifically the `setup.sh` file available [here](https://github.com/DindaPutriFN/Autoscript/releases/download/1.10/setup.sh). I noticed that much of the script is encrypted, which unfortunately makes it difficult to determine exactly what changes it has made to your system.
> 
> Because the script's content isn't fully transparent, it's challenging to provide specific steps to remove or reverse any modifications it may have implemented, especially regarding DNS settings, web sockets, Cloudflare configurations, or SSH.
> 
> If you're experiencing issues that might be related to this script and are unsure how to proceed, my recommendation is still to reimage your VPS to restore it to its original state. This would effectively remove any changes made by the script. You mention that don't have access to a self-service portal to perform a reimage, therefore you'd have to raise a support ticket with your hosting provider's support team to request their assistance.
> 
> If you have a normally functioning VPS with correctly configured internet access, firewall, and DNS, then my script will work just fine. Unfortunately, if this previously installed script has made changes to the default networking setting, and it can't contact GitHub, then if won't work at all.

Hmm, its better should i buy a new VPS for your script. so, i am going with cheap VPS that cost's 3 dollar per month. so before purchasing this new VPS, can you please tell me what minimum requirements for your script like ram, core, ssd, bandwidth, specially bandwidth. 

Normally I go with Ultahost but this one little cheap 😅
(www.interserver.net/vps)

**Comment by thebrumby** [comment]
The minimum spec is determined by how many sessions you intend to run:

https://github.com/thebrumby/HotWalletClaimer#general-instructions

35 MB RAM per session plus 450 MB if you only intended to claim one session at a time and let the others queue. Up to 400 Mb disk space per session unless you disable caching. There is a table of some examples to act as a guide.

**Comment by thebrumby** [comment]
The $3 a-month server will probably work for 10 game sessions in total, with only 1 active claim at a time. The $6 a month could maybe do 20-30 total sessions, with 1 claim at a time, or 12 total sessions with 2 claims at any time.
