### ISSUE TITLE
Feature Request: Please also add more hosting platform's 

### ISSUE THREAD

**Issue by Rohan7559** [thebrumby/HotWalletClaimer#225]
1. Heroku
2. Render
3. Railway
4. Koyeb

One more xtra feature 😅
Make your script like that, user's can access/control entire script from a telegram bot (For all task). Means we just have to deploy a telegram bot. Using above hosting platform's.

**Comment by thebrumby** [comment]
Hi,

Thanks for the suggestion, but its probably not going to happen anytime soon. The project already takes  100 hours a month to maintain so adding functionality that I won’t use myself isn't high on the list of priorities.

**Comment by Rohan7559** [comment]
> Hi,
> 
> Thanks for the suggestion, but its probably not going to happen anytime soon. The project already takes 100 hours a month to maintain so adding functionality that I won’t use myself isn't high on the list of priorities.

I am requesting one of the platforms that's mentioned above because this service is free of charge. 

It's okay for now; currently I have had VPS for 2 months... 

Well, currently I am not able to use it; get one error, already reported to you.

And,
Thank you so much, sir, for this amazing script and for your great hard work. Love from India ❤️

**Comment by thebrumby** [comment]
OK, I understand. Can you avail the free 12-month AWS trial in India? Unfortunately, it requires a credit card.

**Comment by Rohan7559** [comment]
> OK, I understand. Can you avail the free 12-month AWS trial in India? Unfortunately, it requires a credit card.

Today I claimed AWS free trial for 12 months, but it have only one free tire [1 GB ram, 1 core, 30 GB SSD] and is not enough for your script 😔

**Comment by thebrumby** [comment]
<img width="571" alt="image" src="https://github.com/user-attachments/assets/95ab4945-fec9-4c22-a4b1-e7a75ff250df">

Have you tried selecting the ARM64 architecture? The Chrome browser version is pegged at version 118, which uses less memory than recent versions. You should be able to set up around 8 session, free for 12 months.

**Comment by Rohan7559** [comment]
> <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/29182343/372476791-95ab4945-fec9-4c22-a4b1-e7a75ff250df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MTEwNDksIm5iZiI6MTcyNzgxMDc0OSwicGF0aCI6Ii8yOTE4MjM0My8zNzI0NzY3OTEtOTVhYjQ5NDUtZmVjOS00YzIyLWE0YjEtZTdhNzVmZjI1MGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE5MjU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMDczM2U1MWU4NTg3MjM3M2I2YjgxODgxZGRlYTU0ZTRjNTBkMTM2NGU4ZjVlZDY4YTYyNTYxODFlMGEwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O-YynGcndjZxieWQJlwU5pYZMMr2XNytKh3Sj33aJTA">
> Have you tried selecting the ARM64 architecture? The Chrome browser version is pegged at version 118, which uses less memory than recent versions. You should be able to set up around 8 session, free for 12 months.

Ok sir, let me try 😌
