### ISSUE TITLE
Bug: [Seed update]

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#231]
**Describe the Bug (required):**
Seed update with the new interface and the tool cannot claim

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
yes

**Comment by Jelingam** [comment]
Seed UI change completely, a hole new upgrade

**Comment by thebrumby** [comment]
@bscongluanbui & @Jelingam,

Thanks for the heads up, I hadn't seen that. 

I've pushed an update to the code, which now logs in correctly and appears to claim the standard reward and daily claim bonus, we'll have to monitor things like the worm, egg etc to ensure they claim correctly. 

Cheers

**Comment by wordfangsss** [comment]
![image](https://github.com/user-attachments/assets/d77c3977-d591-431b-83bc-714e3ce358c8)
hmm yea we cannot claim

**Comment by thebrumby** [comment]
> hmm yea we cannot claim

Hi @wordfangsss,

It's working OK for me, can you provide more details?

**Comment by bscongluanbui** [comment]
> > hmm yea we cannot claim
> 
> Hi @wordfangsss,
> 
> It's working OK for me, can you provide more details?

Hm, the new update 2 days and I cannot Claim too.

**Comment by wordfangsss** [comment]
> > hmm yea we cannot claim
> 
> Hi @wordfangsss,
> 
> It's working OK for me, can you provide more details?

see [seed.py](https://github.com/thebrumby/HotWalletClaimer/blob/main/games/seed.py) the last commit is 4 days ago, and actually the game there is some update yesterday

**Comment by thebrumby** [comment]
Looks like I hadn't updated the code from my local copy :P

**Comment by bscongluanbui** [comment]
> Looks like I hadn't updated the code from my local copy :P

I update the new  commit but seem still not working
![image](https://github.com/user-attachments/assets/29227fab-9aba-450b-9e93-dc31a76a8b86)

**Comment by wordfangsss** [comment]
> Looks like I hadn't updated the code from my local copy :P

![image](https://github.com/user-attachments/assets/dd04e564-f94c-4b48-a64e-d512d989cf16)
hmm weird its says claimed on the log, but when i check manualy in the app actually it's not claimed yet

![Screenshot_20240918-194849_Telegraph](https://github.com/user-attachments/assets/da767c07-4ef4-4215-9e9a-b53c05a97398)

**Comment by thebrumby** [comment]
Looks strange for sure. You could double-check everything is 100% on the latest code:

## Docker
```
./pull-scripts.sh
pm2 delete http-proxy
pm2 save
./launch.sh enable-proxy
pm2 restart /Seed/
```

## Standalone
```
git pull
pm2 delete http-proxy
pm2 save
./launch.sh enable-proxy
pm2 restart /Seed/
```

It's possible they added some new screen or something to complete which might be blocking it, you'd have to follow the troubleshooting steps to see what's happening, or wait for me to get blocked by the same issue.

**Comment by wordfangsss** [comment]
> Looks strange for sure. You could double-check everything is 100% on the latest code:
> 
> ## Docker
> ```
> ./pull-scripts.sh
> pm2 delete http-proxy
> pm2 save
> ./launch.sh enable-proxy
> pm2 restart /Seed/
> ```
> 
> ## Standalone
> ```
> git pull
> pm2 delete http-proxy
> pm2 save
> ./launch.sh enable-proxy
> pm2 restart /Seed/
> ```
> 
> It's possible they added some new screen or something to complete which might be blocking it, you'd have to follow the troubleshooting steps to see what's happening, or wait for me to get blocked by the same issue.

Oh no problem, it's working well now. By the way, I have a request: Could you add an automatic start hunt feature, and also auto-claim the results after the 12-hour hunt

![Screenshot_20240918-214918_Telegraph](https://github.com/user-attachments/assets/ac3fa913-8e44-4df3-ba52-a8788601321a)

**Comment by thebrumby** [comment]
Yeah, I saw the opportunity to add this the other day. 

Next priority is repair Spell after their major GUI changes, then I’ll take a look.

**Comment by wordfangsss** [comment]
> Yeah, I saw the opportunity to add this the other day.
> 
> Next priority is repair Spell after their major GUI changes, then I’ll take a look.

Thanks a lot for all the effort you've put in, especially doing this for free. Really appreciate it!
