### ISSUE TITLE
Help Me: Problem with free space

### ISSUE THREAD

**Issue by Neo19867** [thebrumby/HotWalletClaimer#232]
Problem with free space.
I run several bots for 3 accounts and after a couple of weeks Docker starts to take up 200-300 gigabytes. This is very bad. I completely removed Docker and reinstalled it, ran your script and everything repeated. After a couple of weeks, I ran out of disk space. How can I solve this problem?

**Comment by thebrumby** [comment]
> Problem with free space. I run several bots for 3 accounts and after a couple of weeks Docker starts to take up 200-300 gigabytes. This is very bad. I completely removed Docker and reinstalled it, ran your script and everything repeated. After a couple of weeks, I ran out of disk space. How can I solve this problem?

Hi @Neo19867,
> Docker starts to take up 200-300 gigabytes.

I assume you mean megabytes, not gigabytes? If you filled a 300 GB hard disk , it's highly unlikely to be from running three sessions with this script, you'd have some major issue with your system
> This is very bad.

For you maybe! Virtually every browser in the world caches images, CSS, Javascript, and other frequently used data which doesn't change regularly to reduce network load and speed up to the user experience. Disabling the cache will cause every game asset to load every time you make a claim, this will cause the script to run slower and add more network load. 

> How can I solve this problem?

You could have read the closed issues or followed the setup instructions!

## Usage Instructions
After executing the script with ```./launch.sh```, you will be prompted to update settings and configure the session:

### Update Settings
   - If you choose "yes" to update settings when prompted, you can review and possibly update the following settings:
      - `enableCache`: If disabled, reduces the amount of data cached to disk, with the trade-off of higher data transmission volume.

**Comment by billal7** [comment]
I also faced the same problem , it was because septber 7 the previous version of docker didn't support reclaim storage feature in wsl2. if you can update to latest version now they mentioned it supported reclaim feature. before that I untick "use wsl2 instead of hyper-v" while installing docker. do it and use hyper-v and the problem solved.
