### ISSUE TITLE
Feature Request: Spell - major GUI changes

### ISSUE THREAD

**Issue by thebrumby** [thebrumby/HotWalletClaimer#233]
**Describe the Feature You'd Like (required):**
Refactor script to take into account the major GUI changes

**How Would You Use It (optional):**
All - the Spell game devs look to have made a big graphical shift, and possibly some anti-bot blocking, we'll take a look in the coming days to see what can be done to get around this.

**Comment by thebrumby** [comment]
All,

Just a quick update to say Spell has been updated after the major GUI changes, the claim, balance and daily puzzle functions should now be working again.

**Comment by bscongluanbui** [comment]
> All,
> 
> Just a quick update to say Spell has been updated after the major GUI changes, the claim, balance and daily puzzle functions should now be working again.

Hi I update the latest version but Spell game still notworking correctly. It said 
Step 118 - This means either the claim failed, or there is lag in the game.

**Comment by thebrumby** [comment]
Hi, 

Are you using the built-in proxy? My latest recommendation was to run with the built-in proxy disabled, after disabling it, please restart Spell:

## Usage Instructions

After executing the script with `./launch.sh`, you'll be prompted to update settings and configure your session.

### Update Settings

If you choose **"yes"** when prompted to update settings, you can review and modify the following options:

- **`useProxy`**: Decide whether to use the built-in proxy (as of 19th September 2024, recommended **off**).
-------------------
```
pm2 restart /Spell/
```

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Are you using the built-in proxy? My latest recommendation was to run with the built-in proxy disabled, after disabling it, please restart Spell:
> 
> ## Usage Instructions
> After executing the script with `./launch.sh`, you'll be prompted to update settings and configure your session.
> 
> ### Update Settings
> If you choose **"yes"** when prompted to update settings, you can review and modify the following options:
> 
> * **`useProxy`**: Decide whether to use the built-in proxy (as of 19th September 2024, recommended **off**).
> 
> ```
> pm2 restart /Spell/
> ```

Hi Im using normal, not with any proxy

**Comment by thebrumby** [comment]
Hi,

If the proxy is turned off in your settings, yet the script still fails after updating and restarting, you'd need to follow the standard troubleshooting steps to discover why it's not working.
