### ISSUE TITLE
Help Me: 

### ISSUE THREAD

**Issue by ashim175** [thebrumby/HotWalletClaimer#235]
hi sir 
, I just  wanna ask one simple question and you can just delete this issue.  

in my task manager I'm seeing Vmmem running in background including docker so
does that mean Vmmem is the background process of the running scripts? because Vmmem is using my lot of resources like 50% cpu soo

Also can my script runs if i put my laptop in sleep mode?

Thank you.

**Comment by thebrumby** [comment]
The **Vmmem** process is related to running Docker containers. It manages the resources (like CPU and memory) for virtual environments, which Docker relies on. So yes, it makes sense that you’re seeing Vmmem while running the bot—it's handling the background processing for your Docker instance. The high resource usage is common, especially if the containers are doing resource-intensive tasks.

Regarding your second question, if you put your laptop in **sleep mode**, all processes (including Docker) will pause, meaning the script won’t run while the laptop is asleep. 

However, you can adjust your laptop’s power settings to prevent it from going to sleep while still saving energy:
- Set your laptop to **turn off the screen and hard disk** after a certain period of inactivity, but **keep the system awake** to allow Docker (and your script) to continue running in the background.

This way, you won’t need to worry about the script pausing, and you’ll save some power while the screen and disk aren’t being used.

**Comment by ashim175** [comment]
i have 8gb ram and 
Vmmem almost takes 3600/2600 MB of ram and my ram usage gets upto 95% in which there are total of 15 session ( and I'll be adding more )
is this normal
( then i should get another ram )

**Comment by Wellynounet** [comment]
I have around 45 sessions running on my Proxmox server with 4 GB of RAM allocated for Docker, but I am only using about 2 GB of RAM.

**Comment by thebrumby** [comment]
I only ran Docker in Windows for testing, so I can’t really say. In terms of the script usage, 3 gb usage seems high. Maybe 50% of that is the overhead for Docker. 

I guess the 3 main options are:
- upgrade to 16 Gb memory
- switch to a VPS, you could run 50-100 sessions for on £8 package 
- if you don’t use the laptop very oftenfor other task, Dual boot a Linux system. 8gb ram, 4 cores, 15 gb disk space would run the same 50-100 sessions.

**Comment by ashim175** [comment]
can i ask how and where to do no.2 
also for 3 no.
