### ISSUE TITLE
Mine seed app News error

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#24]
Mine seed app error claim when it have news. Thank you
Best regards

**Comment by Wellynounet** [comment]
YEah  because tree tap is here we need to chop him :/

**Comment by thebrumby** [comment]
Hi,

I uploaded the version with the "Tap tree 10 times" line in it! The latest version is pushed to the repository, please let me know how you get on.

**Comment by bscongluanbui** [comment]
> Hi,
> 
> The first version I uploaded was without the "Tap tree 10 times" line in it! The latest version is pushed to the repository, please let me know how you get on.

It's seem working.
Thank you

**Comment by thebrumby** [comment]
Perfect! Happy claiming :)

**Comment by bscongluanbui** [comment]
https://t.me/oxygenminerbot?start=881735154
Hi this oxygen bot from Polygon chain support
