### ISSUE TITLE
please check this is what i am facing in linux

### ISSUE THREAD

**Issue by xaxazic007** [thebrumby/HotWalletClaimer#242]
![brumpy](https://github.com/user-attachments/assets/e41830cd-6f5c-4905-b219-d9fdeab00e49)
**Describe the Bug (required):**

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Please confirm that you've reviewed the troubleshooting guide linked above and completed all steps to ensure the issue is not with your session.

**Steps to Reproduce (required):**
List the steps to reproduce the bug.

**Expected Behavior (required):**
Describe what you expected to happen.

**Screenshots or Logs:**
If applicable, add screenshots or logs to help explain your problem.

**Comment by thebrumby** [comment]
You can get that error if you are too late taking a picture of the QR code, what happens if you try again?

**Comment by thebrumby** [comment]
Or as described in the trouble shooting, if you are struggling to install it on Ubuntu, use the pre-built [Docker Image](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/DOCKER.md).

**Comment by xaxazic007** [comment]
> You can get that error if you are too late taking a picture of the QR code, what happens if you try again?

same issue as in SS everytime.
i do login instant as soon s qr appears and my device does show auth success.

**Comment by xaxazic007** [comment]
> So, in Linux, do you get this error before seeing any QR code? If so something probably isn't installed correctly.
> 
> You can always run the installer a second time to watch for errors, or to change from Chrome Browser to Chromium:
> 
> ```
> ./install.sh
> ```

i got it after QR code seems the issues is with QR code scan. I gave a try disabling QR logged via number the problem wasn't persist

**Comment by thebrumby** [comment]
So, it probably failed to download some dependency for you. I just started with a clean install on AWS, and can not replicate your error.
