### ISSUE TITLE
Simpletap bug

### ISSUE THREAD

**Issue by LFQO** [thebrumby/HotWalletClaimer#243]
Hi, I'm getting the following error in simple tap.
![image](https://github.com/user-attachments/assets/34d81668-426a-4165-b1eb-8f7158f37b16)

**Comment by LFQO** [comment]
I also have a question regarding auto-update process. I've occasionally deleted it. It's there a command to start it again?

**Comment by thebrumby** [comment]
Hi, 

Kindly update your code and try again. You can see below the closed issues for people who deleted their auto-update.

https://github.com/thebrumby/HotWalletClaimer/issues/213#issuecomment-2323348698
https://github.com/thebrumby/HotWalletClaimer/issues/221#issuecomment-2343805909
