### ISSUE TITLE
Bug: [Describe the issue briefly]error only while running seed 

### ISSUE THREAD

**Issue by xaxaziccrypt** [thebrumby/HotWalletClaimer#244]
![seederror](https://github.com/user-attachments/assets/c51ebbd9-05c6-4bc4-bda4-5a2a3705e962)
please solution

**Comment by thebrumby** [comment]
Hi,

The standard installation folder is `HotWalletBot ` but you are called the script from `HotWalletClaimer`, and whatever script you're using is not using the correct folder, it should say `./games/fuel.py with arguments:`

<img width="418" alt="image" src="https://github.com/user-attachments/assets/c530008d-3567-4682-8810-4747471e656a">

I'd recommend reinstalling things using the correct method and standard folders. If you prefer to modify things and deviate from the default, you'll need to find your own solutions.
