### ISSUE TITLE
Bug: [Describe the issue briefly]

### ISSUE THREAD

**Issue by xaxazic007** [thebrumby/HotWalletClaimer#245]
![Screenshot_20240925_101328](https://github.com/user-attachments/assets/3c2233e5-80dd-4c64-b4d9-fbc27c7683a9)
**Describe the Bug (required):**

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Please confirm that you've reviewed the troubleshooting guide linked above and completed all steps to ensure the issue is not with your session.

**Steps to Reproduce (required):**
List the steps to reproduce the bug.

**Expected Behavior (required):**
Describe what you expected to happen.

**Screenshots or Logs:**
If applicable, add screenshots or logs to help explain your problem.

**Comment by thebrumby** [comment]
```
google-chrome --version
chromium-browser --version
chromedriver --version
```
