### ISSUE TITLE
Help Me: Suddenly all pm2 process was gone

### ISSUE THREAD

**Issue by Jelingam** [thebrumby/HotWalletClaimer#246]
hi
i don't know what's happening in my server, all games was gone.

but selenium folders are still there.

![image](https://github.com/user-attachments/assets/31facbb9-df0f-4e0b-b2e2-93eeba3035ab)

**Comment by Jelingam** [comment]
```
from os import listdir
from os.path import isfile, join, isdir
import subprocess

def start_pm2_app(script_path, app_name, session_name):
    interpreter_path = "venv/bin/python3"
    command = f"NODE_NO_WARNINGS=1 pm2 start {script_path} --name {app_name} --interpreter {interpreter_path} --watch {script_path} -- {session_name}"
    subprocess.run(command, shell=True, check=True)
    # command = f"NODE_NO_WARNINGS=1 pm2 save"
    # subprocess.run(command, shell=True, check=True)

mypath = "./selenium/"
allfolder = [f for f in listdir(mypath) if isdir(join(mypath, f))]
for folder in allfolder:
    if "Telegram" in folder:
        continue
    else:
        script_path = join(mypath, folder)
        if isdir(script_path):
            start_pm2_app(script_path, folder, folder)
```
i came up with this solution, but i got this error.
anyone can help me ?

![image](https://github.com/user-attachments/assets/e46c3ea1-3444-46e7-bfc7-7dd30f80d967)

**Comment by thebrumby** [comment]
Hi @Jelingam,

In your [other post](https://github.com/thebrumby/HotWalletClaimer/issues/237) you were talking about writing a script to stop PM2 handling the idle processes, and now they have mysteriously disappeared? Strange!

If your PM2 processes have disappeared, you can attempt to restore them using:

```
pm2 resurrect
```

If that doesn't work, the format of the PM2 command the script uses is shown in the text at the end of the process:

>We backed up the session data in case of a later crash!
You could add the new/updated session to PM use: pm2 start games/blum.py --interpreter venv/bin/python3 --name Blum:Wallet1 -- Blum:Wallet1
Enter 'y' to continue to 'claim' function, 'e' to exit, 'a' or <enter> to automatically add to PM2:

So you could write a script or manually set up each one to restore them based on this example:
```
pm2 start games/blum.py --interpreter venv/bin/python3 --name Blum:Wallet1 -- Blum:Wallet1
```

You'd need to change the name of the script for each game, replacing `games/blum.py` with the script you wish to handle the session and then substitute `Blum:Wallet1` with the name of the session folder from the Selenium folder.

**Comment by thebrumby** [comment]
> from os import listdir
> from os.path import isfile, join, isdir
> import subprocess
> 
> def start_pm2_app(script_path, app_name, session_name):
>     interpreter_path = "venv/bin/python3"
>     command = f"NODE_NO_WARNINGS=1 pm2 start {script_path} --name {app_name} --interpreter {interpreter_path} --watch {script_path} -- {session_name}"
>     subprocess.run(command, shell=True, check=True)
>     # command = f"NODE_NO_WARNINGS=1 pm2 save"
>     # subprocess.run(command, shell=True, check=True)
> 
> mypath = "./selenium/"
> allfolder = [f for f in listdir(mypath) if isdir(join(mypath, f))]
> for folder in allfolder:
>     if "Telegram" in folder:
>         continue
>     else:
>         script_path = join(mypath, folder)
>         if isdir(script_path):
>             start_pm2_app(script_path, folder, folder)

While this correctly iterates through the Selenium session folders, it is trying to set the game session folder name as the script to run, rather than the relative script from the `./games` directory.

**Comment by Jelingam** [comment]
Tnx Phil

**Comment by thebrumby** [comment]
My pleasure, I hope you got sorted.
