### ISSUE TITLE
Game Suggestion: NOT pixel

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#247]
**Bot Name (required):**
NOT pixel 

**Bot Handle (required):**
They say you can only join by referral, so I'm posting the link. https://t.me/notpixel/app?startapp=f6506558140

**Reason for Inclusion:**
Hi Phil! This is a project from the creators of the famous notcoin. The creators of notcoin officially in their social networks promised that for this project will be the biggest airdrop this year. Airdrop is scheduled for November, that is very soon.
The essence of the project that for a certain interval of time you need to taping at random in the picture painting a pixel, a certain number of attempts is given (in the beginning 6). For each pixel are accrued tokens PX - they will be converted into airdrop then. After all presses are used, after a recovery interval (6 minutes by default) they will be available again. Also in the boosts section is available tokens claim every minute

It is very desirable to automate this project, because the creators have already shown what they are capable of + very soon airdrop speaks in favor of the fact that they will fulfill their promises.

**Comment by vanhbakaa** [comment]
https://github.com/vanhbakaa/Notpixel-bot

**Comment by thebrumby** [comment]
Thanks, 

This looks fun, I need to wrap my head around what needs to be done to automate it, but I think something can be done.

**Comment by farmdigit** [comment]
> Thanks,
> 
> This looks fun, I need to wrap my head around what needs to be done to automate it, but I think something can be done.

You need to simulate a random tap on the screen and after that claim a pixel. And also in the boosts section the usual claim button as in other miniapps.

**Comment by farmdigit** [comment]
> https://github.com/vanhbakaa/Notpixel-bot

Can this be implemented in Phil's bot?

**Comment by mi7f** [comment]
> Thanks,
> 
> This looks fun, I need to wrap my head around what needs to be done to automate it, but I think something can be done.

Good afternoon. Do you plan to realize this game? After all, it is very promising and limited on the time of mining, as the developers say in November everything will end. So I would like to see this game in your scripts, very much.

**Comment by thebrumby** [comment]
Hi @mi7f,

Unfortunately their anti-bot detection is currently blocking any progress on adding this game.

**Comment by farmdigit** [comment]
> Hi @mi7f,
> 
> Unfortunately, their anti-bot detection is currently blocking any progress on adding this game.

Maybe implement a ready-made solution? Here above a man threw the source code, which according to him works:
https://github.com/vanhbakaa/Notpixel-bot

**Comment by farmdigit** [comment]
> Hi @mi7f,
> 
> Unfortunately, their anti-bot detection is currently blocking any progress on adding this game.

Hi Phil!!! Is there any possibility to work with the portable version instead of the web? There is no antibot block there.

**Comment by thebrumby** [comment]
Hi @farmdigit!

We use Selenium primarily to handle interactions with Telegram through the web version, which allows us to automate tasks within a browser. Selenium supports a variety of browsers like Chrome, Firefox, Edge, and others, making it versatile for this kind of automation.

However, Selenium is designed to work with web browsers and not external desktop applications, including the portable version of Telegram. For interacting with the Telegram desktop client, it would need a different approach.

Hope this helps clarify things!
