### ISSUE TITLE
Help Me: How can I use this script without docker, any alternative?

### ISSUE THREAD

**Issue by Keyz400** [thebrumby/HotWalletClaimer#248]
How can I use this script without docker, any alternative?

I don't have a powerful VPS.

**Comment by prognt** [comment]
i run it on windows 10/11 in docker desktop

**Comment by thebrumby** [comment]
Hi,

All the options are on the main page with links in each section to the individual instruction guides in the "docs" folder :

Windows PC/laptop - Docker or WSL2
Ubuntu or VPS: Docker or standalone install
Mac: Docker

1 core 1 GB ram will only do one account for testing purposes. 1 core 2 GB is recommended if you intend to claim on multiple accounts/games.

Thanks.
