### ISSUE TITLE
Bug: Login issue 

### ISSUE THREAD

**Issue by Keyz400** [thebrumby/HotWalletClaimer#251]
After scanning QR code. Script not processing next steps. (Stop after generating QR code). Plz give number login option. So we can also login through Mobile number....

**Comment by thebrumby** [comment]
Kindly follow the [usage instructions](https://github.com/thebrumby/HotWalletClaimer?tab=readme-ov-file#v303-release-notes) or watch video 4  for guidance of how to do this.
