### ISSUE TITLE
Feature Request:  Worm Catching & Marketplace 

### ISSUE THREAD

**Issue by HoN3YP0T** [thebrumby/HotWalletClaimer#252]
Feature Request:

The current seed script only attempts to catch worms when the seed claim timer ends, which can sometimes be more than 12 or 24 hours, causing it to miss many worms. Could you please add a feature to detect when the next worm will spawn and catch it accordingly? Additionally, an automatic buy/sell function in the marketplace, where worms are bought at a low price and sold 20-30% higher, would help generate more seed.

Thank you.

**Comment by thebrumby** [comment]
Hi, 

We won't add adding an automated trader, if you want to change the logic for the claim time, look for this around line 155:

```
            remaining_time = self.apply_random_offset(remaining_wait_time)
            self.output(f"STATUS: Original wait time {remaining_wait_time} minutes, we'll sleep for {remaining_time} minutes after random offset.", 1)
            return remaining_time
```

And modify it to this:

```
            remaining_time = self.apply_random_offset(remaining_wait_time)
            self.output(f"STATUS: Original wait time {remaining_wait_time} minutes, we'll sleep for {remaining_time} minutes after random offset.", 1)
            return min(remaining_time,120)
```

Where 120 is the number of minutes until it repeats.
