### ISSUE TITLE
Bug: Unknown

### ISSUE THREAD

**Issue by Keyz400** [thebrumby/HotWalletClaimer#253]
![Screenshot_2024-10-01-12-35-03-502_com server auditor ssh client-edit](https://github.com/user-attachments/assets/2d7ad85f-1b13-46c6-8f8f-408ed711bfcd)

Yesterday i successfully login/started two bots, but today nothing is happening today I want to start new bot, but not processing next steps, I wait atleast 25-30 minutes (Please refr SS)

Using podman docker, because it is lite version of docker 😅

**Comment by thebrumby** [comment]
What's your free memory during a claim?

```
free -m
```

**Comment by Keyz400** [comment]
> What's your free memory during a claim?
> 
> ```
> free -m
> ```

100 MB approx

**Comment by thebrumby** [comment]
It might be due to low memory. You could try stopping everything in PM2 and then restart one at once to see what the limit is.
