### ISSUE TITLE
Bug: Cold error

### ISSUE THREAD

**Issue by kohutiv** [thebrumby/HotWalletClaimer#254]
This error keeps popping up. Tried all possible settings.
DOCKER

**Image removed by moderator as contains Bothfather API key**

**100_QR-code-check-during-session-start**
![100_QR-code-check-during-session-start](https://github.com/user-attachments/assets/6f3a8c66-71c8-400b-8c48-514f904f3669)

**101_Timeout-during-check-for-the-start-button-(should-not-be-present)**
![101_Timeout-during-check-for-the-start-button-(should-not-be-present)](https://github.com/user-attachments/assets/21b69fe1-2a6d-46bc-8120-41667ba4939e)

**102_iterating-through-launch-game-buttons**
![102_iterating-through-launch-game-buttons](https://github.com/user-attachments/assets/9920950a-a544-4699-9c12-868ceeed067a)

**102_successfully-opened-a-game-start-link**
![102_successfully-opened-a-game-start-link](https://github.com/user-attachments/assets/1d1d65f6-76ee-41b4-ae08-3c9ce7d0623d)

**103_Timeout-during-click-the-'Launch'-button-(probably-not-present)**
![103_Timeout-during-click-the-'Launch'-button-(probably-not-present)](https://github.com/user-attachments/assets/94d5fcd9-876d-4938-927b-b223633b238a)

**105_successfully-switched-to-iFrame**
![105_successfully-switched-to-iFrame](https://github.com/user-attachments/assets/75bf4c19-79af-4ec9-bb95-5387ef4c0fbe)

**106_Timeout-during-click-the-'storage'-link**
![106_Timeout-during-click-the-'storage'-link](https://github.com/user-attachments/assets/75ce9dcd-13a7-49b4-8a55-0d9fba493d94)

**107_MonElem-no-description**
![107_MonElem-no-description](https://github.com/user-attachments/assets/47586070-278b-4c9d-9269-b4f735ff1b6a)

**109_Timeout-during-get-the-pre-claim-wait-timer**
![109_Timeout-during-get-the-pre-claim-wait-timer](https://github.com/user-attachments/assets/9529b517-0745-40c9-931c-1d7afb120a4b)

Help. Thank you.

**Comment by kohutiv** [comment]
Step 105 - Was successfully able to switch to the app's iFrame within 'web-app-body'.
3|BNB-Cold:fishki  | Step 106 - Attempting to click the 'storage' link...
3|BNB-Cold:fishki  | Step 106 - Timeout while attempting to click the 'storage' link.
3|BNB-Cold:fishki  | Step 107 - Found 0 elements with XPath: (//img[@alt='COLD']/following-sibling::p)[last()] for no description
3|BNB-Cold:fishki  | Step 108 - Found 0 elements with XPath: //div[p[text()='Frost Box']]//p[last()] for no description
3|BNB-Cold:fishki  | Step 108 - An error occurred: expected string or bytes-like object, got 'bool'
3|BNB-Cold:fishki  | Step 109 - Attempting to get the pre-claim wait timer...
3|BNB-Cold:fishki  | Step 109 - Timeout while attempting to get the pre-claim wait timer.
3|BNB-Cold:fishki  | STATUS: The pot is not yet full, we'll go back to sleep for 1 hour.
3|BNB-Cold:fishki  | Session released: ./selenium/BNB-Cold:fishki
3|BNB-Cold:fishki  | CHROME DRIVER DETACHED: It is now safe to exit the script.
3|BNB-Cold:fishki  | Session released: ./selenium/BNB-Cold:fishki

**Comment by thebrumby** [comment]
Hi,

I have pushed an update to the repository. Please confirm whether or not it fixed the problem. 

Thanks.

**Comment by kohutiv** [comment]
> Hi,
> 
> I have pushed an update to the repository. Please confirm whether or not it fixed the problem.
> 
> Thanks.

Everything works, thanks.

**Comment by thebrumby** [comment]
Pleased to hear everything's working OK.
