### ISSUE TITLE
Game Suggestion: Yupalka

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#255]
**Bot Name (required):**
Yupalka

**Bot Handle (required):**
invitation is possible only by referral link, so I'm inserting it: https://t.me/YupLand_bot/Yupalka_DarAi?startapp=396860104

**Reason for Inclusion:**
Hi Phil!!!! This app is part of the Yupiland ecosystem, which runs partly on AI. The ecosystem includes a lot of things I haven't quite figured out yet, because there's a lot of stuff there. They have their own coin Darai on the blockchain near which can already be freely bought and sold in the hot wallet. In addition to the coin there are various nfts with different utility. Some of them allow you to get Darai coin regularly, some of them give you abilities and so on. In this ecosystem there are regular airdrop events where nfts or darai coins are distributed on the near blockchain wallets. nfts can be sold in the ecosystem or used in some other way. In the app I provided, miniDarai coins are farmed. For it you can pump your account in the mini app and also buy boxes with aidrops, which appear there periodically. This is the only application besides hot wallet of all that I now know that now regularly give away some values that are liquid and they can be sold. In the application you just need to choose any card once in a certain period and that's it. The time between selecting a card depends on the pumping of the account.

**Comment by thebrumby** [comment]
Nice suggestion @farmdigit,

The game loads nicely on Telegram web, and I have a bot working that's pulling in the balance and remaining wait time. I'll continue tomorrow and map how to click the cards, before pushing out the first version. 

We'll probably release an auto-upgrade version later on, too.

Cheers

However,

**Comment by farmdigit** [comment]
> Nice suggestion @farmdigit,
> 
> The game loads nicely on Telegram web, and I have a bot working that's pulling in the balance and remaining wait time. I'll continue tomorrow and map how to click the cards, before pushing out the first version.
> 
> We'll probably release an auto-upgrade version later on, too.
> 
> Cheers
> 
> However,

That's awesome!!! Is it quick to add to the bot? It seems like a pretty simple app there.

**Comment by thebrumby** [comment]
> Is it quick to add to the bot? It seems like a pretty simple app there.

As you say, it depends on the complexity of the game and how much effort they make to block bots. In this case, getting the balance, wait time, and claiming the card is pretty easy. In fact, the whole thing seems to be working OK on my local system.

I'll send it to @Wellynounet to help with the testing, but it looks like we can push it tomorrow.

**Comment by farmdigit** [comment]
> > Is it quick to add to the bot? It seems like a pretty simple app there.
> 
> As you say, it depends on the complexity of the game and how much effort they make to block bots. In this case, getting the balance, wait time, and claiming the card is pretty easy. In fact, the whole thing seems to be working OK on my local system.
> 
> I'll send it to @Wellynounet to help with the testing, but it looks like we can push it tomorrow.

that's cool!!! yes everything should be easy there as the mini app is just a part of the ecosystem and they don't have bots at all yet. they are just starting to develop and have a pretty small community.

**Comment by farmdigit** [comment]
> ```
> ./launch.sh yapalka
> ```
> 
> **🚨 Game is Live! 🚨**
> 
> Big thanks to **@Wellynounet** for the help with testing! The game is up and running for an initial attempt. It tracks your balance, shows the time until the next card pick is available, and when you're able to draw, it randomly picks a card and tells you which number it selected. So far, rewards have ranged from 7 to 226, so there's quite a bit of variance in the amounts.
> 
> Once we're happy with the core functionality, we'll add an auto-upgrade path and unlock bonus content as we explore new features—especially once we reach Level 4, where a lot more seems to be available.

Phil, you and **@Wellynounet** are unbelievably cool!!!

**Comment by thebrumby** [comment]
Thanks for a great suggestion @farmdigit!

**Comment by farmdigit** [comment]
> Thanks for a great suggestion @farmdigit!

if you're interested, the link to their ecosystem site https://yupik.fun
as well as the ecosystem on telegram:
https://t.me/yupland
and this is the place where you can trade their nft:
https://t.me/+pmkQzdKTKfE3M2Qy

today added the ability to buy new boxes in mini app, you can get up to 1kk darai (about 20 bucks in equivalent) from each box. Darai can be sold in any near wallet, for example in hot wallet.

**Comment by thebrumby** [comment]
It looks like the devs switched off TG web! I'll take a look next week what we can do with a new approach to the proxy to get around it.

**Comment by farmdigit** [comment]
> It looks like the devs switched off TG web! I'll take a look next week what we can do with a new approach to the proxy to get around it.

maybe the mobile UA can help?
