### ISSUE TITLE
Bug: Crypto Rank

### ISSUE THREAD

**Issue by kohutiv** [thebrumby/HotWalletClaimer#256]
Regards!

Crypto Rank does not collect reward, daily reward etc.

**106_Timeout-during-initial-screen-(may-not-be-present)**
![106_Timeout-during-initial-screen-(may-not-be-present)](https://github.com/user-attachments/assets/e287d929-45b9-4997-baa6-74037d51dba9)

**108_Timeout-during-look-for-the-claim-button**
![108_Timeout-during-look-for-the-claim-button](https://github.com/user-attachments/assets/5b58e2be-51f4-4d5f-aae9-830be7bc4eca)

![image](https://github.com/user-attachments/assets/bec3664a-e846-4fe8-96a3-38db2a2a3705)

**Comment by thebrumby** [comment]
Hi @kohutiv,

Thanks for the heads up. It appears the game devs changed the format for the main buttons, and also introduced an extra step to claim the daily bonus. I've updated the mappings, and while I've only tested it once, it appears everything is working again correctly. 

If you can confirm, and we'll close the issue. 

Thanks
