### ISSUE TITLE
Game Suggestion: Electra

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#258]
**Bot Name (required):**
Electra

**Bot Handle (required):**
invitation is possible only by referral link, so I'm inserting it: https://t.me/ElectraAppBot/dex?startapp=YrQqXCue

**Reason for Inclusion:**
Hi Phil!!!! This is an analog of blum, but unlike blum there is already a ready-made dex exchange with adaptation for telegram. The listing will be in December. The development is done by the Lumia.org team.
In the mini app itself there are the following activities:
1. once in 6 hours to play a game where you need to pump a bitcoin.
2. once every 6 hours to guess the bitcoin rate in 6 hours - click at random on one of the two buttons, you can always click buy :) 'case crypto forever :)
3. collect a daily reward once a day - pop up just click on the button to collect the reward.
4. one-time social activity tasks.
I remember that you don't implement games, but can you at least implement points 2 and 3? It is a regular claim in essence.

**Comment by thebrumby** [comment]
Thanks for the suggestion @farmdigit, we'll look to add this next.

**Comment by farmdigit** [comment]
> Thanks for the suggestion @farmdigit, we'll look to add this next.

TY VM, Phill!!

**Comment by thebrumby** [comment]
Hi,

Unfortunately, despite multiple attempts to integrate the game, it isn’t cooperating with Selenium/headless Chrome. For now, I’m going to close the request.
