### ISSUE TITLE
Bug: [no QRcode settings]

### ISSUE THREAD

**Issue by devCarlosHenSil** [thebrumby/HotWalletClaimer#259]
![Captura de tela 2024-10-09 150242](https://github.com/user-attachments/assets/0a3b9ce7-17d3-4a26-a31c-c2cd8b5dfe04)
![Captura de tela 2024-10-09 151559](https://github.com/user-attachments/assets/2477fe10-b97f-4d87-8ac5-997788496607)

Olá, Phill pode me ajudar não estou conseguindo utilizar a sua aplicação pois segui todo passado em ambos sistemas operacionais porem me deparo sempre com o mesmo problema , ele não aparece o QRcode para que eu possa scanear e outro ponto é que está bem diferente do video a forma de instalação uma vez que mudou muito de lá para cá com seus comiits se puder me ajudar agradeço.
Abraço.

**Comment by thebrumby** [comment]
Sure, here’s a detailed response in Portuguese with instructions on how to check the connection to Telegram Web using curl:

Oi,

Você está usando Docker ou Ubuntu? Pode ser que existam algumas configurações extras no sistema, mas o processo geral deve ser o mesmo. Parece que o script não está conseguindo detectar o QR code do Telegram.

Para verificar a conexão com o Telegram Web, você pode usar o comando curl no terminal. Siga estas instruções:

	1.	Abra o terminal.
	2.	Digite o seguinte comando e pressione Enter:
```
curl -I https://web.telegram.org
```
Isso deve retornar algumas informações sobre a conexão. Se você conseguir ver algo como HTTP/1.1 200 OK, significa que a conexão com o site está funcionando corretamente.

Se não conseguir essa resposta, pode haver um problema de rede ou firewall bloqueando o acesso ao Telegram Web. Me avise o que aparecer para poder ajudar mais!

**Comment by thebrumby** [comment]
Se o QR code não aparecer, talvez devido a uma conexão de internet lenta ou algum outro problema, você pode desativar a captura de tela do QR code nas configurações. Assim, será solicitado o número de telefone registrado, e o Telegram enviará um código OTP para o seu dispositivo.

**Comment by devCarlosHenSil** [comment]
i use method docker , send for you screenshot 
![Captura de tela 2024-10-09 183312](https://github.com/user-attachments/assets/5b948aba-c1bf-4a8f-a292-755b32681a61)
![Captura de tela 2024-10-09 183334](https://github.com/user-attachments/assets/0d15ac2a-89bd-498f-b5ed-659aace58c52)
![Captura de tela 2024-10-09 183406](https://github.com/user-attachments/assets/7f4c9109-9984-4442-afe2-28ce63d1ae77)
![Captura de tela 2024-10-09 183425](https://github.com/user-attachments/assets/c103aa2f-4ebc-42ee-9808-c74733134374)
![Captura de tela 2024-10-09 183456](https://github.com/user-attachments/assets/a2e6bb9e-4ee8-4a77-b94a-da852e3507e9)
![Captura de tela 2024-10-09 183519](https://github.com/user-attachments/assets/901f94e8-85f1-46e6-a43c-0c55e7a32cc8)
![Captura de tela 2024-10-09 183538](https://github.com/user-attachments/assets/4b108a1c-5e71-44f3-935c-42b7f78d5edc)

**Comment by thebrumby** [comment]
Hi,

The recommended setting is have the built-in proxy turned off, or at least until you have everything working correctly. 

To debug it further, you will need to enable the screenshots from the  virtual web browser as described in the troubleshooting guide.

**Comment by devCarlosHenSil** [comment]
Hello, Phill, it worked as you instructed me to use the method via phone number and disable the proxy, however it is very risky to use multiple accounts with the same IP address, do you know what could be the problem when using a proxy, I tested the proxy itself and it is operating normally.

**Comment by thebrumby** [comment]
Just as an FYI, some users who initially experienced issues logging in a proxy reported that they got the proxy to work by modifying this in `setup-proxy.py`:

```
def update_start_script(host, port, username, password):
    start_script_content = f"""#!/bin/bash
./venv/bin/mitmdump --mode upstream:https://{host}:{port} --upstream-auth {username}:{password} -s {os.path.join(PROXY_DIR, 'modify_requests_responses.py')} > /dev/null 2>&1
"""
    with open(START_SCRIPT_PATH, 'w') as file:
        file.write(start_script_content)
    os.chmod(START_SCRIPT_PATH, 0o755)
```
    
They changed the `https` to `http`. From a personal perspective, I don't want to send unencrypted login credentials over the internet as they could be intercepted by any relay between your Docker setup and the VPN host. If you aren't using a metered VPN, you might be more open to try it than I was.

**Comment by thebrumby** [comment]
I added the option to switch to HTTP authentication in the script, along with a test to see what level of anonymity the proxy provides and a link to [WebShare](https://www.webshare.io/?referral_code=yat0oxfcqbpd) where people can get a free account with some included monthly bandwidth.

**Comment by devCarlosHenSil** [comment]
Thank you very much Phill for your willingness to help. I will check the changes you committed.****
