### ISSUE TITLE
Request New Game: memefi

### ISSUE THREAD

**Issue by itcthienkhiem** [thebrumby/HotWalletClaimer#26]
Dear Ad,
Please add new game memefi in telegram bot 
Link: https://web.telegram.org/k/#@memefi_coin_bot
Thanks

**Comment by thebrumby** [comment]
Hi, 

We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)

**Comment by bscongluanbui** [comment]
> Hi,
> 
> We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)

Hi Oxygen is a very fomo game now and plan to list on Q3/2024
https://t.me/oxygenminerbot
pls Consider it

**Comment by thebrumby** [comment]
> > Hi,
> > We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)
> 
> Hi Oxygen is a very fomo game now and plan to list on Q3/2024 https://t.me/oxygenminerbot pls Consider it

Thank you for your suggestion of **Oxygen** and the **Coffee** ☕!!

We are currently doing the final test and will upload it shortly.

**Comment by thebrumby** [comment]
> > Hi,
> > We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)
> 
> Hi Oxygen is a very fomo game now and plan to list on Q3/2024 https://t.me/oxygenminerbot pls Consider it

We have now uploaded the script, although we continuing to test if it consistently claims the daily box. So far it is correctly claiming the hourly reward without issue. Once downloaded, you can log in and set up the claim process with:

 ```
./launch.sh oxygen
```

<img width="650" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/8e1749bf-9586-401b-bf7d-5597e53baf35">

**Comment by bscongluanbui** [comment]
> > > Hi,
> > > We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)
> > 
> > 
> > Hi Oxygen is a very fomo game now and plan to list on Q3/2024 https://t.me/oxygenminerbot pls Consider it
> 
> We have now uploaded the script, although we continuing to test if it consistently claims the daily box. So far it is correctly claiming the hourly reward without issue. Once downloaded, you can log in and set up the claim process with:
> 
> ```
> ./launch.sh oxygen
> ```
> 
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/29182343/335147745-8e1749bf-9586-401b-bf7d-5597e53baf35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjcyNTgsIm5iZiI6MTcxNzA2Njk1OCwicGF0aCI6Ii8yOTE4MjM0My8zMzUxNDc3NDUtOGUxNzQ5YmYtOTU4Ni00MDFiLWJmN2QtNTU5N2U1M2JhZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTk4NjgzZDllNjFhNzI2NWQwZTVlMmMwM2NmOGZlYjE5MTVlNGZmMmIyYjQ5Y2ViYmIzYzdhZTM2NDc2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOGikMyLCclcddcVmZupFzDqsN4xpnFpYnGNoqpj-js">

Many thanks. Wish best for you

**Comment by bscongluanbui** [comment]
> > > Hi,
> > > We hope to add a new game a week, in the coming weeks. We'll add it to the list of suggestions :)
> > 
> > 
> > Hi Oxygen is a very fomo game now and plan to list on Q3/2024 https://t.me/oxygenminerbot pls Consider it
> 
> We have now uploaded the script, although we continuing to test if it consistently claims the daily box. So far it is correctly claiming the hourly reward without issue. Once downloaded, you can log in and set up the claim process with:
> 
> ```
> ./launch.sh oxygen
> ```
> 
> <img alt="image" width="650" src="https://private-user-images.githubusercontent.com/29182343/335147745-8e1749bf-9586-401b-bf7d-5597e53baf35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNjc1ODgsIm5iZiI6MTcxNzA2NzI4OCwicGF0aCI6Ii8yOTE4MjM0My8zMzUxNDc3NDUtOGUxNzQ5YmYtOTU4Ni00MDFiLWJmN2QtNTU5N2U1M2JhZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDExMDgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMTAwZjU2ZTdkMDVkMjFiYTk5YzAwZWM2NmMwNDJlODIyZDg2ZDhiOGQzMmMzZjY0OTVmN2QyYTQxMGJjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.miKpOTNJCN-1Lk-1tXtr5KDL6QLVulKweYopZpDeRz4">

Hi I'm using linux installation, not docker. How to update this script?

**Comment by thebrumby** [comment]
If you didn't modify any of the base files, you could run `git pull` from inside your `HotWalletBot` directory and it will get the latest version of the scripts without overwriting your variables.txt or existing directories.

If you prefer to be more cautious, you can run. 

```
git clone https://github.com/thebrumby/HotWalletBot.git updated_scripts
cp updated_scripts/games/oxygen.py games/
```

I hope this makes sense?

**Comment by bscongluanbui** [comment]
> > If you didn't modify any of the base files, you could run `git pull` from inside your `HotWalletBot` directory and it will get the latest version of the scripts without overwriting your variables.txt or existing directories.
> > If you prefer to be more cautious, you can run.
> > ```
> > git clone https://github.com/thebrumby/HotWalletBot.git updated_scripts
> > cp updated_scripts/games/oxygen.py games/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope this makes sense?
> 
> thank you I did it perfectly

sorrry but after update the script with git pull. All old process stop, How to restart them. SOrry for my bad

**Comment by Wellynounet** [comment]
> sorrry but after update the script with git pull. All old process stop, How to restart them. SOrry for my bad


They appear in pm2 ls ? or not ? if not  use " pm2 resurrect"  and  everything should work :) like before.

**Comment by bscongluanbui** [comment]
> > sorrry but after update the script with git pull. All old process stop, How to restart them. SOrry for my bad
> 
> They appear in pm2 ls ? or not ? if not use " pm2 resurrect" and everything should work :) like before.

pm2 resurrect not working. It show in inactive process when I run ./remove-process.sh, I can see them

**Comment by thebrumby** [comment]
> It show in inactive process when I run `./remove-process.sh`, I can see them
Hi,

- **PM2 Resurrect:** This is enabled by default in the Docker build.
- **Process Removal:** The script `./remove-process.sh` can be used to remove inactive folders. It lists any folder that exists without a corresponding PM2 process in an "online" status.

If your PM2 processes have disappeared, you have two options, although neither is ideal:
1. **Repeat the Automated Setup:** Use `./remove-process.sh` to remove inactive folders and `./launch.sh` to automate the setup from the beginning.
2. **Manual Addition:** Manually add each process to PM2 based on your actual file structure. Below are some examples:

```bash
pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT:Wallet1 -- HOT:Wallet1
pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold:Wallet1 -- BNB-Cold:Wallet1
pm2 save
```

Thanks

**Comment by bscongluanbui** [comment]
> > It show in inactive process when I run `./remove-process.sh`, I can see them
> > Hi,
> 
> * **PM2 Resurrect:** This is enabled by default in the Docker build.
> * **Process Removal:** The script `./remove-process.sh` can be used to remove inactive folders. It lists any folder that exists without a corresponding PM2 process in an "online" status.
> 
> If your PM2 processes have disappeared, you have two options, although neither is ideal:
> 
> 1. **Repeat the Automated Setup:** Use `./remove-process.sh` to remove inactive folders and `./launch.sh` to automate the setup from the beginning.
> 2. **Manual Addition:** Manually add each process to PM2 based on your actual file structure. Below are some examples:
> 
> ```shell
> pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT:Wallet1 -- HOT:Wallet1
> pm2 start games/cold.py --interpreter venv/bin/python3 --name BNB-Cold:Wallet1 -- BNB-Cold:Wallet1
> pm2 save
> ```
> 
> Thanks

thank you I'm switch to docker and working perfectly. Thanks for you support
