### ISSUE TITLE
delete selenium folder content

### ISSUE THREAD

**Issue by Jelingam** [thebrumby/HotWalletClaimer#264]
hey phil
What happens if I delete this folder?

this is just cache ?

![image](https://github.com/user-attachments/assets/ab38eb41-635e-4064-a70d-df87db6a5a31)

**Comment by Jelingam** [comment]
```
import os

base_folder = "./selenium/"
all_folder = os.listdir(base_folder)

size = 0.0
for folder in all_folder:
    js_folder = f"selenium/{folder}/Default/Code Cache/js/"
    if os.path.isdir(js_folder):
        js_content = os.listdir(js_folder)
        for content in js_content:
            c = js_folder + content
            size += os.path.getsize(c)

gb = size / 1024 / 1024 / 1024
print(f"folder size = {gb:.1f} GB")
```

this js folder taking up about 5.6 GB of space

**Comment by thebrumby** [comment]
Hi, 

The `selenium` folder contains the browser sessions of all games, if you were to delete all sub-folders within this folder, you would be essentially deleting the current version of all games. On the next run of the script, the it would attempt to restore the session from the backups folder, which would probably contain less cached content then the session in the selenium folder - that said, if the script was unable to restore from the backup, you'd then need to start again with that session.

**Comment by Jelingam** [comment]
how about deleting unnecessary cache ?

as you see in js folder.

**Comment by thebrumby** [comment]
Hi @Jelingam,

I've never tried it. You could take a copy of the folder and see what happens after deleting it.
