### ISSUE TITLE
Bug: [Describe the issue briefly]....problem in collecting hot 

### ISSUE THREAD

**Issue by basu180** [thebrumby/HotWalletClaimer#265]
describe the Bug (required):**
hot is not claiming 

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
Please confirm that you've reviewed the troubleshooting guide linked above and completed all steps to ensure the issue is not with your session.

**Steps to Reproduce (required):**
List the steps to reproduce the bug.

**Expected Behavior (required):**
Describe what you expected to happen.

**Screenshots or Logs:**
If applicable, add screenshots or logs to help explain your problem.
![photo_2024-10-19_10-56-51](https://github.com/user-attachments/assets/da00b0a4-5f6b-4dbc-92a4-365ce3d44a59)

**Comment by basu180** [comment]
please solve the issue as soon as possible ..phill sir

**Comment by thebrumby** [comment]
Hi,

Top up your account with Near!

**Comment by basu180** [comment]
I already have sufficient near in my wallet ..0.21 near

**Comment by thebrumby** [comment]
Hi @basu180,

If you choose to top up a little more, you'll find the "bug" you reported is magically fixed.

**Comment by basu180** [comment]
What's the minimum near required for claim hot ?
