### ISSUE TITLE
Help Me: I want to Run 100 Hot accounts. how much ram and memory needed.

### ISSUE THREAD

**Issue by nileshpk** [thebrumby/HotWalletClaimer#266]
**Introduction:**
Before raising a help request, please ensure you've followed the necessary setup and troubleshooting steps. This will help us assist you more effectively and efficiently.

**Which self-help guides have you tried to follow? (required):**
Please list the guides or resources you've consulted so far. 

**Describe Your Issue (required):**
Please provide a clear and concise description of the help you need.

**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Before submitting, please confirm that you've reviewed the FAQ linked above.

**Steps Taken So Far (optional):**
Describe what you have tried so far to resolve your issue.

**Additional Information:**
Include any other information that might help us assist you, such as screenshots, logs, or system details.

**Comment by Keyz400** [comment]
> **Introduction:** Before raising a help request, please ensure you've followed the necessary setup and troubleshooting steps. This will help us assist you more effectively and efficiently.
> 
> **Which self-help guides have you tried to follow? (required):** Please list the guides or resources you've consulted so far.
> 
> **Describe Your Issue (required):** Please provide a clear and concise description of the help you need.
> 
> **Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):** Before submitting, please confirm that you've reviewed the FAQ linked above.
> 
> **Steps Taken So Far (optional):** Describe what you have tried so far to resolve your issue.
> 
> **Additional Information:** Include any other information that might help us assist you, such as screenshots, logs, or system details.

Running 100 concurrent game sessions

To ensure smooth performance, consider the following:

*Hardware Requirements:*

- CPU: Multi-core processor (at least 8-16 cores)
- RAM: 16-32 GB (or more)
- Storage: Fast disk (SSD) with sufficient space (at least 100 GB)

*Configuration Adjustments:*

1. Increase concurrent claims setting to 100 in the script settings.
2. Adjust PM2 settings for efficient process management.
3. Monitor system resources and adjust as needed.

*Performance Considerations:*

1. Memory usage: approximately 3.5-4.5 GB (35-45 MB/session)
2. CPU usage: moderate to high, depending on game requirements
3. Disk usage: increased logging and cache storage

**Comment by thebrumby** [comment]
Hi @nileshpk,

@Keyz400 is right, for 100 HOT accounts, you'll need a reasonably substantial setup. The specifics will vary depending on what upgrades you have applied to the account. If you have 100 accounts and on two-hour claims (50 claims per hour) you will need more resources than if you're already max upgraded to 24 hours between claims (potentially reduce to 4 claims per hour).

**Comment by nileshpk** [comment]
I have update pot to 12 hours. I want to know how much hot can I run in amazon free trial vps. And 
<img width="960" alt="Untitled" src="https://github.com/user-attachments/assets/544b4f64-e671-439c-b40d-9a8d1a2135f9">
How to create several containers.

**Comment by thebrumby** [comment]
Hi @nileshpk,

To create multiple containers, you'd do something like this:
```
docker run -d --name tcb-account1 --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it tcb-account1 /bin/bash
```
```
docker run -d --name tcb-account2 --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it tcb-account2 /bin/bash
```

If you want to experiment with VPS on Amazon, I would select the ARM64 option rather than the AMD64/x64 variant; this is because it is locked to an older version of Chrome that uses less memory. With only 1 gb of ram available in the free trial, this will be your limiting factor. You might be able to set up 6 - 8 accounts there, all from a single container to save memory.

**Comment by nileshpk** [comment]
Can you suggest some vps provider.

**Comment by Keyz400** [comment]
> Can you suggest some vps provider.

Ultahost, Hostingner

Free trail:
AWS, Google cloud, Microsoft
