### ISSUE TITLE
Feature Request: Batch Session Creation

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#271]
I think I'm getting the hang of using the HOT claimer. As far as I understand, the script should distinguish fine between multiple HOT-accounts that are under "one hood" of a single telegram account since HOT supports importing multiple accounts.

Now I wonder if there's a way to batch create sessions by providing the seed phrases in a more time-efficient manner.

**Comment by thebrumby** [comment]
Hi @BraveCanister,

Your understanding is correct. You can only create one set of HOT keys per Telegram account, but as the script uses a different browser session for each saved game session, you can "manage" multiple game sessions from a single Telegram account (so you only need to sign in once). 

There is a slight timesaver where you can pre-submit the Wallet name and seed phrase in the launch command, but you will still need to enter them one by one, and select the saved Telegram account and final options once the seed phrase has been added (default add to PM2 and save PM2 config).

```
./launch.sh hot HOT:Wallet1 --seed-phrase word1 word2 ... word12
```
```
./launch.sh hot HOT:Wallet2 --seed-phrase word1 word2 ... word12
```
