### ISSUE TITLE
Feature Request: auto connect every gam without seedphrase 

### ISSUE THREAD

**Issue by Wellynounet** [thebrumby/HotWalletClaimer#272]
**Describe the Feature You'd Like (required):**
Please provide a clear and concise description of the feature or enhancement you are suggesting. What problem does it solve?
"I want to auto-connect to every game that doesn't require a seed phrase, to maximize my profit without having to select every new game.

**How Would You Use It (optional):**
"I want to auto-connect to every game that doesn't require a seed phrase, to maximize my profit without having to select every new game.

**Additional Context:**
I'm tired of connecting to every game manually. I want to auto-connect to every game that doesn't require a seed phrase to maximize my profit without selecting each new game.

**Comment by thebrumby** [comment]
Hi,

Each script acts independently to create the initial folders, write the cookies and set up the PM2 component. It doesn’t really work with the batch concept.
