### ISSUE TITLE
Help Me: I am trying aws and following steps provided in video and I couldn't set up hot wallet claim it show some error please help.

### ISSUE THREAD

**Issue by nileshpk** [thebrumby/HotWalletClaimer#273]
[**Introduction:**]
<img width="960" alt="s" src="https://github.com/user-attachments/assets/7a548405-1cc8-40b7-be14-5cab6e5cd0e7">
 Installed Versions:
PM2 version: [PM2] Spawning PM2 daemon with pm2_home=/home/ubuntu/.pm2
[PM2] PM2 Successfully daemonized
5.4.2
Python version: Python 3.12.3
Node.js version: v23.0.0
npm version: 10.9.0
./install.sh: line 90: chromium-browser: command not found
./install.sh: line 90: google-chrome: command not found
Chromium/Chrome version: 
Chromedriver version: ChromeDriver 130.0.6723.58 (3a50e012e4c9b8a410a4e2b12bf577e69ee8f755-refs/branch-heads/6723@{#1353})
Architecture: x86_64

Here some error chrome browser.
Before raising a help request, please ensure you've followed the necessary setup and troubleshooting steps. This will help us assist you more effectively and efficiently.

**Which self-help guides have you tried to follow? (required):**
Please list the guides or resources you've consulted so far. 

**Describe Your Issue (required):**
Please provide a clear and concise description of the help you need.

**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Before submitting, please confirm that you've reviewed the FAQ linked above.

**Steps Taken So Far (optional):**
Describe what you have tried so far to resolve your issue.

**Additional Information:**
Include any other information that might help us assist you, such as screenshots, logs, or system details.

**Comment by thebrumby** [comment]
Follow the troubleshooting guide.

**Comment by thebrumby** [comment]
### Final thought:
If you're having trouble setting up the dependencies and requirements to run this script, consider using Docker Desktop (on Windows or macOS) or Docker CLI (on a VPS). The [Docker setup](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/DOCKER.md) includes everything pre-built and tested, making it much easier to get up and running.

If the troubleshooting steps here don’t resolve your issue and you can’t find the answer in previously closed issues, feel free to open a support ticket. However, please note that vague posts like "doesn't work" without any detailed information may be closed, locked, or deleted.
