### ISSUE TITLE
Gets stuck at Step 12 on AWS

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#278]
I'm trying to set up a HOT wallet claimer via AWS and after inputting the seed phrase it gets stuck at Step 12:

![image](https://github.com/user-attachments/assets/813eb3ac-162e-49d0-87f6-7b33ac90e2c4)

"Attempting to click the storage link"

In one of my many attempts it went a little further, claiming that an error occurred while trying to clear overlays:

![Screenshot 2024-10-31 001816](https://github.com/user-attachments/assets/a6d6a593-9ca7-44bb-a097-8f43ff7372c4)

I think it bricks my EC2 instance because restarting the ShellNGN window gives me a "connection closed" timeout error and I have to reboot the instance via AWS panel.

**Comment by BraveCanister** [comment]
Alright, after about an hour of stepping away it suggests it timed out trying to find an iframe: 

![image](https://github.com/user-attachments/assets/7450767c-0608-4f73-85e5-8a3f6ab3fed6)

**Comment by BraveCanister** [comment]
I started everything from scratch step by step and it got stuck nonetheless, now at step 5:

![image](https://github.com/user-attachments/assets/a4b6306e-eeb4-4e63-bf57-fdb529bedb54)

**Comment by thebrumby** [comment]
Hi,

The setup process should only take a couple of minutes—I recently recreated over 60 accounts in about an hour.

What server specifications are you using? It sounds like you might be running out of RAM.

You can check your memory usage with the following command:

```
free -m
```

As mentioned in some of the closed issues, if you’re on a limited RAM AWS account, consider using an ARM64 server. This setup is tied to an older version of Chrome, which tends to use less memory.

**Comment by BraveCanister** [comment]
![image](https://github.com/user-attachments/assets/9ca41bca-d583-45eb-8add-5be70af6ce79)

I followed the video setting up an Amazon VPS 1:1 with a default instance type t3.micro.

I'll try ARM64 for sure.

**Comment by thebrumby** [comment]
At the time of recording the video, the setup was successfully hosting 8 or 9 accounts using that method. Unfortunately, since then, the baseline RAM requirements of the third-party software seem to have increased, impacting its ability to run on a 1 GB server.

**Comment by BraveCanister** [comment]
Right, so would I have to go with an instance of at least 2gb of memory? Is there any clue as to how much it would cost per month running say 10 HOT accounts given that the free tier is limited to micro with 1gb of memory? 

![image](https://github.com/user-attachments/assets/8cba94ef-67c8-4ff7-89ca-018479c1a0ff)

![image](https://github.com/user-attachments/assets/6887fbab-3139-4d42-8dfe-ce16d31e7a11)

**Comment by thebrumby** [comment]
Hi,

The costs can vary depending on the data center hosting the script, but there’s an option that might work well for testing:

When creating an instance, search for:

```
Minimal Ubuntu 22.04 LTS - Jammy
```

<img width="655" alt="image" src="https://github.com/user-attachments/assets/68c512bd-a917-4ce3-99b9-5bdec8519db4">

I set up a test instance on an AMD-64 bit, t2.micro instance (free-tier eligible), and was able to create six accounts with some RAM to spare.

If the free tier doesn’t quite cover the number of accounts you want, it might be worth moving to a different provider after testing. Many offer servers with 2 GB RAM for around $2-3 per month, which could be a good alternative.

**Comment by BraveCanister** [comment]
Awesome, I got it working finally. Are there any particular providers at that cost that I could check out?

**Comment by BraveCanister** [comment]
Well, while I managed to add the processes successfully after upgrading an instance to x64 ARM and bigger RAM, it still fails:

![image](https://github.com/user-attachments/assets/2fec3564-6de7-4d49-a089-3d91495d7e12)


Error encountered: expected string or bytes-like object, got 'bool' right after it attempts to locate storage.

**Comment by thebrumby** [comment]
Hi, 

You need to follow the troubleshooting guide: h[ttps://github.com/thebrumby/HotWalletClaimer/issues/166](https://github.com/thebrumby/HotWalletClaimer/issues/166)

1) Enable verbose 3
2) Enable debugging and look at the screenshots from the virtual browser

**Comment by BraveCanister** [comment]
Alright well, it didn't get to the storage step this time:

![image](https://github.com/user-attachments/assets/dce7efa0-2989-4edd-abec-8ec4d4df5f7c)

**Comment by BraveCanister** [comment]
I just re-ran the exact same thing again and no chrome crash happened. 

![image](https://github.com/user-attachments/assets/3134ed44-51f4-4dc7-8124-263f69cc3555)


Despite the log saying "Was successfully able to enter the seed phrase", based on the screenshots it doesn't do anything:

![image](https://github.com/user-attachments/assets/2ff84896-b0cf-4eaf-842d-18a4d079d301)

All the rest of the screenshots for the consequent steps are just staring at the import wallet starting screen on the app. 


However, there is one account that I claimed manually just a short while ago, and the debug screenshots show that it does enter the seed and access the wallet: 

![image](https://github.com/user-attachments/assets/3a3d60ae-dcd0-4974-ba1f-f90c43c95ffb)

I don't know what to make of any of this. The other handful of accounts that I run from my PC work fine.

**Comment by BraveCanister** [comment]
For the accounts that don't get stuck on the entry screen. I set up the forced claim in settings but judging from screenshots it's stuck because of the "check news" button.

![image](https://github.com/user-attachments/assets/3f93b109-44aa-4789-b66c-56f8f252e83d)

![image](https://github.com/user-attachments/assets/6e08f9f9-ff76-46d5-bd2c-bf1d55e645ed)
