### ISSUE TITLE
Help Me: huge docker_data.vhdx

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#279]
**Which self-help guides have you tried to follow? (required):**
Please list the guides or resources you've consulted so far. 
I tried to solve this problem using Optimize-vhd:
https://gist.github.com/jjmartres/177c68d3f44a4f8a82d9d0bc42a97637
I tried to solve this problem using diskpart:
https://stackoverflow.com/questions/70946140/docker-desktop-wsl-ext4-vhdx-too-large
I tried to solve this problem using wslcompact -c -d:
https://github.com/okibcn/wslcompact

No method has brought any result

Most of the guides pay attention to the problem of large size of ex4.vhdx file, which is the main file in WSL2, but I have a problem with large size of docker_data.vhdx data file. not with ex4.vhdx file and I couldn't find a solution to my problem anywhere.

**Describe Your Issue (required):**
Hi Phil!!! Please tell me how to solve the problem of huge file size AppData\Local\Docker\wsl\disk\docker_data.vhdx
without deleting or corrupting the data. 

**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Yes

**Additional Information:**
This is the actual size of the container:
![image](https://github.com/user-attachments/assets/45c6f1af-ced7-4a4e-bc55-8f335f2e7e0b)
but physically it is many times bigger.
![image](https://github.com/user-attachments/assets/2a5404cb-64af-4d2d-8164-74712c55c36f)

**Comment by thebrumby** [comment]
Hi @farmdigit ,

Have you tried[ this solution](https://github.com/thebrumby/HotWalletClaimer/issues/232#issuecomment-2356359005)?

> I also faced the same problem , it was because septber 7 the previous version of docker didn't support reclaim storage feature in wsl2. if you can update to latest version now they mentioned it supported reclaim feature. before that I untick "use wsl2 instead of hyper-v" while installing docker. do it and use hyper-v and the problem solved.

I assume you should be able to upgrade the Docker Desktop using hyper-v without losing the data in the container.

**Comment by farmdigit** [comment]
> Have you tried[ this solution](https://github.com/thebrumby/HotWalletClaimer/issues/232#issuecomment-2356359005)?

I don't understand what it's supposed to do.

How can I reclaim storage feature in wsl2?



> I assume you should be able to upgrade the Docker Desktop using hyper-v without losing the data in the container.

how do I do that?

**Comment by thebrumby** [comment]
I've no idea, it was just a previously suggested theory that hyper-v was more efficient on disk space than docker built on WSL2. I use Ubuntu Server as an operating system so I don't have experience with this issue.
