### ISSUE TITLE
Help Me: 

### ISSUE THREAD

**Issue by Imaroubat** [thebrumby/HotWalletClaimer#280]
Hello. Some account work at first start . Some stuck at this point. I trying restart install process many times.
I understand this is not code problem.

Step 01 - Attempting to verify if we are logged in (hopefully QR code is not present).
Step 01 - nothing found to action. The QR code test passed.

Step 02 - Attempting to check for the start button (should not be present)...
Step 02 - Timeout while attempting to check for the start button (should not be present).
Step 03 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app'] | //div[@class='new-message-bot-commands-view'][contains(text(),'Open Wallet')]...
Step 03 - Successfully able to open a link for the app..

Step 04 - Attempting to click the 'Launch' button (probably not present)...
Step 05 - Attempting to replace platform in iframe URL if necessary...
Step 05 - Platform 'web' found in iframe URL and replaced with 'ios'.
Step 06 - Attempting to switch to the app's iFrame with id 'None' or within 'web-app-body'...
Step 06 - Successfully switched to the app's iFrame within 'web-app-body'.
Step 08 - Attempting to find the HereWallet log-in button...
Step 08 - Timeout while attempting to find the HereWallet log-in button.
Step 08 - An error occurred: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome-headless-shell=126.0.6478.114)
Stacktrace:
#0 0x559b2493969a <unknown>
#1 0x559b2461c0dc <unknown>
#2 0x559b246217e9 <unknown>
#3 0x559b2462385c <unknown>
#4 0x559b246ab5a9 <unknown>
#5 0x559b2468b872 <unknown>
#6 0x559b246aa5c3 <unknown>
#7 0x559b2468b613 <unknown>
#8 0x559b2465b4f7 <unknown>
#9 0x559b2465be4e <unknown>
#10 0x559b248ff86b <unknown>
#11 0x559b24903911 <unknown>
#12 0x559b248eb35e <unknown>
#13 0x559b24904472 <unknown>
#14 0x559b248cfcbf <unknown>
#15 0x559b24929098 <unknown>
#16 0x559b24929270 <unknown>
#17 0x559b249387cc <unknown>
#18 0x7f2552e53a94 <unknown>
#19 0x7f2552ee0c3c <unknown>

**Comment by Alexahalid** [comment]
@Imaroubat It sounds like you're having some trouble with the installation process. Since it’s not a code problem, have you tried checking for updates or reinstalling the app? Sometimes, restarting your device can also help.
