### ISSUE TITLE
Help Me: Blum script can also play game ?

### ISSUE THREAD

**Issue by Rohan7559** [thebrumby/HotWalletClaimer#281]
How script can get Blum points from 1 ticket/pass

**Comment by thebrumby** [comment]
Hi,

The script does not play racing/action-style games. 

Thanks

**Comment by Rohan7559** [comment]
> Hi,
> 
> The script does not play racing/action-style games.
> 
> Thanks

Sir can you please explain, exactly what is the use of your script ?

**Comment by thebrumby** [comment]
On Blum, the script claims the daily reward, initiates mining, and then claims the mining reward once the process is complete.

**Comment by Rohan7559** [comment]
Sir can you please make your code more advance, for popular games like Blum that can do/play games yt task etc....
