### ISSUE TITLE
Help Me: how to install it on pterodactyl panel

### ISSUE THREAD

**Issue by sakiresy** [thebrumby/HotWalletClaimer#283]
**Introduction:**
Before raising a help request, please ensure you've followed the necessary setup and troubleshooting steps. This will help us assist you more effectively and efficiently.

**Which self-help guides have you tried to follow? (required):**
Please list the guides or resources you've consulted so far. 

**Describe Your Issue (required):**
Please provide a clear and concise description of the help you need.

**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Before submitting, please confirm that you've reviewed the FAQ linked above.

**Steps Taken So Far (optional):**
Describe what you have tried so far to resolve your issue.

**Additional Information:**
Include any other information that might help us assist you, such as screenshots, logs, or system details.

**Comment by thebrumby** [comment]
Hi,

Pterodactyl is primarily designed to host and manage game servers, right? 

You can install this claim bot system by using the Docker quickstart guide. After copying and pasting three blocks of commands, you'll have everything up and running without the need for an additional management panel.

I'm not sure what benefit there'd be to using Pterodactyl, installing the application directly will save you time and reduce potential complications.
