### ISSUE TITLE
Help Me:  Hot game error while trying to login using script

### ISSUE THREAD

**Issue by nileshpk** [thebrumby/HotWalletClaimer#284]
**Introduction:**
Before raising a help request, please ensure you've followed the necessary setup and troubleshooting steps. This will help us assist you more effectively and efficiently.

**Which self-help guides have you tried to follow? (required):**
Please list the guides or resources you've consulted so far. 

**Describe Your Issue (required):**
When I tried to login hot it shows error and automatically save in pm2 without seed phrase
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 03 - Attempting to verify if we are logged in (hopefully QR code is not present).
Step 04 - Attempting to check for the start button (should not be present)...

_> **Step 05 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app'] | //div[@class='new-message-bot-commands-view'][contains(text(),'Open Wallet')]...
> Step 05 - An error occurred while trying to open the app: Message: javascript error: {"status":60,"value":"https://t.me/herewalletbot/app has no size and location"}**
>   (Session info: chrome=129.0.6668.89)_

Stacktrace:
#0 0x5640ddf0202a <unknown>
#1 0x5640ddbe85e0 <unknown>
#2 0x5640ddbee443 <unknown>
#3 0x5640ddbf0105 <unknown>
#4 0x5640ddbf018c <unknown>
#5 0x5640ddc3ddce <unknown>
#6 0x5640ddc3d1e6 <unknown>
#7 0x5640ddc84227 <unknown>
#8 0x5640ddc5cb22 <unknown>
#9 0x5640ddc7bd7d <unknown>
#10 0x5640ddc5c8c3 <unknown>
#11 0x5640ddc2a6b3 <unknown>
#12 0x5640ddc2b68e <unknown>
#13 0x5640ddecca2b <unknown>
#14 0x5640dded09b1 <unknown>
#15 0x5640ddeb9225 <unknown>
#16 0x5640dded1532 <unknown>
#17 0x5640dde9e38f <unknown>
#18 0x5640ddef0f28 <unknown>
#19 0x5640ddef10f3 <unknown>
#20 0x5640ddf00e7c <unknown>
#21 0x7f836f2f3a94 <unknown>
#22 0x7f836f380a34 __clone

Step 05 - Attempting to find the chat window message input box...
Step 06 - Attempting to send the '/start' command...
Step 07 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app'] | //div[@class='new-message-bot-commands-view'][contains(text(),'Open Wallet')]...
Step 07 - An error occurred while trying to open the app: Message: javascript error: {"status":60,"value":"https://t.me/herewalletbot/app has no size and location"}
  (Session info: chrome=129.0.6668.89)
Stacktrace:
#0 0x5640ddf0202a <unknown>
#1 0x5640ddbe85e0 <unknown>
#2 0x5640ddbee443 <unknown>
#3 0x5640ddbf0105 <unknown>
#4 0x5640ddbf018c <unknown>
#5 0x5640ddc3ddce <unknown>
#6 0x5640ddc3d1e6 <unknown>
#7 0x5640ddc84227 <unknown>
#8 0x5640ddc5cb22 <unknown>
#9 0x5640ddc7bd7d <unknown>
#10 0x5640ddc5c8c3 <unknown>
#11 0x5640ddc2a6b3 <unknown>
#12 0x5640ddc2b68e <unknown>
#13 0x5640ddecca2b <unknown>
#14 0x5640dded09b1 <unknown>
#15 0x5640ddeb9225 <unknown>
#16 0x5640dded1532 <unknown>
#17 0x5640dde9e38f <unknown>
#18 0x5640ddef0f28 <unknown>
#19 0x5640ddef10f3 <unknown>
#20 0x5640ddf00e7c <unknown>
#21 0x7f836f2f3a94 <unknown>
#22 0x7f836f380a34 __clone

Step 08 - Attempting to click the 'Launch' button (probably not present)...
Step 09 - Attempting to replace platform in iframe URL if necessary...
Step 10 - Attempting to switch to the app's iFrame with id 'None' or within 'web-app-body'...
Step 12 - Attempting to find the HereWallet log-in button...
Step 12 - An error occurred: Message: javascript error: Cannot read properties of null (reading 'click')
  (Session info: chrome=129.0.6668.89)
Stacktrace:
#0 0x5640ddf0202a <unknown>
#1 0x5640ddbe85e0 <unknown>
#2 0x5640ddbee443 <unknown>
#3 0x5640ddbf03c9 <unknown>
#4 0x5640ddc7ccfc <unknown>
#5 0x5640ddc5cb22 <unknown>
#6 0x5640ddc7bd7d <unknown>
#7 0x5640ddc5c8c3 <unknown>
#8 0x5640ddc2a6b3 <unknown>
#9 0x5640ddc2b68e <unknown>
#10 0x5640ddecca2b <unknown>
#11 0x5640dded09b1 <unknown>
#12 0x5640ddeb9225 <unknown>
#13 0x5640dded1532 <unknown>
#14 0x5640dde9e38f <unknown>
#15 0x5640ddef0f28 <unknown>
#16 0x5640ddef10f3 <unknown>
#17 0x5640ddf00e7c <unknown>
#18 0x7f836f2f3a94 <unknown>
#19 0x7f836f380a34 __clone

CHROME DRIVER DETACHED: It is now safe to exit the script.
You could add the new/updated session to PM use: pm2 start games/hot.py --interpreter venv/bin/python3 --name HOT:Wallet101 -- HOT:Wallet101
Enter 'y' to continue to 'claim' function, 'e' to exit, 'a' or <enter> to automatically add to PM2: 

Step 05 - An error occurred while trying to open the app: Message: javascript error: {"status":60,"value":"https://t.me/herewalletbot/app has no size and location"}

  (Session info: chrome=129.0[PM2] Starting /usr/src/app/games/hot.py in fork_mode (1 instance)
[PM2] Done.
┌────┬──────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id │ name             │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├────┼──────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 1  │ HOT:Wallet101    │ default     │ N/A     │ fork    │ 993      │ 0s     │ 0    │ online    │ 0%       │ 12.3mb   │ root     │ enabled  │
│ 0  │ daily-update     │ default     │ N/A     │ fork    │ 35       │ 6D     │ 0    │ online    │ 0%       │ 3.3mb    │ root     │ disabled │
└────┴──────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
[PM2][WARN] Current process list is not synchronized with saved list. Type 'pm2 save' to synchronize.
Should we save your PM2 processes? (Y/n): [PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2

You can now watch the session log into PM2 with: pm2 logs HOT:Wallet101
Deactivating virtual environment...
root@63cad2087a80:/usr/src/app# Step 05 - An error occurred while trying to open the app: Message: javascript error: {"status":60,"value":"https://t.me/herewalletbot/app has no size and location"}
bash: Step: command not found
root@63cad2087a80:/usr/src/app# 
root@63cad2087a80:/usr/src/app#   (Session info: chrome=129.0

Step 05 - An error occurred while trying to open the app: Message: javascript error: {"status":60,"value":"https://t.me/herewalletbot/app has no size and location"}

  (Session info: chrome=129.0
**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Before submitting, please confirm that you've reviewed the FAQ linked above.

**Steps Taken So Far (optional):**

**Additional Information:**
Include any other information that might help us assist you, such as screenshots, logs, or system details.

**Comment by thebrumby** [comment]
Hi,

You need to follow the troubleshooting guide

- activate the in game screenshots if you want to know what’s happening. Screen-shoting the CLI only shows there is a problem, but doesn’t show what. 
- make sure you aren’t stuck at a search prompt in your mobile phone/telegram desktop GUI. 
- delete/overwrite the saved Telegram session and authenticate a new session with QR code or OTP method. 

By not following or documenting that you followed the steps in the troubleshooting guide, you made it impossible to daignose the issue.

**Comment by nileshpk** [comment]
After enabling screenshot I am unable to what is error. When I try first time every session error and second time it run smoothly. Why it first time stuck.

![03_QR-code-check-during-session-start](https://github.com/user-attachments/assets/093a4ae1-3aba-4ba8-8280-1c64ec5ac389)
![04_Timeout-during-check-for-the-start-button-(should-not-be-present)](https://github.com/user-attachments/assets/ef92c6da-65a8-4c8f-b373-50dd41e84b6e)
![05_iterating-through-launch-game-buttons](https://github.com/user-attachments/assets/495f65be-76f2-4f68-9417-931252b32b87)
![05_Moved-to-find-the-chat-window-message-input-box-without-clicking](https://github.com/user-attachments/assets/487279eb-f76c-4440-946b-04e04e149887)
![05_unspecified-error-while-trying-to-launch-the-game](https://github.com/user-attachments/assets/006d79d6-21bc-4116-83a6-fb3f09b8950d)
![06_we-sent-the-start-command-to-the-chat-window](https://github.com/user-attachments/assets/d9bf1a55-4e20-44be-8af6-dc41eb36cb0c)
![07_iterating-through-launch-game-buttons](https://github.com/user-attachments/assets/98df6188-9b15-41ad-bc72-1addb068fbd0)
![07_unspecified-error-while-trying-to-launch-the-game](https://github.com/user-attachments/assets/f57e73c5-f29b-45ca-935c-7be670b42b1b)
![08_Timeout-during-click-the-'Launch'-button-(probably-not-present)](https://github.com/user-attachments/assets/5248569d-53d8-4a0e-8921-5f7eb7a4a4bd)
![10_timeout-while-trying-to-switch-to-iFrame](https://github.com/user-attachments/assets/66806f53-e9e8-44c7-b5b2-27ba400d6129)
![12_Timeout-during-find-the-HereWallet-log-in-button](https://github.com/user-attachments/assets/3a665a7c-362c-435c-aea7-4e5744018cbc)

**Comment by thebrumby** [comment]
Thanks for sharing the screenshots—they helped me understand the issue better. While I’m not entirely sure why this is affecting you specifically, but I’ve simplified the XPath that launches the game to remove the part that is failing for you. This should resolve the issue and hopefully won't cause a problem for anyone else.

I’ve pushed an update to the repository. Please update your local repository using git pull (for standalone setups) or `./pull-games.sh` if you’re using Docker. Once updated, check if the affected sessions have automatically restarted, or if not restart them manually.

Thanks.
