### ISSUE TITLE
Per-Session Proxy Connections

### ISSUE THREAD

**Issue by BraveCanister** [thebrumby/HotWalletClaimer#285]
From what I understand setting up an upstream proxy will cover all Telegram sessions at once, so I'm interested in using different proxies for different telegram sessions and I'm wondering how to do that. I'm not sure where to start with setting up a different docker container as the instructions in proxy suggest, though maybe I overcomplicate it a bit. I'm using a Hezner VPS currently, not Windows if that helps.

**Comment by thebrumby** [comment]
To use different proxies for different Telegram sessions, you need to run separate Docker containers for each session. This approach allows you to assign a unique proxy to each container, ensuring that each Telegram account operates through its designated proxy.

### Step 1: Run Multiple Docker Containers

Start by running multiple instances of the Docker container, each with a unique name:
```
docker run -d --name telegram-claim-bot1 --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker run -d --name telegram-claim-bot2 --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker run -d --name telegram-claim-bot3 --restart unless-stopped thebrumby/telegram-claim-bot:latest
```
### Step 2: Access Each Container Individually

Enter each container to configure the proxy settings specific to that Telegram session:
```
docker exec -it telegram-claim-bot1 /bin/bash
# Configure proxy settings for the first session as in Step 3
```
```
docker exec -it telegram-claim-bot2 /bin/bash
# Configure proxy settings for the second session as in Step 3
```
```
docker exec -it telegram-claim-bot3 /bin/bash
# Configure proxy settings for the third session as in Step 3
```
### Step 3: Configure Proxy Settings Within Each Container

Inside each container, set up the proxy settings:

```
./launch.sh setup-proxy
```

### Explanation: Why Multiple Containers Are Necessary

Most third-party tools, including those used in this project like Selenium and MITMProxy, support only one proxy connection per session or container:

- **Selenium**: Can connect to a proxy but doesn't handle proxy authentication with a username and password effectively.
- **MITMProxy**: Supports proxy authentication but only with one set of credentials at a time.

By running separate containers, you ensure that each Telegram session is isolated with its own proxy settings, allowing you to manage multiple accounts with different IP addresses.

### Alternative Option

- **Use Paid Rotating Proxies**: Some proxies rotate IP addresses every 10 minutes, which might eliminate the need for multiple containers.

Cheers,  
Phil
