### ISSUE TITLE
Game Suggestion: christmas raffle ton from the official telegram app store

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#288]
**Bot Name (required):**
Telegram Apps Center

**Bot Handle (required):**
@tapps_bot 

**Reason for Inclusion:**
Hi Phil! How are you doing my friend? 
I propose to automate the Christmas raffle ton from the official telegram app store.
You need to go to the bot @tapps_bot and select daily check in.
![image](https://github.com/user-attachments/assets/062a26a9-1321-4429-ba18-6116ae1e11d4)

and then redirect to the daily task. you need to click on it

![image](https://github.com/user-attachments/assets/70100562-4c8a-49c9-9067-abc9f6cf7c23)

You don't need to open the bot itself, you can click "Cancel" & close it at once, the task will be counted.
![image](https://github.com/user-attachments/assets/b350abe4-2e2a-4177-8eac-c02bd6d4eda5)

![image](https://github.com/user-attachments/assets/e2283379-2a43-4867-8126-7014186f3b0d)

**Comment by thebrumby** [comment]
Hey @farmdigit,

I'm doing well thank you, I hope you are too? It looks like this sequence should be fairly easy to map. I'll try again tonight from within the script, and if all goes well, I share what I find tomorrow :)

**Comment by farmdigit** [comment]
> Hey @farmdigit,
> 
> I'm doing well thank you, I hope you are too? It looks like this sequence should be fairly easy to map. I'll try again tonight from within the script, and if all goes well, I share what I find tomorrow :)

I'm fine too, waiting for Christmas :) thanks. That's great news!

**Comment by thebrumby** [comment]
> I'm fine too, waiting for Christmas :) 

Just a few weeks now!

Regarding the raffle, I'm not sure if it's a glitch in the game, but the panel that was present yesterday now just seems to hang when loading, and then disappear. Am I missing something?

**Comment by farmdigit** [comment]
> > I'm fine too, waiting for Christmas :)
> 
> Just a few weeks now!
> 
> Regarding the raffle, I'm not sure if it's a glitch in the game, but the panel that was present yesterday now just seems to hang when loading, and then disappear. Am I missing something?

It's not working properly today. Try a little later in 10 minutes, for example. If you run it manually everything works fine?

**Comment by thebrumby** [comment]
OK, thanks. I'll give it some time and try again :)

**Comment by thebrumby** [comment]
The good news is the number of days in the streak, and the remaining time to the next claim is working nicely, just need to map the steps to click the game of the day later tonight :)

**Comment by farmdigit** [comment]
> The good news is the number of days in the streak, and the remaining time to the next claim is working nicely, just need to map the steps to click the game of the day later tonight :)

does that mean the next super bot is almost ready? :)

**Comment by thebrumby** [comment]
Sorry, I ran out of time to implement this so will close.

**Comment by farmdigit** [comment]
> Sorry, I ran out of time to implement this so will close.

ok
