### ISSUE TITLE
[Request Feature] Add a option proxy to command  ./launch.s-->Settings 

### ISSUE THREAD

**Issue by itcthienkhiem** [thebrumby/HotWalletClaimer#29]
Dear Ad,
I want to add a proxy on option ./launch.s-->Settings 
with: ip:port:user:password.
Thanks.

**Comment by thebrumby** [comment]
Hi,

Hi, the script does not support a proxy by default, but you can manually amend the scripts Chrome options section to allow this:

```
# add this after chrome_options = Options()...
chrome_options.add_argument('--proxy-server=192.168.1.100:8080')
```

Replace `192.168.1.100:8080` with your proxy server's IP address and port.

Thanks
