### ISSUE TITLE
Help Me: Cleaning Cashe

### ISSUE THREAD

**Issue by farmdigit** [thebrumby/HotWalletClaimer#291]
**Describe Your Issue (required):**
Hi Phil, please help me write a script to clear the cache in all accounts. I understand that as you use it, the size on your hard disk increases due to cache accumulation. The option to enable off the cache unfortunately does not help much and it remains in such directories of each selenium account as: 
usr\src\app\backups\HOT:acc1\Default\Cache\Cache_Data\ 
usr\src\app\backups\HOT:acc1\Default\Code Cache\js\
usr\src\app\backups\HOT:acc1\Default\Service Worker\CacheStorage\

usr\src\app\selenium\HOT:acc1\Default\Cache\Cache_Data\  
usr\src\app\selenium\HOT:acc1\Default\Code Cache\js\
usr\src\app\selenium\HOT:acc1\Default\Service Worker\CacheStorage\

and maybe some others, I haven't quite figured it out yet, maybe I haven't found all the places where the cache is accumulated.

**Have you checked the [FAQ](https://github.com/thebrumby/HotWalletClaimer/wiki/FAQ) (required):**
Yes.

**Steps Taken So Far (optional):**
I found a solution to write a similar script and manually specify all the paths where the raw cache is located. Could you please tell me how to write this script for your container, and also maybe there are other directories where the cache is accumulated? Maybe there is a more elegant way to solve this problem?

#!/bin/bash

# Get list processes PM2
processes=$(pm2 list | grep -Eo 'acc[0-9]+')

# stop all processes
for process in $processes; do
  echo "Stopping $process..."
  pm2 stop "$process"
done

# Clean cashe of each process
echo "Cleaning cache for all processes..."
rm -rf /path/to/profile/*/Cache/*

# Restart all processes
for process in $processes; do
  echo "Restarting $process..."
  pm2 start "$process"
done

**Additional Information:**
Also, how to integrate this script into your project?

or maybe an alternative solution is to periodically delete accounts from the usr/src/app/selenium/ directory and restore them from the usr/src/app/backups/ directory ? 

#!/bin/bash

   # Clean path selenium
   rm -rf /usr/src/app/selenium/*

   # Copy from backups to selenium
   cp -R /usr/src/app/backups/* /usr/src/app/selenium/

Please advise me how best to solve this problem.

**Comment by thebrumby** [comment]
Hi @farmdigit,

If you are happy to skip the option to be able to restore a backup of the session, you can remove these directories:
```
rm -rf /usr/src/app/backups
```
If you further need to prune the cached data, you'd need to use
```
./launch.sh status
```
to delete and remake the sessions. 

Cheers

**Comment by farmdigit** [comment]
> to delete and remake the sessions.

and how do I delete and recreate sessions?

**Comment by thebrumby** [comment]
You'd need to delete one or more of your existing sessions using [these instructions](https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/STATUS.md) and then recreate it using the usual method as a fresh start.

Regarding your comment:

> The option to enable off the cache unfortunately does not help much and it remains in such directories

Am I correct in understanding that you mean setting `enableCache` to `False` doesn’t help much? If so, please note that this option doesn’t clear the existing cache; it only prevents Selenium from caching further data. Could you confirm whether you had this option set to False right from the start when creating the session, and if it still didn’t make a difference?

**Comment by farmdigit** [comment]
> Am I correct in understanding that you mean setting `enableCache` to `False` doesn’t help much?

Yes



> Could you confirm whether you had this option set to False right from the start when creating the session

Yes, from the start but the specified directories are cached anyway.

**Comment by thebrumby** [comment]
The directories will definitely be created anyway. Without the per-session folder in the Selenium directory, you'd need to sign in to Telegram every time.

Setting `enableCache` to `False` instructs the Selenium Python module not to cache browser data unnecessarily. If you're seeing that the directory size increases regardless of this setting, there's unfortunately not much I can do about it. This appears to be an issue with the third-party module.

As mentioned above, the backup directories can be deleted once the sessions have been recreated. Just keep in mind that if the live session gets corrupted, the script won't be able to restore the backup into the live folder.
