### ISSUE TITLE
Feature Request: Manual update code every day

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#292]
**Describe the Feature You'd Like (required):**
Hi I want manual update the code (like Vertus, they will list 27-12). I can edit inside the extras?

**Comment by thebrumby** [comment]
Sure, I have added you as a collaborator and you can now edit the extras file.

**Comment by bscongluanbui** [comment]
> Sure, I have added you as a collaborator and you can now edit the extras file.

Thanks Phill
