### ISSUE TITLE
Bug: [Fail to open Pitchtalk with proxy]

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#293]
**Describe the Bug (required):**
Hi Phil. I got a problem with Pitchtalk game when using proxy. If I using none proxy, It's working perfectly. I tried to change another proxy with many provider and country but not working. It's stuck on opening.
On my old docker, I using that proxy, It's working But when I create new docker (latest) IT's not working
![108_MonElem-get-balance](https://github.com/user-attachments/assets/589102fb-e749-4fbf-a29c-6d8276dc5114)

**Have you followed the [troubleshooting guide](https://github.com/thebrumby/HotWalletClaimer/issues/166) (required):**
yes.

**Steps to Reproduce (required):**
THe game open on screen but not into the game.
**Expected Behavior (required):**
Can you check the proxy setting?
**Screenshots or Logs:**
![107_MonElem-get-claim-timer](https://github.com/user-attachments/assets/8e728846-be46-4d79-b674-0fdbcf697313)
Step 102 (Start link) to step 108, only show this

**Comment by thebrumby** [comment]
Hi,

Unfortunately, there isn’t much I can do if Pitch Talk blocks your proxies. Have you tried using https://www.webshare.io?

**Comment by thebrumby** [comment]
Hi,

To answer the question myself, I just tested it with both Webshare and Smart Proxy and Pitch Talk works fine with both proxies.

**Comment by bscongluanbui** [comment]
> Hi,
> 
> To answer the question myself, I just tested it with both Webshare and Smart Proxy and Pitch Talk works fine with both proxies.

Thanks I will try on webshare

**Comment by thebrumby** [comment]
Webshare offer 1 gb/mo free per account, so you may be able to put the pitchtalk in a contain on its own with the proxy.
