### ISSUE TITLE
Request Feature - Push claim message to telegram bot

### ISSUE THREAD

**Issue by itcthienkhiem** [thebrumby/HotWalletClaimer#32]
I want to push claim information to telegram bot, for example, claim information is as follows:
 App name - Account name - claim time - claim quantity - total coins after claim
Many thanks.

**Comment by thebrumby** [comment]
Hi,

Thank you for your suggestion to push claim information to a Telegram bot. It's an interesting idea, and I see its potential benefits. However, I'd like to understand more about how you envision this setup working.

Implementing a Telegram bot involves obtaining an API token from Telegram's BotFather and maintaining a server that runs 24/7 to handle messages from a Python script and relay them to Telegram users. Could you clarify if your suggestion involves the script sending data to each user's own server, and whether you were thinking this would be something I would host?

Given the potential volume of users from games with millions of accounts, hosting an open relay would require significant resources. Additionally, if users are to self-host, it would require them to have sufficient technical knowledge.

Could you provide more details on how you see this idea working?

**Comment by Wellynounet** [comment]
> Hi, Currently, I'm having difficulty controlling multiple session accounts in cmd. I don't know which account has already claimed the reward, which account has not claimed the reward, and how much. My idea is to push data to a private telegram bot so I can check my reward amount on my phone


You can use : " pm2 logs"  to see which account have been claim
