### ISSUE TITLE
Current Point result

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#33]
It's will be good if you add total current points of each account  to `_pm2 list_ `command. We easier to mannage that account

**Comment by Wellynounet** [comment]
why you mean by point ?  
balance of the coin ?

**Comment by bscongluanbui** [comment]
> Hi , What you mean by point ? Balance of the coin ?

yep sir. Balance of the coin. I can see it on log but if show on pm2 list command we will ease to manage account.
Thanks Sir

**Comment by Wellynounet** [comment]
pm2 logs | grep Balance 

is the command to solve the purpose 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/cfcf2a07-2a81-4cb1-8948-0d0aa68adef9)

**Comment by bscongluanbui** [comment]
> pm2 logs | grep Balance
> 
> is the command to solve the purpose
> 
> ![image](https://private-user-images.githubusercontent.com/88185485/335513422-cfcf2a07-2a81-4cb1-8948-0d0aa68adef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDY3ODcsIm5iZiI6MTcxNzE0NjQ4NywicGF0aCI6Ii84ODE4NTQ4NS8zMzU1MTM0MjItY2ZjZjJhMDctMmE4MS00Y2IxLTg5NDgtMGQwYWE2OGFkZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5MDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYTA2ZTJmYWNjNjJjZmEzZmMwOTJkZmUxNWZlMmFjYzVjMzliZDQ3NTRhZGVhNDAyZmIxMzA4YjFmZWZiNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7WbhZz9Dwl_EA3G9GwyGSq3KYtHdAHhxSNKNNAgbnUQ)

Thanks,, but I have 10 session in pm2 log. But pm2 logs | grep Balance, only show 7 session? Whats wrong with me

**Comment by Wellynounet** [comment]
pm2 logs --lines 50 | grep Balance

modify "50"  to fit the numbers of lines you want

**Comment by bscongluanbui** [comment]
Yup, I got it, but still difficult to see and manage the balance. Would be nice if add balance to pm2 list command

**Comment by thebrumby** [comment]
Hi,

Would a shell script like this be helpful? 

<img width="1070" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/2e816c49-5878-4f86-916a-e82ce744ef2c">

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Would a shell script like this be helpful?
> 
> <img alt="image" width="1070" src="https://private-user-images.githubusercontent.com/29182343/335613962-2e816c49-5878-4f86-916a-e82ce744ef2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjU3ODIsIm5iZiI6MTcxNzE2NTQ4MiwicGF0aCI6Ii8yOTE4MjM0My8zMzU2MTM5NjItMmU4MTZjNDktNTg3OC00Zjg2LTkxNmEtZTgyY2U3NDRlZjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE0MjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNWJhMWJlMTU5MTdhZWRkNTJiODFmNjk2NGRmM2FiYTExYTUzYTlkMzI1NmVjMzk5MjY4ZDNhODU5ZTU4ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d8ksW13WjmyRLFynQ0WqoLExTspHWViJcvHGQGPcHm4">

yes, it may help us to control balances

**Comment by thebrumby** [comment]
OK, we will test in Docker and add to the next build in a few days.

Looking back at the beginning of the post. We can't add it to PM2 list because it's just a generic Linux tool we have to manage processes, it's not possibe for us to pass parameters for it to show in such a way. And if we make the system broadcast the information somehow, it will become a minefield for data encryption, restricting access, potentials for data breach etc.

The safest way is we will continue testing this status.sh script and then you can log into your server whenever you want to know the update, and check with a single command. We might slightly adjust the game script outputs and functionality to further improve on the idea before general release :)

**Comment by thebrumby** [comment]
Or actually, we might provide this as a python script, and push it to the games folder, so people using Docker do not have to upgrade and lose their data.

**Comment by thebrumby** [comment]
We made the status.py script available in the repository now:

Docker users can run: `./pull-games.sh`
Stand-alone Linux users can run: `git pull`

You can then see the current status by running: `./launch.sh status`

<img width="870" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/6c4afca5-2482-4591-9a14-dd16fc90e847">

**Comment by bscongluanbui** [comment]
> ./launch.sh status

thank you
