### ISSUE TITLE
Oxygen Unknown issue

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#35]
Hi Today I got an unknown issue of Oxygen game. I checked and It's seem the script cannot load to the game.
![image](https://github.com/thebrumby/HotWalletClaimer/assets/102287592/752b49f5-54e1-445d-b74b-1649d80b66e7)

**Comment by thebrumby** [comment]
Hi, 

the issue is that they generally have an in-game lag right now and it's stuck constantly at the loading page with Telegram Web. We'll have to see if this is a temporary issue or not. Unfortunately, the script can only connect when the game is available to interact with.

<img width="327" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/6ef3d0fd-bda0-487c-8ae5-aed2a511d7d4">

Thanks

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Thanks for reporting, although we'd already seen it. The issue is that they generally have an in-game lag right now and it's stuck constantly at the loading page with Telegram Web. We'll have to see if this is a temporary issue or not. Unfortunately, the script can only connect when the game is available to interact with.
> 
> <img alt="image" width="327" src="https://private-user-images.githubusercontent.com/29182343/335857113-6ef3d0fd-bda0-487c-8ae5-aed2a511d7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzQ0MTQsIm5iZiI6MTcxNzMzNDExNCwicGF0aCI6Ii8yOTE4MjM0My8zMzU4NTcxMTMtNmVmM2QwZmQtYmRhMC00ODdjLThhZTUtYWVkMmE1MTFkN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMTUxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYTliODhiODFhZDE5NmE4Y2RhOWUzN2JhNDk5OTgxNjdmMDE2NjlmMjJiNTRmNGY1ODQ2Nzk3NWY5MDFiYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QTYNgovXMKLToVkO0ijKmstDNkGV5nhe9CYT5XdBRQE">
> Thanks

![image](https://github.com/thebrumby/HotWalletClaimer/assets/102287592/ebf70ab1-9340-4d8b-bed2-4547204ca030)
yes, Something wrong. I still access on web but another web, it's lag

**Comment by thebrumby** [comment]
They may have blocked Telegram Web - in which case we'll have to remove it from the list. 

We're currently working on Spell! Thank you for your suggestion and contribution to this project.

**Comment by bscongluanbui** [comment]
> contribution

Is there any way to by pass this?
Reminde PocketFi bot is another good project, pls remind it.

**Comment by thebrumby** [comment]
Great news! Please update to the latest code and restart :)

**Comment by thebrumby** [comment]
> > contribution
> 
> Is there any way to bypass this? Reminder: PocketFi bot is another good project, pls remind it.

Hi, we are currently looking at Spell and PocketFi - the developers of both have made it very difficult to use this system. We will continue to try and find a work-around, although they may not be possible and we'll have to move onto other games. 

Thanks

**Comment by bscongluanbui** [comment]
> > > contribution
> > 
> > 
> > Is there any way to bypass this? Reminder: PocketFi bot is another good project, pls remind it.
> 
> Hi, we are currently looking at Spell and PocketFi - the developers of both have made it very difficult to use this system. We will continue to try and find a work-around, although they may not be possible and we'll have to move onto other games.
> 
> Thanks

Thanks for your hard working

**Comment by bscongluanbui** [comment]
Oh another issue with hexacore when restart the script
An error occurred while trying to claim: '>' not supported between instances ...

**Comment by thebrumby** [comment]
> An error occurred while trying to claim: '>'

OK, our beta tester highlighted this in testing and I thought it was resolved. I pushed another update to try to prevent it. Thanks.
