### ISSUE TITLE
PocketFi issue

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#38]
Hi today I got an issue when claim. It's show
_Unable to click. CPU may not be fast enough. Let's come back in 1 hour._
But my CPU is very strong with 4 CPU/24GB ram
When restart the service it's working for a time

**Comment by thebrumby** [comment]
Hi,

The original issue was that PocketFi requires a very fast click cycle, it needs to carry out 4 actions in a fraction of a second or it will fail - hence the original error message. 

However, they have now introduced some extra steps that need navigating before a claim can be made, and their site seems to be down at the minute. We'll have to wait until it comes back up before we can do something further. 

Thanks.
