### ISSUE TITLE
FIXED: Blum issues

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [thebrumby/HotWalletClaimer#39]
***Hi,***

Blum is not working, please, check

***thnks you***

***Edit from Welly***

**Comment by thebrumby** [comment]
Hi,

Yes, we removed Blum from the list of supported games as Blum has blocked access via Telegram Web. We didn't remove from the repository yet in case we found a work-around, but currently is not working. 

Thanks

![image](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/71d9ec73-465f-42f2-98a3-25856eaf8d96)

**Comment by S26T** [comment]
> Hi,
> 
> Yes, we removed Blum from the list of supported games as Blum has blocked access via Telegram Web. We didn't remove from the repository yet in case we found a work-around, but currently is not working.
> 
> Thanks
> 
> ![image](https://private-user-images.githubusercontent.com/29182343/337539043-d102c4a9-0655-42c6-9be7-1537442c7386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MzU1NjMsIm5iZiI6MTcxNzkzNTI2MywicGF0aCI6Ii8yOTE4MjM0My8zMzc1MzkwNDMtZDEwMmM0YTktMDY1NS00MmM2LTliZTctMTUzNzQ0MmM3Mzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA5VDEyMTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNGM0NDEwNTkxMzE3ZGI5ZTljZWZmMzA4OGQxZDZjZjMyYTgyYjU4MGQ2NmFiZjIwMWQ3NDBhNTg5ZDY5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y4c95pRJhzGUfyGN8-WGDZtkGhzp3b-55VxYJI9EesY)

Hello! I have solution for this. I added this extension with rules for my puppeteer script and it's works `https://www.youtube.com/shorts/1pd2RkSFDIg`.
Maybe you know how make it without chrome extension....

**Comment by thebrumby** [comment]
Ah, great! I'll take a look once I finish my "real" job for the week and can spend some time again on this project here. Be nice to have it running again :)

**Comment by bscongluanbui** [comment]
> Great info from the YouTube thank you! We have Blum working in our test environment. We'll look to update the Docker and installer files in the next few days to return Blum to service!

yeah I'm using docker and get this error

Step 01 - An error occurred: Message: unknown error: net::ERR_PROXY_CONNECTION_FAILED
  (Session info: headless chrome=112.0.5615.49)
Stacktrace:
#0 0x005585af2bf4 <unknown>
#1 0x00558585e040 <unknown>
#2 0x00558585b2f8 <unknown>
#3 0x00558584e734 <unknown>
#4 0x00558584fb9c <unknown>
#5 0x00558584ea60 <unknown>
#6 0x00558584da9c <unknown>
#7 0x00558584d968 <unknown>
#8 0x00558584c9bc <unknown>
#9 0x00558584cc6c <unknown>
#10 0x00558585ff58 <unknown>
#11 0x0055858c7bf4 <unknown>
#12 0x0055858c7544 <unknown>
#13 0x005585889064 <unknown>
#14 0x00558588a550 <unknown>
#15 0x005585b1adf4 <unknown>
#16 0x005585ad539c <unknown>
#17 0x005585ad4ecc <unknown>
#18 0x005585b175dc <unknown>
#19 0x005585ad5d78 <unknown>
#20 0x005585ab94c8 <unknown>
#21 0x005585ae05e4 <unknown>
#22 0x005585ae0788 <unknown>
#23 0x005585aeafa0 <unknown>
#24 0x007fb675597c <unknown>
#25 0x007fb67bb7dc <unknown>

**Comment by thebrumby** [comment]
Hi @bscongluanbui ,

For sure you'll get that error. The post above mentions the time frame for a return-to-service, which will be 1 to 2 days! The script is working fine, but you need to set up a proxy that removes the response headers - we will provide an additional script that Blum users can use for that, but it will first need writing, testing, and deployment!

**Comment by thebrumby** [comment]
Hi all,

To resolve the issue with Blum, you need to take the following steps:

1. **Remove existing Blum sessions** (if any):

 ```
./remove-process.sh
```

   - Select option 1 to remove any active Blum sessions.
   - Select option 2 to remove any inactive Blum sessions and any Telegram accounts you will use to log into Blum (this won't affect other active game sessions).

If you try and reuse a save TG account, you will likely get returned to the QR log in page when accessing it using the Proxy Server - you will then see a lot of errors in the flow. 

2. **Enable proxy and install dependencies**:

```
./launch.sh enable-proxy
```

   This will install the required dependencies within the standard virtual environment and create a new PM2 process called `http-proxy`.

3. **Set up new Blum accounts**:

```
./launch.sh blum
```

   Set up new accounts for each Blum user you wish to automate.

Following these steps should resolve the issues you're experiencing with Blum. If you encounter any further problems, feel free to ask for assistance.

**Comment by bscongluanbui** [comment]
> Hi all,
> 
> To resolve the issue with Blum, you need to take the following steps:
> 
> 1. **Remove existing Blum & Telegram sessions** (if any):
> 
> ```
> ./remove-process.sh
> ```
> 
> * Select option 1 to remove any active Blum sessions.
> * Select option 2 to remove any inactive Blum sessions and any Telegram accounts you will use to log into Blum (this won't affect other active game sessions).
> 
> If you try and reuse a saved TG account, you will likely get returned to the QR log-in page when accessing it using the Proxy Server - you will then see a lot of errors in the flow.
> 
> 2. **Enable proxy and install dependencies**:
> 
> ```
> ./launch.sh enable-proxy
> ```
> 
> This will install the required dependencies within the standard virtual environment and create a new PM2 process called `http-proxy`.
> 
> 3. **Set up new Blum accounts**:
> 
> ```
> ./launch.sh blum
> ```
> 
> Set up new accounts for each Blum user you wish to automate.
> 
> Following these steps should resolve the issues you're experiencing with Blum. If you encounter any further problems, feel free to ask for assistance.

HI Did it working on docker?

**Comment by bscongluanbui** [comment]
I got this after do the follow step
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 10 - Attempting to check for the start button (should not be present)...
Step 11 - Attempting to open a link for the app...
Step 11 - Failed to find the 'Open Wallet' button within the expected timeframe.

Step 11 - Attempting to find the chat window/message input box...
Step 12 - Attempting to send the '/start' command...
Step 12 - An error occurred: Message: element not interactable
  (Session info: headless chrome=112.0.5615.49)
Stacktrace:
#0 0x005556c42bf4 <unknown>
#1 0x0055569adec0 <unknown>
#2 0x0055569dfb4c <unknown>
#3 0x0055569df31c <unknown>
#4 0x0055569dac18 <unknown>
#5 0x005556a17544 <unknown>
#6 0x0055569d9064 <unknown>
#7 0x0055569da550 <unknown>
#8 0x005556c6adf4 <unknown>
#9 0x005556c2539c <unknown>
#10 0x005556c24ecc <unknown>
#11 0x005556c675dc <unknown>
#12 0x005556c25d78 <unknown>
#13 0x005556c094c8 <unknown>
#14 0x005556c305e4 <unknown>
#15 0x005556c30788 <unknown>
#16 0x005556c3afa0 <unknown>
#17 0x007fa596597c <unknown>
#18 0x007fa59cb7dc <unknown>

**Comment by thebrumby** [comment]
Hi, looks like the Telegram session is not working correctly. Did you delete the existing Blum and Telegram sessions and start again with a newly scanned QR code or OTP?

**Comment by thebrumby** [comment]
And if you type
```
pm2 logs http-proxy
```

Do you see normal output?

94|http-pr | 127.0.0.1:56310 <- WebSocket binary message <- kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56310 -> WebSocket binary message -> kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 <- WebSocket binary message <- kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 <- WebSocket binary message <- kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 -> WebSocket binary message -> kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 -> WebSocket binary message -> kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56310 -> WebSocket binary message -> kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56310 <- WebSocket binary message <- kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 -> WebSocket binary message -> kws4.web.telegram.org:443/apiws
94|http-pr | 127.0.0.1:56308 <- WebSocket binary message <- kws4.web.telegram.org:443/apiws

**Comment by bscongluanbui** [comment]
> Hi, looks like the Telegram session is not working correctly. Did you delete the existing Blum and Telegram sessions and start again with a newly scanned QR code or OTP?

yes. I do it, delete all blum and telegram sesion, create new session but got this. I'm using docker and using ./pull-games.sh
to update

**Comment by thebrumby** [comment]
Can you see the healthly response from the http-proxy output in PM2 logs?

**Comment by thebrumby** [comment]
Is it worth trying to create a new container for Blum? See if it also has the issue. I pre-tested on AWS-Linux & Ubuntu 24 machines both as raw installs and docker containers (both AMD64 and ARM64) and could not create any issue:

docker run -d --name telegram-claim-bot2 --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it telegram-claim-bot2 /bin/bash

**Comment by bscongluanbui** [comment]
> Is it worth trying to create a new container for Blum? See if it also has the issue. I pre-tested on AWS-Linux & Ubuntu 24 machines both as raw installs and docker containers (both AMD64 and ARM64) and could not create any issue:
> 
> ```
> docker run -d --name telegram-claim-bot2 --restart unless-stopped thebrumby/telegram-claim-bot:latest
> docker exec -it telegram-claim-bot2 /bin/bash
> ```

thanks for help. I reinstall and it's working but sometime account it's claim but not start farm

**Comment by thebrumby** [comment]
No problem! :)

Regarding Blum, there might need to be some tweaks to the code in the coming days because they have made alterations to the GUI. Now that the game is live again, we will monitor it closely to identify any changes they have made.
