### ISSUE TITLE
FIXED: Discussion: vertus daily rewards 

### ISSUE THREAD

**Issue by S26T** [thebrumby/HotWalletClaimer#42]
Please add daily rewards. Need to tap on missions -> daily -> claim

Thanks 🙏

**Comment by thebrumby** [comment]
Hey Sergey,

We are just trying to refine one optimization and then will release it in the repository. 

It is claiming both the daily reward (if present) and the usual tokens, but we have to reload between the two types of reward, as we can't trigger the back button!

We'll update again tomorrow :)

**Comment by thebrumby** [comment]
Friends, 

It might need some minor tweaks, but the main flow is now sorted and the daily claim status is correctly fed back to `./launch.sh status`, so we pushed it live to the repository.

As always, you just need to restart each instance of the script in PM2 after pulling the latest code to benefit from the change.

**Comment by thebrumby** [comment]
We are now on day 4 with no issues or manual intervention required. Closing as complete :)

**Comment by bscongluanbui** [comment]
> We are now on day 4 with no issues or manual intervention required. Closing as complete :)

Hi Im using docker but vertus rewards not working on all my accounts

**Comment by thebrumby** [comment]
Hi, 

Team member @Wellynounet has pushed an update for better compatibility in Docker. Please advise if it resolves the problem or not. 

Thanks.

**Comment by thebrumby** [comment]
Hi @bscongluanbui,

Did the new code update fix the daily claim for you in Docker?

**Comment by bscongluanbui** [comment]
> Hi @bscongluanbui,
> 
> 
> 
> Did the new code update fix the daily claim for you in Docker?

Yes. Thanks for fix it. Everything is working good
