### ISSUE TITLE
FIXED: Web version of HOT Wallet app does not work and so the script

### ISSUE THREAD

**Issue by bulat-gab** [thebrumby/HotWalletClaimer#44]
But the HOT Wallet mini app in telegram desktop and mobile version of telegram work. Is it possible to update the script to make it work again?
![image](https://github.com/thebrumby/HotWalletClaimer/assets/14952031/b8e098d7-fa4c-4124-8479-8cb55bff4404)

**Comment by thebrumby** [comment]
Hi,

As mentioned in the readme.md, "This Python script utilizes Selenium and a virtual web browser to mimic human-like interaction with the games." If the game developer withdraws access to the Telegram web version, the script can't connect. We've tested various settings in our test environment to find a workaround, but nothing has been successful so far. Unfortunately, the Selenium module in Python cannot control the Telegram desktop app or the mobile versions. Therefore, it's likely that HOT will be dropped from our supported games.

Best regards,

**Comment by bulat-gab** [comment]
Thank you!

**Comment by thebrumby** [comment]
Hi, 

While we wait to see if the Telegram-embedded version of HOT can be resolved, we have made an alternate script, although it comes with a few warnings. However, in our tests so far it is working on fine on dozens of accounts :)

https://www.patreon.com/posts/here-comes-hot-106013700?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link

Kind regards

**Comment by bulat-gab** [comment]
That's awesome! I'll try

**Comment by thebrumby** [comment]
Please let us know if it works for you, then we'll close the issue.

Kind regards

**Comment by bulat-gab** [comment]
Works nicely @thebrumby ! Thank you
