### ISSUE TITLE
Long time waiting for slot

### ISSUE THREAD

**Issue by bangbangbong** [thebrumby/HotWalletClaimer#46]
Hi, I'm experiencing some difficulty when trying to add a new game account. Sometimes, the process takes hours. Is there a way to prioritize adding accounts so the wait time is shorter?
![Screenshot_1](https://github.com/thebrumby/HotWalletClaimer/assets/162609910/ccc1d209-428b-487b-b828-180a86cd6a8a)

**Comment by Wellynounet** [comment]
hi , 
add more maxSessions

**Comment by thebrumby** [comment]
Hi @bangbangbong,

The time it takes to add a new game account can depend on the hardware you are running the script on and the number of game sessions you have running.

Here are some key points to consider:

Memory Usage:
Each idle game session uses approximately 35 MB of memory.
Each active game session (during setup or claiming) uses approximately 400-450 MB of memory.
To manage memory usage effectively, we introduced a limit on the number of concurrent claims, known as claim slots. Each game session reserves a slot for up to 5 minutes to make its claim. If it cannot complete within this time, it releases the slot, and another game session can attempt to claim.

Steps to Improve Performance
Check Your Server Specifications:

For a server with 1 vCPU and 1 GB of RAM, stick with 1 claim slot.
With 2 GB of RAM, you can increase to 3 claim slots.
With 4 GB of RAM, you can increase to 6 claim slots.
Use the command free -m in Ubuntu to check your available memory.
Check for Memory Issues:

If the process is taking too long, your memory might be full. You can reset everything with sudo reboot.
Use ./launch.sh status to check if existing game sessions are stuck in a loop of errors and claims.
Increase Claim Slots:

If you need to increase the number of claim slots, run ./launch.sh and select "y" when prompted to update settings.
Navigate to the maxSessions prompt and increase the number as needed. Confirm all values to proceed with the normal setup.
Under normal circumstances, each game session should take between 30 seconds and a few minutes to create. If it's taking hours, there might be an issue with your setup that needs to be addressed.

Kind regards

**Comment by thebrumby** [comment]
If you run `pm2 stop all`, it will stop all the other sessions, for sure.

You could then do `rm status.txt` to clear the wait queue.

Add your game(s) as required and then do `pm2 start all` to resume everything :)

**Comment by Wellynounet** [comment]
share with us your specs 
Cpu 
Ram 
Network-Speed 
OS 
Docker 
and how many account you running :)
