### ISSUE TITLE
Hot Wallet working not correctly

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#47]
I think Hot wallet is not collect coin on time. Over pass 1-2 hour of Schedule time but the tool didn't collect the rewards. If I restart, It's collected. Pls check that.
I'm Using docker

**Comment by Wellynounet** [comment]
If you have a time difference between what it should claim and your time, maybe you don't have the right time zone. Type "date" in docker and tell me if you see the same time as in your country. 
I, too, was like that at the beginning with docker I'm in the Germany Berlin time zone and I had a 2-hour time difference 
if not, I'm also using docker and there's no problem on my side. 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/e33e9755-57c6-47aa-952c-7cc0d635b68a)

**Comment by bscongluanbui** [comment]
> hi,
> 
> If you have a time difference between what it should claim and your time, maybe you don't have the right time zone. Type "date" in docker and tell me if you see the same time as in your country. I, too, was like that at the beginning with docker I'm in the Germany Berlin time zone and I had a 2-hour time difference if not, I'm also using docker and there's no problem on my side.
> 
> ![image](https://private-user-images.githubusercontent.com/88185485/339959306-e33e9755-57c6-47aa-952c-7cc0d635b68a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0MzIxODEsIm5iZiI6MTcxODQzMTg4MSwicGF0aCI6Ii84ODE4NTQ4NS8zMzk5NTkzMDYtZTMzZTk3NTUtNTdjNi00N2FhLTk1MmMtN2NjMGQ2MzViNjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDA2MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYzg3MmM2ZmZlYjE4N2NjMmJjYjczODY0ZGRhZTlmMTQyZGZiMmZhYTYzNWJjZGVlMTg0NTg1ZGUyY2Q0YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NIPW57Q0jVuPt-gxCnoU2pF274aF32vyKd999xEHFmA)

Oh thank you, I restart it this morning and it working right now

**Comment by Wellynounet** [comment]
use this tuto if you want  your TZ

https://www.hoelzel.it/helm/2022/07/05/update-timezone-alpine-container.html
