### ISSUE TITLE
Discussion chat

### ISSUE THREAD

**Issue by badmosh23** [thebrumby/HotWalletClaimer#48]

**Comment by Wellynounet** [comment]
hi it's already here you just need to learn how to use it

**Comment by badmosh23** [comment]
Offf sry I just used the bot it's so good can't expain it thanks for your support for this amazing bots for community

**Comment by badmosh23** [comment]
Just have another doubt I just shutdown my pc so when will I turn it on and open docker does the claim done automatically?

**Comment by Wellynounet** [comment]
yes, but easier to try

**Comment by thebrumby** [comment]
Hi,

I think the script already can do what you’re suggesting. If you go into setting and set “forceClaim” to True in the variables.txt, or enter a “y” if you use “./launch.sh”. Then every time the container starts it will claim all. 

You can switch it on a few times a day and it will immediately claim everything it can. 

If you didn’t already see the YouTube video on about Virtual Private Servers, Amazon do a one year free trial that will let you run maybe 12 accounts. Or I use Contabo which can handle >100 acounts for $6 a month.

**Comment by badmosh23** [comment]
Ohh thanks for that information. Great script sir 🫡

**Comment by badmosh23** [comment]
Sorry for interruption but AWS required a card. certainly I don't have that isn't there any other service which takes payment in crypto im ready to pay but I can't make a payment if there paid method that you can suggest 😕

**Comment by Wellynounet** [comment]
Some time ago i have use hydra hosting, you can pay with crypto
https://hydra-hosting.eu/rdp-hosting/
but we can tell you more about how to use this service you have to find out

**Comment by thebrumby** [comment]
A quick Google search shows [PQ Hosting](https://pq.hosting/en/payments) also accepts around 10 common coins as payment. But I have never used them and can't speak for the quality of their service or what the surcharge might be for crypto.

Thanks

**Comment by badmosh23** [comment]
Does all steps goes same with this service ? Steps as AWS service

**Comment by Wellynounet** [comment]
go talk to them in discord they can answer better

**Comment by badmosh23** [comment]
well PQ hosting will work for me

**Comment by Wellynounet** [comment]
you can connect with near wallet and you will have access to your seedphrase

**Comment by badmosh23** [comment]
Which vps are you guys using?

**Comment by thebrumby** [comment]
> you can connect with near wallet and you will have access to your seedphrase

Good idea @Wellynounet! The HereWallet iOS/Android app let's you log in with Seed Phrase, Private Key or QR code. Once logged in if you look for the "Passphrase" option it will show it in 12-word seed phrase format!

**Comment by thebrumby** [comment]
> Which vps are you guys using?

Personally, I use Contabo the most. They have a 4-core, 6 GB system for about $6.50 a month that would handle upwards of 100 game accounts I guess :) My other main one is Amazon Web Services - but that's more for testing. With them, I can spin up an instance for $0.02 per hour, install Docker or Standalone, try a few accounts and shut it back down within the same hour with no setup fee or minimum charge (or 1 hour minimum charge maybe).

**Comment by badmosh23** [comment]
I will try to buy a server with crypto but 5 a month and get the same specs as the aws free trail kinda feel wrong to buy it have no other option 🫠

**Comment by thebrumby** [comment]
> I will try to buy a server with crypto but 5 a month and get the same specs as the aws free trail kinda feel wrong to buy it have no other option 🫠

Yeah the 12-months free with AWS is a gift if you are eligible and only need to claim around a dozen accounts. However if you don’t have access to a card, or have a close friend that could do it for you, then it’s a lost opportunity.

**Comment by Wellynounet** [comment]
i have personally a mini pc with N100 processor  it's kinda cheap like 120 - 150 €  for4 core 16 gb  of ram and 512gb ssd

**Comment by badmosh23** [comment]
That my pc specs

**Comment by badmosh23** [comment]
Hey I brought the server but why there isn't any password now how can I login to it?

**Comment by badmosh23** [comment]
![Screenshot (265)](https://github.com/thebrumby/HotWalletClaimer/assets/150448156/9933c312-9482-49d9-b8d6-946c084ffc16)
its take lot of time isnt there any other faster way or we compalsry have to add account?

**Comment by Wellynounet** [comment]
> That my pc specs

Great with this PC you can run a lot of game, I have like 50 game running at same time split into  3+ account telegram with very little CPU usage on (docker)  


for your last pictures 

you can run "pm2 stop all " 
rm  status.txt 
and you can add another claim 
with 
"./launch.sh hot " without waiting 
do the same for every claim process you want 
and after do ```pm2 restart all```  and wait :)

**Comment by badmosh23** [comment]
Ohh great it just speed up my process by lot

**Comment by Wellynounet** [comment]
> Ohh great it just speed up my process by lot

dont forget to restart after :)

**Comment by bscongluanbui** [comment]
Hi why We don't create a group telegram chat for share and discusion?

**Comment by badmosh23** [comment]
Yes it will be great. 🫡

**Comment by badmosh23** [comment]
![Screenshot (267)](https://github.com/thebrumby/HotWalletClaimer/assets/150448156/e052f625-af04-4004-af8a-c1f9260efcd6)
what do you guys think how many more account can i add till now i added only 6 account of hot mining

**Comment by badmosh23** [comment]
![markup_2672.png](https://github.com/thebrumby/HotWalletClaimer/assets/150448156/ae63a60b-a7f5-4b67-9213-f2375e635c65)

Well I imported to here wallet and it's showing this error 🥲 any solution guys?

**Comment by thebrumby** [comment]
> ![Screenshot (267)](https://private-user-images.githubusercontent.com/150448156/340074467-e052f625-af04-4004-af8a-c1f9260efcd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzAxMTQsIm5iZiI6MTcxODUyOTgxNCwicGF0aCI6Ii8xNTA0NDgxNTYvMzQwMDc0NDY3LWUwNTJmNjI1LWFmMDQtNDAwNC1hZjhhLWMxZjkyNjBlZmNkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWE3YjdjMTg3Yzk3YWUyOGExMTRkZjUxZGI3OTlhMmJmMmZhZGJhNjQyOTRkNTdjZDVkMDk4OGFmMjdiZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gaCvvHqG7SvTLZOyy03U4mj2geIdrAwGyKdouWUSmgo) what do you guys think how many more account can i add till now i added only 6 account of hot mining

With 1  GB of RAM I’d aim for around 12 accounts, you can type ‘free -m’ to see the remaining after each account add, then leave around 450 mb for the claim session when active. 

Expanding to a 2 GB VPS would let you add another 30 accounts if you stick to one concurrent claim session.

**Comment by badmosh23** [comment]
> > ![Screenshot (267)](https://private-user-images.githubusercontent.com/150448156/340074467-e052f625-af04-4004-af8a-c1f9260efcd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzAxMTQsIm5iZiI6MTcxODUyOTgxNCwicGF0aCI6Ii8xNTA0NDgxNTYvMzQwMDc0NDY3LWUwNTJmNjI1LWFmMDQtNDAwNC1hZjhhLWMxZjkyNjBlZmNkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWE3YjdjMTg3Yzk3YWUyOGExMTRkZjUxZGI3OTlhMmJmMmZhZGJhNjQyOTRkNTdjZDVkMDk4OGFmMjdiZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gaCvvHqG7SvTLZOyy03U4mj2geIdrAwGyKdouWUSmgo) what do you guys think how many more account can i add till now i added only 6 account of hot mining
> 
> With 1  GB of RAM I’d aim for around 12 accounts, you can type ‘free -m’ to see the remaining after each account add, then leave around 450 mb for the claim session when active. 
> 
> Expanding to a 2 GB VPS would let you add another 30 accounts if you stick to one concurrent claim session. 

What about Blum if I add it? With 9 account?

**Comment by thebrumby** [comment]
> ![markup_2672.png](https://private-user-images.githubusercontent.com/150448156/340075010-ae63a60b-a7f5-4b67-9213-f2375e635c65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MzAxMTQsIm5iZiI6MTcxODUyOTgxNCwicGF0aCI6Ii8xNTA0NDgxNTYvMzQwMDc1MDEwLWFlNjNhNjBiLWE3ZjUtNGI2Ny05MjEzLWYyMzc1ZTYzNWM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwOTIzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGFhNDQ4NTdiMzA5ZmM0YjhhYTg4YmIyOGY0MDY4YmUxOWU3ZmNiYzQ4OTFiOTRlNmZkZmVhMzNhYTJmZTcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QwYMo7X6Fvfcpqp4dpGTWMNF_4QT1_1_uFszSrHMPdQ)
> 
> Well I imported to here wallet and it's showing this error 🥲 any solution guys?

Hi, the HereWallet Telegram bot only accepts logins via seed phrase, I’m not aware how to convert a Near protocol PK to seed phrase.

**Comment by badmosh23** [comment]
There is another option to login via pk

**Comment by thebrumby** [comment]
> Hi why We don't create a group telegram chat for share and discusion?

Hi, 

does any community member or members have the time and interest to moderate such as group? 

I can create a TG group and add a spam bot, but currently we are checking YouTube comments, Patroen and of course here in GitHub, so while I can read the Telegram every now and again, I don’t have the time to check such a group multiple times a day. 

Also, if I was a game dev and found a Telegram group of Bot support, I’d be putting the whole members list on my blocked list 😂

**Comment by badmosh23** [comment]
Telegram link?

**Comment by badmosh23** [comment]
> ![markup_2672.png](https://github.com/thebrumby/HotWalletClaimer/assets/150448156/ae63a60b-a7f5-4b67-9213-f2375e635c65)
> 
> Well I imported to here wallet and it's showing this error 🥲 any solution guys?

@Wellynounet did you have any solution?
