### ISSUE TITLE
Oxygen Miner error collect oxy

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#50]
Hi sir, Oxygen didn't collect the Oxy. Status unknown gain.

**Comment by Wellynounet** [comment]
Hello ,  oxygen didn't need to claim OXY  only food

**Comment by bscongluanbui** [comment]
> Hello , oxygen didn't need to claim OXY only food

Sorry but I mean food. I check all account this morning but none of them collected

**Comment by Wellynounet** [comment]
With offset, it happened after probably

**Comment by bscongluanbui** [comment]
> With offset, it happened after probably

It's seem thay add cloudflare to prevent bot

**Comment by thebrumby** [comment]
Hi,

Oxygen miner seems to have lots of lag in it’s GUI today. This is an issue with the Oxygen game developers. 

This last hour it seems a little better, and the script made an automated claim in both my oxygen accounts. 

Please note, many of these games are growing at a rate of millions of users per month, and many of them have had periods of lag or functions not working. If the script can not interact with the Telegram web GUI within a 10-30 second window it will fail to carry out the action. This is not an issue with the script, it’s an issue with the game. Once they restore their access, of course we can adapt if they made changes, but if they are down a few hours or a few days, there is nothing we can do apart from wait 🤓

**Comment by thebrumby** [comment]
Just out of interest, if you use the new status tool, `./launch.sh` and type `status [id]` where you replaced the `[id]` with the number of one of your oxygen accounts, what output are you seeing?

While the oxygen GUI has been lagging for me, it has claimed successfully for the last 10 hours.

<img width="589" alt="image" src="https://github.com/thebrumby/HotWalletClaimer/assets/29182343/c693ec72-0c93-4ea1-9514-3e90d0166ed4">

**Comment by bscongluanbui** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/102287592/581e498b-ad5d-4e98-b044-fa37d7b757a6)
My status. I dont know but I can access on web and mobile

**Comment by Wellynounet** [comment]
its probably from your country  we dont have  any probblem with oxygen

**Comment by bscongluanbui** [comment]
> its probably from your country we dont have any probblem with oxygen

Thank you. Might be problem is server

**Comment by thebrumby** [comment]
> ![image](https://private-user-images.githubusercontent.com/102287592/340143597-581e498b-ad5d-4e98-b044-fa37d7b757a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjA0MTMsIm5iZiI6MTcxODYyMDExMywicGF0aCI6Ii8xMDIyODc1OTIvMzQwMTQzNTk3LTU4MWU0OThiLWFkNWQtNGU5OC1iMDQ0LWZhMzdkN2I3NTdhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxMDI4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWM4NDcxY2YyYjViN2I3NzIxMTdjZmZjNGYxODgwMWY0MzcyZDczZWZjYjU5YTczYjI1ODdiMjdhNGE4NzkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9-lDdiWVydwN6fusIqcIB8HkUhlQBr_6PvFvygJavY0) My status. I dont know but I can access on web and mobile

The Oyxgen script is working well on our test servers in the UK, Germany and USA.

Is it possible that your Telegram session has logged out? It might be worthwhile using `./launch.sh status` to remove the saved Telegram account and bugged game session, and then try setting it up again by scanning a fresh QR code/One-Time password.

Thanks
