### ISSUE TITLE
Fuel Bot the debug screenshot is not full

### ISSUE THREAD

**Issue by bulat-gab** [thebrumby/HotWalletClaimer#51]
The bot makes debug screenshots of only half of the game's page. You can see there is a scroll button on the right

![image](https://github.com/thebrumby/HotWalletClaimer/assets/14952031/4991f506-c5ac-47b5-8c8a-9dfa38a24401)

**Comment by thebrumby** [comment]
Hi @bulat-gab 

You are correct, not all games fit within the standard screen size, especially considering we sometimes attempt to make the game interaction look like it's happening on a mobile device to avoid detection. The Selenium module will move the viewable area to the part we are trying to interact with, and click a button or read the information. If you want to see a different part of the screen, you need to direct Selenium to move there, and you can screenshot that also.

**Comment by bulat-gab** [comment]
Got it. thanks

**Comment by thebrumby** [comment]
Thank you for your commit to fix the fuel advert! I merged it now and will test :)
