### ISSUE TITLE
Fuel game does not watch ads every 30 mins

### ISSUE THREAD

**Issue by bulat-gab** [thebrumby/HotWalletClaimer#54]
Hi @thebrumby,

The Fuel game serves ads every 30 mins. However the fuel bot seems like watching it only once during the full claim, and then it sleeps for 12 hours. I would like the bot to watch ads as soon as they appear, as it increases the mining speed. I'm wondering if I can just update the config or need to modify the code? (I was going through the code, but didn't understand it yet)

Here is the log file showing it:
![image](https://github.com/thebrumby/HotWalletClaimer/assets/14952031/ad47cdf6-e1d2-48ba-8c1a-4047ef779d76)

Step 110 - watch an advert done
After that more than 1 hour passed, no attemp to watch it

**Comment by bulat-gab** [comment]
Keep in mind, sometimes the advert button ("Increase multiplier by..") is available but there are no ads to show and this windows appears:
![image](https://github.com/thebrumby/HotWalletClaimer/assets/14952031/0f2be957-3578-4f8a-875b-945b5033d929)

**Comment by thebrumby** [comment]
Hi @bulat-gab ,

It looks like we could benefit from moving some of the code about in the `def full_claim()`. I'm not at home for testing right now, but I would remove  this:

```
                xpath = "//a[text()='Upgrades']"
                move_and_click(xpath, 10, True, "click the 'Upgrades' button", step, "clickable")
                xpath = "//button[contains(., 'Increase multiplier by')]"
                advert = move_and_click(xpath, 10, True, "watch an advert", step, "clickable")
                if advert:
                    output(f"Step {step} - Waiting 60 seconds for the advert to play.",3)
                    time.sleep(60)
                    increase_step()
                    get_balance(True)
```

And paste it in to here before it returns the remaining time. I just changed the output text to reflect the 30-minute advert check and forced `remaining_wait_time = 30` :

```
    if wait_time_text != "Filled":
        try:
            time_parts = wait_time_text.split()
            hours = int(time_parts[0].strip('h'))
            minutes = int(time_parts[1].strip('m'))
            remaining_wait_time = (hours * 60 + minutes)
            if remaining_wait_time < 5 or settings["forceClaim"]:
                settings['forceClaim'] = True
                output(f"Step {step} - the remaining time to claim is less than the random offset, so applying: settings['forceClaim'] = True", 3)
            else:
                remaining_wait_time = 30
                output(f"STATUS: Pot not ready for claiming - let's come back in 30 minutes to check for adverts.", 1)
                return remaining_wait_time
        except ValueError:
            # Handle the case where wait_time_text can't be parsed
            pass
```

If we do it this way around, it will let us check for the "recycle" after the main claim, which I wonder if it should say "refine" if it's converting oil into petrol :)

Cheers

**Comment by Wellynounet** [comment]
I have pushed the update
auto refine + advert

**Comment by thebrumby** [comment]
Great stuff, thank yo @Wellynounet!
