### ISSUE TITLE
pm2 error

### ISSUE THREAD

**Issue by badmosh23** [thebrumby/HotWalletClaimer#56]
![Screenshot (276)](https://github.com/thebrumby/HotWalletClaimer/assets/150448156/71e759d4-0dfd-4a76-90f4-931dcd516708)
Dont know but why this happening in this server. pm2 is not responding i did every thing same and rm status.txt is also not responding.

**Comment by Wellynounet** [comment]
pm2 resurrect

**Comment by badmosh23** [comment]
ohh im so sorry i didnt even added my account im really really sorry

**Comment by Wellynounet** [comment]
no problem :)

**Comment by badmosh23** [comment]
sorry for my lazyness. i have a question i bought the server so can i get grass on it

**Comment by badmosh23** [comment]
@Wellynounet did you have any idea on it?

**Comment by Wellynounet** [comment]
Sorry, i didn't understand what you mean 
youu want help to setup your account ?

**Comment by badmosh23** [comment]
no i mean that i own a server which run 24/7 so can i run a chrome extention name:- GET GRASS on the server which will earn me some points. @Wellynounet

**Comment by Wellynounet** [comment]
No i dont know grass airdrop 
i cant help on this

**Comment by badmosh23** [comment]
ohh thanks for your help
