### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by badmosh23** [thebrumby/HotWalletClaimer#57]
Does this script have a feature to upgrade the speed of mining HOT automatically? Or do we have to do that manually?

**Comment by Wellynounet** [comment]
hello , no you have to do manually

**Comment by thebrumby** [comment]
Hi,

People have different strategies for what they want to upgrade and when, especially in HOT/Ocean where there are gas fee savings for upgrading the storage pot and reducing the time to fill the pot. Therefore, this is left to the user to upgrade.

In general, I dislike the script doing anything that spends the earned tokens, although we have made some exceptions, such as Hexacore/Hexacoin, which has an optional auto-upgrade script.

Thanks
