### ISSUE TITLE
Not showing balance, next claim, status

### ISSUE THREAD

**Issue by dropclient** [thebrumby/HotWalletClaimer#58]
Hello!
Script doesnt show information, but bots are work success
![image](https://github.com/thebrumby/HotWalletClaimer/assets/22478613/9dfc5f30-1357-4c7f-8117-7c8e951e2b19)
Is this feature doesnt work?
Thanks!

**Comment by Wellynounet** [comment]
hello  your log file are not  in the same folder than the script watch 

i think ..

**Comment by dropclient** [comment]
For information - i use docker container
> pm2 logs
`/root/.pm2/logs/Vertus-123-out.log`

> cat status.py | grep log_file
```
    log_file = f"/root/.pm2/logs/{sanitized_process_name}-out.log"
    logs = run_command(f"tail -n 200 {log_file}")
        log_file = f"/root/.pm2/logs/{sanitized_process_name}-out.log"
        logs = run_command(f"tail -n {lines} {log_file}")
        log_file = f"/root/.pm2/logs/{sanitized_process_name}-out.log"
        logs = run_command(f"grep -E 'BALANCE:|STATUS:' {log_file} | tail -n 20")
> ll /root/.pm2/logs/
```
total 1696
drwxr-xr-x. 2 root root   4096 Jun 19 12:47 ./
drwxr-xr-x. 5 root root    180 Jun 17 21:05 ../
-rw-r--r--. 1 root root   3478 Jun 19 17:55 Vertus-123-error.log
-rw-r--r--. 1 root root  68564 Jun 19 20:41 Vertus-123-out.log
```
But still not show balance

**Comment by Wellynounet** [comment]
ok he need to do a claim first

**Comment by dropclient** [comment]
> ok he need to do a claim first

Already claimed a lot of times
uptime 24h+
![image](https://github.com/thebrumby/HotWalletClaimer/assets/22478613/3d688e3a-c9a9-40a4-b260-ca9de83ca4cd)
For example log:
```
/root/.pm2/logs/Vertus-mega-385-out.log last 15 lines:
12|Vertus: | Step 114 - Attempting to click on the 'Claim' link...
12|Vertus: | Step 114 - Timeout while trying to click on the 'Claim' link.
12|Vertus: | Step 114 - Attempting to check if the bonus is for tomorrow...
12|Vertus: | Step 114 - Removed an overlay covering the target.
12|Vertus: | Step 114 - Removed an overlay covering the target.
12|Vertus: | Step 114 - Removed an overlay covering the target.
12|Vertus: | STATUS: Successful Claim & The daily bonus will be available tomorrow.: Next claim in 60 minutes.
12|Vertus: | Session released: ./selenium/Vertus:mega_385

```

**Comment by dropclient** [comment]
Probably problem with my session names? Maybe underscore not allowed for session names?

**Comment by dropclient** [comment]
Yes, i recreate session from mts_264 to mts264 and now it works =)
Can you fix this in code? =)

**Comment by thebrumby** [comment]
Hi,

We've revised the code for status.py to replace underscores ("_") with hyphens ("-") in PM2 log filenames, while maintaining the ability to pattern match delete processes that include the underscore. We have tested it a few times, but we'd appreciate it if you could confirm that it's working well for you.

Thanks!

**Comment by dropclient** [comment]
Thanks, work fine now!
