### ISSUE TITLE
Vertus passive mining

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#59]
Hi sir. New version of vertus release. We can buy card and get passive mining. But maximum time passive is every 4 hours. Can add the feature that auto collect passive rewards every 4 hours? Thanks

**Comment by Wellynounet** [comment]
Hello bscong  
maybe 
maybe not 
you will see

**Comment by thebrumby** [comment]
Hi @bscongluanbui,

The passive mining / village reward collection has been added for Vertus. 

Thanks.
