### ISSUE TITLE
Manage work python claim.py

### ISSUE THREAD

**Issue by Sergey26Tarasenko** [thebrumby/HotWalletClaimer#6]
Hello! How I can stop python claim.py? After CTRL+C I see that .sh still work in system monitor and auto added folder Selenium to project folder?

**Comment by Sergey26Tarasenko** [comment]
Example 

1. My claim.py not work corrent and I want to stop it
2. Was start claim.py without option debugIsOn and I want to continue work with true value,

**Comment by thebrumby** [comment]
Hey Sergey,

It sounds like the script stopped prematurely, and it didn't manage to close the Chrome/Chrome Driver sessions. 

If you want to close these sessions manually, you can find the active processes with:
\`\`\`bash
pgrep chrome
pgrep chromedriver
\`\`\`

To shut down all the active processes immediately and start fresh, you can use:
\`\`\`bash
pgrep chrome | xargs kill
pgrep chromedriver | xargs kill
\`\`\`

Alternatively, if it's convenient, you might consider saving any open work and rebooting your system. This will also terminate these processes.

**Comment by thebrumby** [comment]
Also, please let me know if you still have issues with the script.

**Comment by Sergey26Tarasenko** [comment]
I think fount solution. Firrst step need to delete session from PM2. pm2 delete .... Next to kill process chromedriver

**Comment by Sergey26Tarasenko** [comment]
Also work CTRL + Z

**Comment by thebrumby** [comment]
Hey Sergey,

It seems things didn't quite work out as I had hoped! I tested the code several times yesterday before rolling it out, and it worked perfectly each time.

I've just pushed today's changes up as version 1.4.2, which I hope will resolve your issues. Again, I tested it in various scenarios (QR code/OTP, with and without 2FA), and all are working as expected for me.

Please let me know how you get on.
