### ISSUE TITLE
how to uninstall this program

### ISSUE THREAD

**Issue by rappganteng78** [thebrumby/HotWalletClaimer#60]
how to uninstall

**Comment by Wellynounet** [comment]
delete file

**Comment by thebrumby** [comment]
> how to uninstall

Hi,

The uninstallation process depends on how you installed the script and what operating system you're using. Could you please provide a bit more detail? Specifically:

- Operating System: Are you using Windows, Ubuntu, or Red Hat Linux?
- Installation Method: Did you install it using Docker, or is it a standalone installation?

Once we have this information, we can give you further imformation.

Thanks!

**Comment by rappganteng78** [comment]
docker sir in ubuntu

**Comment by thebrumby** [comment]
Hi there,

If you want to uninstall the script without removing Docker, you can use the following commands:

```
docker stop telegram-claim-bot
docker rm telegram-claim-bot
```

The first command stops the container, and the second command deletes it.

### If you also want to remove Docker entirely from your Ubuntu system, you can follow these steps:

- Stop all running containers:
```
docker stop $(docker ps -aq)
```

- Remove all containers:
```
docker rm $(docker ps -aq)
```

- Uninstall Docker packages:
```
sudo apt-get purge docker-ce docker-ce-cli containerd.io
sudo apt-get autoremove
```

- Remove Docker directories:
```
sudo rm -rf /var/lib/docker
sudo rm -rf /var/lib/containerd
```

Best regards.

**Comment by rappganteng78** [comment]
thankyou very much
