### ISSUE TITLE
Adding Proxy for each account

### ISSUE THREAD

**Issue by qwerty123-noname** [thebrumby/HotWalletClaimer#62]
Good afternoon I recently saw your program. From the first impression, she will be very good at helping me with farming points, but there is one huge drawback, or I just didn’t see it, but in your program you cannot add a proxy for each account. If this is not there, will you add it in the near future, and if so, please tell me where?

**Comment by Wellynounet** [comment]
hello, i think its build in selenium

**Comment by thebrumby** [comment]
Hi, 

We are currently working on a proxy system (hopefully it will be released this weekend) that offers the following features:

**Default:** Off (However, I recommend turning on)
**Port & IP:** http://127.0.0.1:8080
**Username:**
**Password:**

The games Blum & Vertus both force you to use the provided proxy, or else the game won't work.

The built-in proxy is only a beta feature at the minute, but it will replace certain requests for your user-agent, etc, and replace the ones from your system with one that shows you are using an iPhone, the iOS app, not Telegram Web, etc.

There is also an option that tells the third-party module Squid to spoof your outgoing IP address with a user-defined IPV4/IPV6 address if you want to change it. Mine is set to mimic my own home connection.

**Comment by qwerty123-noname** [comment]
I will wait for this update, because farming everything from 1 IP address is not a very good thing!

**Comment by thebrumby** [comment]
> I will wait for this update, because farming everything from 1 IP address is not a very good thing!

Hi,

The system doesn't offer a per-account configuration. If you want to set up a proxy for each account, you'd need to create multiple repository folders or provide your own workaround:

```
git clone https://github.com/thebrumby/HotWalletClaimer account1
git clone https://github.com/thebrumby/HotWalletClaimer account2
git clone https://github.com/thebrumby/HotWalletClaimer account3
```

**Comment by fly-a1one** [comment]
> > I will wait for this update, because farming everything from 1 IP address is not a very good thing!
> 
> Hi,
> 
> The system doesn't offer a per-account configuration. If you want to set up a proxy for each account, you'd need to create multiple repository folders or provide your own workaround:
> 
> ```
> git clone https://github.com/thebrumby/HotWalletClaimer account1
> git clone https://github.com/thebrumby/HotWalletClaimer account2
> git clone https://github.com/thebrumby/HotWalletClaimer account3
> ```

Hi. I am faced with the problem that I cannot run any script with a proxy. Literally before that, everything worked fine without a proxy, and now I wanted to create a new Telegram session with a proxy, but in the end nothing worked

![image](https://github.com/thebrumby/HotWalletClaimer/assets/70477273/e9d95f64-915e-4a4f-b542-082785273488)

**Comment by thebrumby** [comment]
Hi @fly-a1one ,

What system are you using? Docker / Standalone? If standalone what operating system and OS version are you using?

From the screenshot that you showed, all I can see is it's not working, but there are no clues as to why.

```
pm2 delete http-proxy
pm2 save
```

If you run the above commands and try to `./launch.sh hot` again, it should try to reinstall the proxy. Maybe at that step you can see some error highlighted?

Thanks
