### ISSUE TITLE
Blum Issue

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#65]
Today Blum has an issue with the tool. Pls fix this Sir

**Comment by thebrumby** [comment]
Hi @bscongluanbui , 

Blum is working just fine for us.

Is this a one-time error or repeated? Affecting just one account, or all? Does the screen show any errors?

If all your Blum account logins got corrupted, I would try this approach.

```
./launch.sh status
```

Wait for it to load and offer the options.

```
delete Blum:
```

To remove the accounts that got corrupted. Then type:

```
./launch.sh blum
```

And renew the sign-in for each account. Please let us know if you have further issues after this, thanks.

**Comment by Wellynounet** [comment]
can confirm no issue  here in Europe west ( UK )

**Comment by bscongluanbui** [comment]
Status ID with

STATUS: Still Unknown and 8 minute offset - Let's sleep. None
and PM2 logs with
Step 102 - Attempting to open a link for the app...
Step 103 - Attempting to click the 'Launch' button (may not be present)...
Step 104 - Attempting to switch to the app's iFrame...
Step 105 - Attempting to check for daily reward...
Step 106 - Attempting to click the 'Start farming' button (may already be running)...
CHROME DRIVER DETACHED: It is now safe to exit the script.
24 June - 19:34 | Need to wait until 24 June - 19:49 before the next claim attempt. Approximately 15 minutes.
 
I tried remove the session and add new. Update the latest script. I can open on the mobile

**Comment by thebrumby** [comment]
Hi, 

Are you still using Docker? What happens if you create a new container?

```
docker run -d --name blum --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it blum /bin/bash
```

**Comment by bscongluanbui** [comment]
> Hi,
> 
> Are you still using Docker? What happens if you create a new container?
> 
> ```
> docker run -d --name blum --restart unless-stopped thebrumby/telegram-claim-bot:latest
> docker exec -it blum /bin/bash
> ```

ok i will tried

**Comment by bscongluanbui** [comment]
> docker exec -it blum /bin/bash

I think have some problem with docker after update. When run ./launch.sh, Just some feature on the menu
"Listing available scripts in the current directory and ./games folder:
1) ./games/tree.py
2) ./games/cold.py
3) ./games/wave.py
4) ./games/vertus.py
5) ./games/hot.py
Please select a script by number:"

**Comment by thebrumby** [comment]
I see, it's only getting a few games.

What happens if you manually `./pull-games.sh`?
