### ISSUE TITLE
Initial ChromeDriver setup may have failed: Message: Service /usr/local/bin/chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by nam56k3** [thebrumby/HotWalletClaimer#66]
After I run the command to create a session for blum, the chromedriver error code 127 appears. Can someone give me the solution
![image](https://github.com/thebrumby/HotWalletClaimer/assets/50592413/0a43d6ae-c65b-42e3-b297-1263976a86d1)

**Comment by nam56k3** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/50592413/33e88ed9-6935-4538-8cda-c8b8c94fb5c5)
Can't install chromedriver

**Comment by nam56k3** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/50592413/8432bc68-c6f8-411b-9c4e-b2e1c8310563)
I tried everything on google but still get the error :((

**Comment by thebrumby** [comment]
Hi,

Looking at the file system, are you trying to install it on a Windows machine?

if so, the instructions contain the steps how to do it: https://github.com/thebrumby/HotWalletClaimer/blob/main/docs/WINDOWS.md

Or you can use Docker. All the instructions plus walkthrough video guides are on the main page. 

Thanks
