### ISSUE TITLE
A suggestion for a new game

### ISSUE THREAD

**Issue by fly-a1one** [thebrumby/HotWalletClaimer#67]
I suggest adding another game to the bot - TapSwap. Mechanically, it is similar to Blum, that is, every 8 hours you just have to pick up the reward. Therefore, I think it will not be a problem to do this. Moreover, it is no less popular than other games and has 56 million users

**Comment by thebrumby** [comment]
Hi @fly-a1one,

Thanks for the suggestion. The main problem will be time, as we can only integrate one or two games a week (each game takes around one day to map and test) and we already have a long list, but we'll look at it for sure.
