### ISSUE TITLE
window mode

### ISSUE THREAD

**Issue by jbr1989** [thebrumby/HotWalletClaimer#68]
Is it possible to see the script working in window mode and see what it does?

**Comment by thebrumby** [comment]
Hi, 

If you check out the main page, you can see videos of it working on the following platforms:

- Windows (Docker)
- Windows (WSL embedded Ubuntu 24.04)
- Ubuntu 24 (Docker)
- Ubuntu 24 (Standalone)

Thanks

**Comment by jbr1989** [comment]
Where? I only see videos from the terminal
I want to see the Chrome window

**Comment by thebrumby** [comment]
Our script uses Selenium to control a virtualized browser session.

Currently, it includes the `chrome_options.add_argument("--headless")` configuration, which runs Chrome in headless mode. This means the browser operates without a graphical user interface (GUI). This setup is ideal for environments like Docker containers or VPS, where there is no monitor attached, unlike a desktop PC.

Running Chrome in headless mode means there is no visual representation of the browser activities. While the debug facility can take screenshots of the virtual screen, we cannot produce a video of the interactions in the same way you would by capturing the screen on a Windows Desktop browser.
