### ISSUE TITLE
Fuel: Balances don't appear on the screenshot 

### ISSUE THREAD

**Issue by jbr1989** [thebrumby/HotWalletClaimer#75]
![105-look for oil balance](https://github.com/thebrumby/HotWalletClaimer/assets/761224/e0ec54b1-ab0a-4edb-9175-2230821a90d9)

ERROR: Step 105 - Before BALANCE: Unknown fuel & Unknown oil.

The fuel and oil balance does not appear on the screenshot. 
If I do it manually, Cloudflare appears checking the connection and if I pass it, it appears correct.

**Comment by thebrumby** [comment]
Hi,

How are you finding it if you open the GUI? Is it shown there?

**Comment by thebrumby** [comment]
Hi. 

Thanks for confirming that, I was thinking it was lag in the system before, I'll look in the coming days how better to handle it.
