### ISSUE TITLE
Seed updates

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#76]
Hi recently seed app update with catch Worm on the tree. Can you add it to the script?
Thank you

**Comment by thebrumby** [comment]
Hi,

We are low on time this next 2-weeks, but we will look into what is required. 

Thanks

**Comment by bscongluanbui** [comment]
> Hi,
> 
> We are low on time this next 2-weeks, but we will look into what is required.
> 
> Thanks

hi i see that the script update check to collect worm but it auto sell the worm. Can I keep it? Because It's seem more benefit on the furture

**Comment by thebrumby** [comment]
Hi,

This is the main reason I don't like to add too much automation regarding upgrades, because different users all have different requirement.

Is it possible for you to just delete the lines 97-98 from the script?

**Comment by bscongluanbui** [comment]
> Hi,
> 
> This is the main reason I don't like to add too much automation regarding upgrades, because different users all have different requirement.
> 
> Is it possible for you to just delete the lines 97-98 from the script?

Sorry I'm using docker and I cannot edit the line. 
Just keep it in the Inventory, we can use it later?

**Comment by bscongluanbui** [comment]
> Hi,
> 
> This is the main reason I don't like to add too much automation regarding upgrades, because different users all have different requirement.
> 
> Is it possible for you to just delete the lines 97-98 from the script?

Hi sir, can you update that in the next time. I think almost pepeole want to keep in inventory and after that, they do what they want

**Comment by thebrumby** [comment]
I'll ask the other guys regarding this, @jbr1989 contributed the code improvement and I don't want to change it if he set it for a reason. 

If you really wanted to edit the file, you could do this:

```
apt-get install nano
nano games/seed.py
```

The top line installs a text editor, and the second line would edit the game file.

**Comment by jbr1989** [comment]
I thought the worm sale was the best option, but I don't mind if they are kept in stock.

**Comment by Wellynounet** [comment]
It sounds like there's too much for me to handle with all the things going on. Whether people keep or sell the rat for me, I don't mind. I'm not even sure if the worm has been collected or not.

**Comment by Wellynounet** [comment]
> > Hi,
> > This is the main reason I don't like to add too much automation regarding upgrades, because different users all have different requirement.
> > Is it possible for you to just delete the lines 97-98 from the script?
> 
> Hi sir, can you update that in the next time. I think almost pepeole want to keep in inventory and after that, they do what they want

Hello bscong i have do something on the seed code  

you can folow the step inside the script updaped if yo uwant  keep worm 
by doing this 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/88185485/4422ec3b-92de-469b-bec2-0ae61c10574d)

**Comment by bscongluanbui** [comment]
> > > Hi,
> > > This is the main reason I don't like to add too much automation regarding upgrades, because different users all have different requirement.
> > > Is it possible for you to just delete the lines 97-98 from the script?
> > 
> > 
> > Hi sir, can you update that in the next time. I think almost pepeole want to keep in inventory and after that, they do what they want
> 
> Hello bscong i have do something on the seed code
> 
> you can folow the step inside the script updaped if yo uwant keep worm by doing this
> 
> ![image](https://private-user-images.githubusercontent.com/88185485/344494850-3ad98f53-ac10-4e14-bc17-9b657d5001e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODgyMDMsIm5iZiI6MTcxOTc4NzkwMywicGF0aCI6Ii84ODE4NTQ4NS8zNDQ0OTQ4NTAtM2FkOThmNTMtYWMxMC00ZTE0LWJjMTctOWI2NTdkNTAwMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyNTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNWJlYWJkMTczNTRkZDk0NThiN2E2N2Y3OGY5NjBmNjI4YmExNjM1OTc4NDkzYmIwZGRkM2VjYjM1ZGFhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Sl1T0a9exp0r_quV8eqZlB1QpJMk_NPe-WRq9vRwgQ)

thank you I'll do that
