### ISSUE TITLE
Hot-Alt cannot claim anymore

### ISSUE THREAD

**Issue by howtoprogram** [thebrumby/HotWalletClaimer#77]
Receiving the below messages in the log:

```
`STATUS: The wait timer is still showing: Filled.
Step 115 - This means either the claim failed, or there is >4 minutes lag in the game.`
```
Game: Hot-Alt
This has just happened today only. Looks like the claim function return error

**Comment by thebrumby** [comment]
Hi, 

![image](https://github.com/thebrumby/HotWalletClaimer/assets/29182343/3200c6a5-6ef5-4558-ad3c-f06a4766a353)

It looks like the devs have closed the alt loophole (again), this is the reason that we go back to using the app through Telegram before. 

Thanks for the heads up and we will remove it from the repository.
