### ISSUE TITLE
Kanban Board ?

### ISSUE THREAD

**Issue by jbr1989** [thebrumby/HotWalletClaimer#79]
Do you have Kanban Board for this project?
You can create on Github and if it is public then people can see the progress and new features.

**Comment by thebrumby** [comment]
Hey @jbr1989!

Not yet, but it's a good idea - we'll look to add some.

Originally, we were bumping the version number with some release notes, although most things are not around the core functionality, and are more about games coming in, and sometimes going back out as the devs tighten things up! 

Also, bits and bobs of information in the weekly Patreon blog are all free to read or comment on.

Later today there will be a Blog Post on your contribution!
