### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by ATAMAH161** [thebrumby/HotWalletClaimer#83]
Please tell me, what am I doing wrong? I enter a number without a country code, namely without +7. What could be the problem?
![Uploading IMG_1935.jpeg…]()

**Comment by thebrumby** [comment]
Hi,

To sign in to Telegram Web without a QR code, please visit the [Telegram Web sign-in page](https://web.telegram.org/k/) and choose the option to log in via phone number.

Follow these steps:
- **Step 1:** Identify and enter the country where your cellphone is registered, in words (e.g., Afghanistan, Albania, Algeria). You need to enter this into the script at the first prompt with the same spelling used by Telegram. 
- **Step 2:** At the second prompt, enter your mobile number without the initial zero (0).

The script operates by initiating a virtual browser session that accesses the official Telegram sign-in page linked above. Enter the same combination that works for you on the official page when prompted by the script. Note: The script does not transmit or save your password or phone details directly. However, it does save the "logged in" browser session to your hard drive, which should be kept secure.

- **Step 3:** You will be prompted for a 5-digit one-time password, which will be sent to your registered device.
- **Step 4:** If you have two-factor authentication (2FA) enabled, you'll need to enter this as well to proceed.

Thanks.
