### ISSUE TITLE
Time-Farm: Claim issue

### ISSUE THREAD

**Issue by thebrumby** [thebrumby/HotWalletClaimer#84]
Regarding your output

```
I tried uninstalling start over. But it doesn't seem to see the claim button on Time farm.
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 101 - Attempting to check for the start button (should not be present)...
Step 102 - Attempting to open a link for the app...
Step 103 - Attempting to click the 'Launch' button (may not be present)...
Step 104 - Attempting to switch to the app's iFrame...
Step 106 - Attempting to click the 'Start' button (may not be present)...
Step 108 - Attempting to look for the claim button....
STATUS: The claim button wasn't clickable on this occassion.
```

It's hard to see exactly which stage it's failing on. 

**Option 1:**

If you go to the Time-Farm tab on your Telegram app /  Telegram web, if you delete the existing conversation with the bot (method to delete varies by device (right click on PC or long press on mobile device) - but make sure you don't delete and block. Then restart a new "conversation" before handing over to the script again.

**Option 2:**

This will vary slightly depending whether you are on Docker or Standalone Ubuntu, but in settings, if you enable the debug setting (it will take screenshots of each stage of the process, which might highlight where the issue is) and also change verbose to level 3, this will show far more details about each stage of the claim. Here's an example from my Time Farm:

```
85|Time-Fa | CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
85|Time-Fa | Step 100 - Attempting to verify if we are logged in (hopefully QR code is not present).

85|Time-Farm:Phil  | Step 100 - nothing found to action. The QR code test passed.
85|Time-Farm:Phil  | Step 101 - Attempting to check for the start button (should not be present)...
85|Time-Farm:Phil  | Step 101 - Timeout while trying to check for the start button (should not be present).
85|Time-Farm:Phil  | Step 102 - Attempting to open a link for the app...
85|Time-Farm:Phil  | Step 102 - Successfully able to open a link for the app..
85|Time-Farm:Phil  | Step 103 - Attempting to click the 'Launch' button (may not be present)...
85|Time-Farm:Phil  | Step 103 - Timeout while trying to click the 'Launch' button (may not be present).
85|Time-Farm:Phil  | Step 104 - Attempting to switch to the app's iFrame...
85|Time-Farm:Phil  | Step 104 - Was successfully able to switch to the app's iFrame.
85|Time-Farm:Phil  | Step 105 - Found 1 elements with XPath: //div[@class='balance']
85|Time-Farm:Phil  | Step 105 - Before BALANCE: $123,456
85|Time-Farm:Phil  | Step 106 - Attempting to click the 'Start' button (may not be present)...
85|Time-Farm:Phil  | Step 106 - Timeout while trying to click the 'Start' button (may not be present).
85|Time-Farm:Phil  | Step 107 - check if the timer is elapsing...
85|Time-Farm:Phil  | Step 107 - Found 0 elements with XPath: //table[@class='scroller-table']
85|Time-Farm:Phil  | Step 108 - Attempting to look for the claim button....
85|Time-Farm:Phil  | Step 108 - Removed 0 overlay(s) covering the target.
85|Time-Farm:Phil  | Step 108 - Removed 0 overlay(s) covering the target.
85|Time-Farm:Phil  | STATUS: We appear to have correctly clicked the claim button.
85|Time-Farm:Phil  | Step 109 - Attempting to click the 'Start' button...
85|Time-Farm:Phil  | Step 109 - Removed 0 overlay(s) covering the target.
85|Time-Farm:Phil  | Step 109 - Successfully moved to the element using ActionChains.
85|Time-Farm:Phil  | Step 109 - Removed 0 overlay(s) covering the target.
85|Time-Farm:Phil  | Step 110 - check if the timer is elapsing...
85|Time-Farm:Phil  | Step 110 - Found 0 elements with XPath: //table[@class='scroller-table']
85|Time-Farm:Phil  | Step 111 - Found 1 elements with XPath: //div[@class='balance']
85|Time-Farm:Phil  | Step 111 - After BALANCE: $234,567
85|Time-Farm:Phil  | Step 111 - Random offset applied to the wait timer of: 11 minutes.
85|Time-Farm:Phil  | Session released: ./selenium/Time-Farm:Phil
85|Time-Farm:Phil  | CHROME DRIVER DETACHED: It is now safe to exit the script.
```

**Comment by mexxuz** [comment]
I was able to get it running. Clearing the chat really helped. I was able to see in real time how the game bot was starting. Thx!

**Comment by thebrumby** [comment]
I'm pleased to hear you're connected OK with Time-Farm. Blum requires the use of the built-in proxy to remove certain response headers to make the connection, is the PM2 process "http-proxy" starting OK?

**Comment by mexxuz** [comment]
> Я рад слышать, что у вас все в порядке с Time-Farm. Blum требует использования встроенного прокси-сервера для удаления определенных заголовков ответа для установления соединения, нормально ли запускается процесс PM2 "http-proxy"?

Can you tell me more about this or where can I read more about it? I am not good at understanding code, so I need an explanation of how and what to do. So far I don't understand how to run it or test it, with what commands to implement it.

**Comment by thebrumby** [comment]
```
pm2 list
```

Will show the running processes, first thing with Blum is to know if the "http-proxy" is running :)

**Comment by mexxuz** [comment]
> ```
> pm2 list
> ```
> 
> Will show the running processes, first thing with Blum is to know if the "http-proxy" is running :)

![Snipaste_2024-07-01_00-15-55](https://github.com/thebrumby/HotWalletClaimer/assets/163916551/8fef25a2-3af8-4237-bc7a-46fd93fe006d)

Yes, such a process is present.

**Comment by thebrumby** [comment]
OK good. Can you screenshot any errors you get when launching Blum, please?

**Comment by mexxuz** [comment]
> Хорошо. Не могли бы вы сделать скриншот ошибок, которые возникают при запуске Blum?

![image](https://github.com/thebrumby/HotWalletClaimer/assets/163916551/d8e67ea5-3d16-4953-948b-42e107a9c477)
Here's what's been going on since installation. It doesn't detect the input correctly, doesn't see the balance, and does nothing in the end.

**Comment by mexxuz** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/163916551/5c6d7cfc-ffb4-4709-917d-346dd0b89e2f)
Maybe I'm doing something wrong at the startup stage? Do I need to enter some kind of proxy? I set everything by default.

**Comment by mexxuz** [comment]
![image](https://github.com/thebrumby/HotWalletClaimer/assets/163916551/ba36452a-bdcf-4d45-a7ec-de7442f152ca)
Here's what the Blum log gives me

**Comment by thebrumby** [comment]
Hi,

For some reason it's having a lot of connection issues.

I would try to delete one of the accounts like this:

```
./launch.sh status
```

and then:

```
delete Blum:Mexx
```

and finally

```
./launch.sh blum Blum:Mexx
```

**Comment by mexxuz** [comment]
> Привет
> 
> По какой-то причине у него много проблем с подключением.
> 
> Я бы попробовал удалить один из аккаунтов так:
> 
> ```
> ./launch.sh status
> ```
> 
> а затем в сценарии состояния:
> 
> ```
> delete Blum:Mexx
> ```
> 
> и, наконец, нажмите Enter, чтобы вернуться в командную строку
> 
> ```
> ./launch.sh blum Blum:Mexx
> ```
> 
> И попробуйте снова настроить :)

I've already done the reinstall and uninstall several times, but it hasn't worked for me. What else can I try to do? After all attempts now I can see that the bot I have starts in telegram, but gets stuck further.

**Comment by thebrumby** [comment]
From all the screenshots you included above, it seems that like from the first step, it's not even able to connect to the chat Window in Telegram, even before it tries to connect to Blum.

As an experiment, you could try a separate Docker container for Blum. 

```
docker run -d --name blum --restart unless-stopped thebrumby/telegram-claim-bot:latest
docker exec -it blum /bin/bash
```

**Comment by thebrumby** [comment]
Update: Actually, if your saved TG sessions were saved before the built-in proxy was enabled (it’s mandatory for Blum), the error is probably just that you need to use a new Telegram session not the saved one?

**Comment by thebrumby** [comment]
This looks much more promising, it’s connecting now. Depending on the state of the game on first run, it might take a couple of attempts to get in sync.

pm2 restart Blum:Mexx

**Comment by thebrumby** [comment]
Also, if you set verbose level to 3 in settings, it will help more fault finding.
