### ISSUE TITLE
wave on sui

### ISSUE THREAD

**Issue by adigunn** [thebrumby/HotWalletClaimer#9]
can you make claimer on wave on sui separated from this? thanks

**Comment by thebrumby** [comment]
Hi,

I'm not entirely sure what you mean by "separate."

If you want to run the Wave Wallet claim script, you can use the following command:

```sh
./launch.shn wave
```

This will launch the Wave Wallet claim script.

If you mean that you want to segregate the Wave Wallet claim script from the other scripts, perhaps to allow for different settings or a standalone environment, I can provide you with instructions on how to do that. Essentially, this would involve copying the relevant script and its dependencies to a separate folder and setting it up independently.

Please clarify what you mean by "separate," and I'll be happy to assist you further.

Thanks!

**Comment by adigunn** [comment]
yes, i just need wave on sui script alone

**Comment by Wellynounet** [comment]
> yes, i just need wave on sui script alone

just start wawe script 

with python3 wave.py 

and delete other script if you dont use it

**Comment by thebrumby** [comment]
As Welly mentioned, each game script is independent, so you have a few options:

- Follow the standard instructions and delete the other files you don't need.

- Download only the files you want by clicking on them one at a time.

To help you get started with the minimal effort, I included two shell scripts:

`./install.sh` - This script will attempt to install the necessary dependencies for you, assuming you're using a recent version of Ubuntu. It includes setting up a virtual environment for the Python dependencies.

`./launch.sh wave` - This will launch the wave.py script inside the virtual environment and deactivate the environment when it completes.

If you prefer to download wave.py in isolation, you can run it with `python3 wave.py`, but make sure all dependencies are installed globally.

Kind regards.
