### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Dumpff** [thebrumby/HotWalletClaimer#90]
Sorry for too many Issues but i have question. How can I automatically receive updates to my GitHub code? In status i have daily update but always none
```| 24  | daily-update         | None                 | None                 | None```

**Comment by thebrumby** [comment]
Hi @Dumpff,

If you look at the column headings, you will see Wallet Name, Balance, Next Claim, Status etc

The daily update has no balance, no upcoming claim, and no status from the last claim.

If you want to see the update history, you could type this from within `./launch.sh status`

```
logs 24 200
```

Assuming `daily-update` is still ID `24` and `200` is the number of update line you want to see.

```
/app pulling latest changes.
Updating 8bfb14e..bf9c8de
Fast-forward
 README.md | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
blum.py is already up-to-date.
claimer.py is already up-to-date.
cold.py is already up-to-date.
diamond.py is already up-to-date.
enable-proxy.py is already up-to-date.
fuel-autoupgrade.py is already up-to-date.
fuel.py is already up-to-date.
hexacore-autoupgrade.py is already up-to-date.
hexacore.py is already up-to-date.
hot-alt.py is already up-to-date.
hot.py is already up-to-date.
lumcity-autoupgrade.py is already up-to-date.
lumcity.py is already up-to-date.
oxygen-autoupgrade.py is already up-to-date.
oxygen.py is already up-to-date.
pocketfi.py is already up-to-date.
seed.py is already up-to-date.
status.py is already up-to-date.
time-farm.py is already up-to-date.
tree.py is already up-to-date.
vertus.py is already up-to-date.
wave.py is already up-to-date.
Script executed at: Sat Jun 29 13:08:06 UTC 2024
```
