### ISSUE TITLE
Hot Balances error after update script

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#91]
Hi today have some update of the script and i see something happen. It still claim the rewards but the balacances not show and I see some error of the code
 No user agent found, using default.
CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 101 - Attempting to check for the start button (should not be present)...
Step 102 - Attempting to open a link for the app...
Step 103 - Attempting to click the 'Launch' button (probably not present)...
 - Attempting to switch to the app's iFrame...
Step 105 - Attempting to click the 'storage' link...
Step 107 - Attempting to get the pre-claim wait timer...
Step 107 - The pre-claim wait time is : Filled and random offset is 9 minutes.
Step 108 - Attempting to check for NEWS....
Step 109 - Attempting to switch to the app's iFrame...
Step 110 - Attempting to click the claim button...
Step 111 - Let's wait for the pending Claim spinner to stop spinning...
Step 112 - Attempting to get the post-claim wait timer...
Step 112 - Random offset applied to the wait timer of: 6 minutes.
Step 113 - An error occurred: Message:
 Stacktrace:
 #0 0xaafa8b8c2bf4 <unknown>
 #1 0xaafa8b62e040 <unknown>
#2 0xaafa8b664330 <unknown>
#3 0xaafa8b697544 <unknown>
 #4 0xaafa8b659064 <unknown>
 #5 0xaafa8b65a550 <unknown>
#6 0xaafa8b8eadf4 <unknown>
 #7 0xaafa8b8a539c <unknown>
#8 0xaafa8b8a4ecc <unknown>
#9 0xaafa8b8e75dc <unknown>
#10 0xaafa8b8a5d78 <unknown>
#11 0xaafa8b8894c8 <unknown>
#12 0xaafa8b8b05e4 <unknown>
#13 0xaafa8b8b0788 <unknown>
 #14 0xaafa8b8bafa0 <unknown>
 #15 0xe2e2f994597c <unknown>
#16 0xe2e2f99ab7dc <unknown>
STATUS: Successful Claim: Next claim 2h 0m to fill / 126 minutes.

**Comment by thebrumby** [comment]
Hi @bscongluanbui,

Actually, the game developers made a small change to the game's GUI formatting, which caused the issue. The formatting change happened coincidentally after we pushed the new code to the repository.

We have updated the XPath from: `//p[contains(text(), 'HOT Balance:')]/following-sibling::p[1]`
To: `//p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p`

Everything appears to be working again now. Please confirm, and we'll close the issue. 😊

**Comment by bscongluanbui** [comment]
> Hi @bscongluanbui,
> 
> Actually, the game developers made a small change to the game's GUI formatting, which caused the issue. The formatting change happened coincidentally after we pushed the new code to the repository.
> 
> We have updated the XPath from: `//p[contains(text(), 'HOT Balance:')]/following-sibling::p[1]` To: `//p[contains(text(), 'HOT')]/following-sibling::img/following-sibling::p`
> 
> Everything appears to be working again now. Please confirm, and we'll close the issue. 😊

thank you It' working fine. Thanks for the team

**Comment by thebrumby** [comment]
Our pleasure :)
