### ISSUE TITLE
Chromedriver updated makes it crash wich version i need?

### ISSUE THREAD

**Issue by laggedv1** [thebrumby/HotWalletClaimer#93]
Title explains it , i uninstalled my updated chromedriver from the system can someone share the version you need?

**Comment by thebrumby** [comment]
Just as an FYI Chromedriver needs to be the same version as your browser; or at least close to it. This will vary on your set-up, but first get your browser version

```
chromium-browser --version
```

```
google-chrome --version
```

Then Chromedriver will need to be similar :)

```
chromedriver --version
```
