### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by bscongluanbui** [thebrumby/HotWalletClaimer#94]
Hi, I just update this morning and all service got error with 

CHROME DRIVER INITIALISED: Try not to exit the script before it detaches.
Step 101 - Attempting to check for the start button (should not be present)... [//button[contains(., 'START')]]
Step 102 - Attempting to open a link for the app: //a[@href='https://t.me/herewalletbot/app']...
 Step 103 - Attempting to click the 'Launch' button (probably not present)... [//button[contains(@class, 'popup-button') and contains(., 'Launch')]]
Step 104 - Attempting to switch to the app's iFrame...
Step 105 - Attempting to click the 'storage' link... [//h4[text()='Storage']]
Step 105 - An error occurred while trying to click the 'storage' link: unsupported operand type(s) for +: 'float' and 'str'
Step 107 - Attempting to get the pre-claim wait timer... [//div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')]]
Step 107 - Attempting to click the 'storage' link... [//h4[text()='Storage']]
Step 107 - An error occurred while trying to click the 'storage' link: unsupported operand type(s) for +: 'float' and 'str'
tep 107 - Attempting to get the pre-claim wait timer... [//div[contains(., 'Storage')]//p[contains(., 'Filled') or contains(., 'to fill')]]
Other game has the same this error

**Comment by thebrumby** [comment]
Thanks, please update and restart.
