### ISSUE TITLE
something wrong with the new version (game HOT), cannot claim.

### ISSUE THREAD

**Issue by howtoprogram** [thebrumby/HotWalletClaimer#95]
Step 107 - An error occurred while trying to click the 'storage' link: unsupported operand type(s) for +: 'float' and 'str'
63|HOT:164 | Step 107 - Attempted to select storage again...

**Comment by thebrumby** [comment]
Hi, 

Please update your games folder and restart the processes.

Thanks

**Comment by howtoprogram** [comment]
I'm using Docker on Windows, how should I update?

**Comment by thebrumby** [comment]
```
./pull-games.sh
```

Will manually get the latest versions. Your daily updater must have pulled in the short times the bugged code was in the repository.

Thanks

**Comment by thebrumby** [comment]
Also, once the new code is pulled, I imagine the scripts will automatically restart.

If for whatever reason they don't, you can always use 

```
pm2 restart all

```

**Comment by howtoprogram** [comment]
I have restarted 1 of 2 container successfully. The 2nd container is still 100% CPU, waiting for restart all.
Thank you.
If for some reasons, the PC is restart, can I use the above commands to restart all processes or need to set up telegram from the begining?

**Comment by howtoprogram** [comment]
Thanks
